
/*
 * 
 */

package com.haier.stock.eai.getTidan;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.2.3
 * Wed May 28 14:02:40 CST 2014
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "GetTidanZWDFromLESToEHAIER", 
                  wsdlLocation = "file:/D:/idea-workspace/haier-cbs/wsdl-creator/src/main/resources/GetTidanZWDFromLESToEHAIER.wsdl",
                  targetNamespace = "http://www.example.org/GetTidanZWDFromLESToEHAIER/") 
public class GetTidanZWDFromLESToEHAIER_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.example.org/GetTidanZWDFromLESToEHAIER/", "GetTidanZWDFromLESToEHAIER");
    public final static QName GetTidanZWDFromLESToEHAIERSOAP = new QName("http://www.example.org/GetTidanZWDFromLESToEHAIER/", "GetTidanZWDFromLESToEHAIERSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/idea-workspace/haier-cbs/wsdl-creator/src/main/resources/GetTidanZWDFromLESToEHAIER.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/D:/idea-workspace/haier-cbs/wsdl-creator/src/main/resources/GetTidanZWDFromLESToEHAIER.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public GetTidanZWDFromLESToEHAIER_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetTidanZWDFromLESToEHAIER_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetTidanZWDFromLESToEHAIER_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns GetTidanZWDFromLESToEHAIER
     */
    @WebEndpoint(name = "GetTidanZWDFromLESToEHAIERSOAP")
    public GetTidanZWDFromLESToEHAIER getGetTidanZWDFromLESToEHAIERSOAP() {
        return super.getPort(GetTidanZWDFromLESToEHAIERSOAP, GetTidanZWDFromLESToEHAIER.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetTidanZWDFromLESToEHAIER
     */
    @WebEndpoint(name = "GetTidanZWDFromLESToEHAIERSOAP")
    public GetTidanZWDFromLESToEHAIER getGetTidanZWDFromLESToEHAIERSOAP(WebServiceFeature... features) {
        return super.getPort(GetTidanZWDFromLESToEHAIERSOAP, GetTidanZWDFromLESToEHAIER.class, features);
    }

}
