server:
  port: 8081
  jetty:
    max-http-post-size: 10000000
 
interconn:
  project: 3W-CBS
  app: svc-api
  monitor:
   url: http://collector.c.haier.net
   enable: true

spring:
  mvc:
    view:
      suffix: .vm
  velocity:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    resource-loader-path: /templates
    prefix: /
    suffix: .vm


spring.http.multipart.maxFileSize: 20MB
spring.http.multipart.maxRequestSize: 20MB
dubbo:
  name: svc-api
  registry: zookeeper://127.0.0.1:2181

spring.dubbo:
  application.name: consumer
  registry.address: zookeeper://127.0.0.1:2181
  timeout: 10000
  threads: 100
  heartBeats: 10000
  scan: com.haier.svc
#  host: 192.168.1.108


jsondoc:
  version: 1.0
  basePath: http://localhost:8081
  packages: com.haier.svc.api.controller
  playgroundEnabled: true
  displayMethodAs: SUMMARY

idm:
  ldapHost: 10.135.7.142
  loginDN: cn=hbdmuser,ou=user,o=services
  loginPassword: hbdm@20170705

secretKey: KeLy8g7qjmnbgWP1

ketValue: RRS,123

suning:
    url: http://open.suning.com/api/http/sopRequest
    appKey: 458e39b7a6c3d198ca1483a9405fb33c
    appSecret: 7c805c40af42c49ac908b71052a608a0

suninggq:
    url: http://open.suning.com/api/http/sopRequest
    appKey: a41f04c8fde5f1f7d452b3214b4a61ee
    appSecret: cc65dc74111b61c1d89e0e8adce11d59

snqdzx:
    url: http://open.suning.com/api/http/sopRequest
    appKey: f7b0d0b2f22073e1a2ddc9f28b690088
    appSecret: 8eb97c47cb235345cc6ce876198adccc



gmzx:
    url: http://api.coo8.com/ApiControl
    venderId: 80005640
    appKey: bbafa21ade154025

gmzxts:
    url: http://api.coo8.com/ApiControl
    venderId: 80014255
    appKey: 3773ac2db170437b

jingdong:
    url: https://api.jd.com/routerjson
    appKey: 0B014335327F0ECB5FA391C2C65ADC04
    appSecret: 9bbd9cf4fb8146c68017d7f2c009b8bc
    accessToken: 7a6cf2fe-6dae-4cd0-b12e-4df5c3f9005f
    refreshToken: f514add5-a777-4652-a0c5-35198bb35f8d

jingdongbx:
    url: https://api.jd.com/routerjson
    appKey: C42AA639DFF4DA3C34F90D497E940992
    appSecret: 9895a0a1230c467a8ae0b31988714102
    accessToken: 5c91bb13-bd93-429b-9668-46064d5261e6
    refreshToken: fe2a7f30-b103-4953-ab07-8d03fea898b1

dangdang:
    url: http://api.open.dangdang.com/openapi/rest
    appKey: 2100003939
    appSecret: C7A8A15438A842A1A85444C5E1DE17A8
    session: 4835C37A4820E3637938563A3878B185E402AD3808BAB00B947D86B1A5090062
    shopId: 16575
