package com.haier.vehicle.wsdl.mdm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * OSB Service
 *
 * This class was generated by Apache CXF 3.1.12
 * 2018-01-26T20:34:50.292+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "TransCustomerInfoXDToMDM", 
                  wsdlLocation = "file:/D:/java/TransCustomerInfoXDToMDM.wsdl",
                  targetNamespace = "http://www.example.org/TransCustomerInfoXDToMDM/") 
public class TransCustomerInfoXDToMDM_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/TransCustomerInfoXDToMDM/", "TransCustomerInfoXDToMDM");
    public final static QName TransCustomerInfoXDToMDMSOAP = new QName("http://www.example.org/TransCustomerInfoXDToMDM/", "TransCustomerInfoXDToMDMSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/java/TransCustomerInfoXDToMDM.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TransCustomerInfoXDToMDM_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/java/TransCustomerInfoXDToMDM.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TransCustomerInfoXDToMDM_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TransCustomerInfoXDToMDM_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransCustomerInfoXDToMDM_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns TransCustomerInfoXDToMDM
     */
    @WebEndpoint(name = "TransCustomerInfoXDToMDMSOAP")
    public TransCustomerInfoXDToMDM getTransCustomerInfoXDToMDMSOAP() {
        return super.getPort(TransCustomerInfoXDToMDMSOAP, TransCustomerInfoXDToMDM.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransCustomerInfoXDToMDM
     */
    @WebEndpoint(name = "TransCustomerInfoXDToMDMSOAP")
    public TransCustomerInfoXDToMDM getTransCustomerInfoXDToMDMSOAP(WebServiceFeature... features) {
        return super.getPort(TransCustomerInfoXDToMDMSOAP, TransCustomerInfoXDToMDM.class, features);
    }

}
