
package com.haier.vehicle.wsdl.mdm;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-01-26T20:34:50.043+08:00
 * Generated source version: 3.1.12
 * 
 */
public final class TransCustomerInfoXDToMDM_TransCustomerInfoXDToMDMSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/TransCustomerInfoXDToMDM/", "TransCustomerInfoXDToMDM");

    private TransCustomerInfoXDToMDM_TransCustomerInfoXDToMDMSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TransCustomerInfoXDToMDM_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TransCustomerInfoXDToMDM_Service ss = new TransCustomerInfoXDToMDM_Service(wsdlURL, SERVICE_NAME);
        TransCustomerInfoXDToMDM port = ss.getTransCustomerInfoXDToMDMSOAP();  
        
        {
        System.out.println("Invoking transCustomerInfoXDToMDM...");
        java.lang.String _transCustomerInfoXDToMDM_inSYSNAME = "";
        java.lang.String _transCustomerInfoXDToMDM_inMASTERTYPE = "";
        java.lang.String _transCustomerInfoXDToMDM_inTABLENAME = "";
        java.util.List<com.haier.vehicle.wsdl.mdm.HAIERMDMFIELDSVALUETABLE> _transCustomerInfoXDToMDM_inFIELDSVALUETABLE = null;
        javax.xml.ws.Holder<java.lang.String> _transCustomerInfoXDToMDM_outRESULT = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _transCustomerInfoXDToMDM_outRETMSG = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _transCustomerInfoXDToMDM_outRETCODE = new javax.xml.ws.Holder<java.lang.String>();
        port.transCustomerInfoXDToMDM(_transCustomerInfoXDToMDM_inSYSNAME, _transCustomerInfoXDToMDM_inMASTERTYPE, _transCustomerInfoXDToMDM_inTABLENAME, _transCustomerInfoXDToMDM_inFIELDSVALUETABLE, _transCustomerInfoXDToMDM_outRESULT, _transCustomerInfoXDToMDM_outRETMSG, _transCustomerInfoXDToMDM_outRETCODE);

        System.out.println("transCustomerInfoXDToMDM._transCustomerInfoXDToMDM_outRESULT=" + _transCustomerInfoXDToMDM_outRESULT.value);
        System.out.println("transCustomerInfoXDToMDM._transCustomerInfoXDToMDM_outRETMSG=" + _transCustomerInfoXDToMDM_outRETMSG.value);
        System.out.println("transCustomerInfoXDToMDM._transCustomerInfoXDToMDM_outRETCODE=" + _transCustomerInfoXDToMDM_outRETCODE.value);

        }

        System.exit(0);
    }

}
