package com.haier.purchase.data.eai.finance.transfer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-07T17:49:07.071+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://www.example.org/TransferGoodsInfoToEhaierSAP/", name = "TransferGoodsInfoToEhaierSAP")
@XmlSeeAlso({ObjectFactory.class})
public interface TransferGoodsInfoToEhaierSAP {

    @WebMethod(operationName = "TransferGoodsInfoToEhaierSAP", action = "http://www.example.org/TransferGoodsInfoToEhaierSAP/TransferGoodsInfoToEhaierSAP")
    @RequestWrapper(localName = "TransferGoodsInfoToEhaierSAP", targetNamespace = "http://www.example.org/TransferGoodsInfoToEhaierSAP/", className = "com.haier.purchase.data.eai.finance.transfer.TransferGoodsInfoToEhaierSAP_Type")
    @ResponseWrapper(localName = "TransferGoodsInfoToEhaierSAPResponse", targetNamespace = "http://www.example.org/TransferGoodsInfoToEhaierSAP/", className = "com.haier.purchase.data.eai.finance.transfer.TransferGoodsInfoToEhaierSAPResponse")
    public void transferGoodsInfoToEhaierSAP(
        @WebParam(name = "T_ZMMS0010", targetNamespace = "")
        java.util.List<com.haier.purchase.data.eai.finance.transfer.ZMMS0010> tZMMS0010,
        @WebParam(mode = WebParam.Mode.OUT, name = "EX_SUBRC", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> exSUBRC,
        @WebParam(mode = WebParam.Mode.OUT, name = "T_MSG", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.haier.purchase.data.eai.finance.transfer.ZSDS0002>> tMSG
    );
}
