package com.haier.svc.purchase.createscordertoles;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-13T16:43:22.977+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://www.example.org/CreateSCOrderToLES/", name = "CreateSCOrderToLES")
@XmlSeeAlso({ObjectFactory.class})
public interface CreateSCOrderToLES {

    @WebResult(name = "Output", targetNamespace = "")
    @RequestWrapper(localName = "CreateSCOrderToLES", targetNamespace = "http://www.example.org/CreateSCOrderToLES/", className = "com.haier.svc.purchase.createscordertoles.CreateSCOrderToLES_Type")
    @WebMethod(operationName = "CreateSCOrderToLES", action = "http://www.example.org/CreateSCOrderToLES/CreateSCOrderToLES")
    @ResponseWrapper(localName = "CreateSCOrderToLESResponse", targetNamespace = "http://www.example.org/CreateSCOrderToLES/", className = "com.haier.svc.purchase.createscordertoles.CreateSCOrderToLESResponse")
    public java.util.List<com.haier.svc.purchase.createscordertoles.OutputType> createSCOrderToLES(
        @WebParam(name = "Input", targetNamespace = "")
        java.util.List<com.haier.svc.purchase.createscordertoles.InputType> input
    );
}
