package com.haier.stock.eai.getbominfofromlestoehaier;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.2.3
 * Mon Jun 24 15:18:34 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebServiceClient(name = "GetBomInfoFromLESToEHAIER", wsdlLocation = "file:/Users/benio/Documents/projects/wsdl-creator/wsdl-creator/src/main/resources/GetBomInfoFromLESToEHAIER.wsdl", targetNamespace = "http://www.example.org/GetBomInfoFromLESToEHAIER/")
public class GetBomInfoFromLESToEHAIER_Service extends Service {

    public final static URL   WSDL_LOCATION;
    public final static QName SERVICE                       = new QName(
                                                                "http://www.example.org/GetBomInfoFromLESToEHAIER/",
                                                                "GetBomInfoFromLESToEHAIER");
    public final static QName GetBomInfoFromLESToEHAIERSOAP = new QName(
                                                                "http://www.example.org/GetBomInfoFromLESToEHAIER/",
                                                                "GetBomInfoFromLESToEHAIERSOAP");
    static {
        URL url = null;
        try {
            url = new URL(
                "file:/Users/benio/Documents/projects/wsdl-creator/wsdl-creator/src/main/resources/GetBomInfoFromLESToEHAIER.wsdl");
        } catch (MalformedURLException e) {
            System.err
                .println("Can not initialize the default wsdl from file:/Users/benio/Documents/projects/wsdl-creator/wsdl-creator/src/main/resources/GetBomInfoFromLESToEHAIER.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public GetBomInfoFromLESToEHAIER_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetBomInfoFromLESToEHAIER_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetBomInfoFromLESToEHAIER_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns GetBomInfoFromLESToEHAIER
     */
    @WebEndpoint(name = "GetBomInfoFromLESToEHAIERSOAP")
    public GetBomInfoFromLESToEHAIER getGetBomInfoFromLESToEHAIERSOAP() {
        return super.getPort(GetBomInfoFromLESToEHAIERSOAP, GetBomInfoFromLESToEHAIER.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetBomInfoFromLESToEHAIER
     */
    @WebEndpoint(name = "GetBomInfoFromLESToEHAIERSOAP")
    public GetBomInfoFromLESToEHAIER getGetBomInfoFromLESToEHAIERSOAP(WebServiceFeature... features) {
        return super.getPort(GetBomInfoFromLESToEHAIERSOAP, GetBomInfoFromLESToEHAIER.class,
            features);
    }

}
