package com.haier.stock.eai.getbominfofromlestoehaier;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Mon Jun 24 15:18:34 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebService(targetNamespace = "http://www.example.org/GetBomInfoFromLESToEHAIER/", name = "GetBomInfoFromLESToEHAIER")
@XmlSeeAlso({ ObjectFactory.class })
public interface GetBomInfoFromLESToEHAIER {

    @RequestWrapper(localName = "GetBomInfoFromLESToEHAIER", targetNamespace = "http://www.example.org/GetBomInfoFromLESToEHAIER/", className = "org.example.getbominfofromlestoehaier.GetBomInfoFromLESToEHAIER_Type")
    @ResponseWrapper(localName = "GetBomInfoFromLESToEHAIERResponse", targetNamespace = "http://www.example.org/GetBomInfoFromLESToEHAIER/", className = "org.example.getbominfofromlestoehaier.GetBomInfoFromLESToEHAIERResponse")
    @WebMethod(operationName = "GetBomInfoFromLESToEHAIER", action = "http://www.example.org/GetBomInfoFromLESToEHAIER/GetBomInfoFromLESToEHAIER")
    public void getBomInfoFromLESToEHAIER(
        @WebParam(name = "Z_INPUT_PARA", targetNamespace = "") String zINPUTPARA,
        @WebParam(mode = WebParam.Mode.OUT, name = "FLAG", targetNamespace = "") javax.xml.ws.Holder<String> flag,
        @WebParam(mode = WebParam.Mode.OUT, name = "MESSAGE", targetNamespace = "") javax.xml.ws.Holder<String> message,
        @WebParam(mode = WebParam.Mode.OUT, name = "Z_OUTPUT_PARA", targetNamespace = "") javax.xml.ws.Holder<java.util.List<com.haier.stock.eai.getbominfofromlestoehaier.ZLESDCMS24>> zOUTPUTPARA);
}
