package com.haier.purchase.data.model;

import java.io.Serializable;
import java.util.Date;

public class ExchangeGoods implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 4788058809077730542L;

	 /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_goods.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_goods.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_goods.storeOrderCode
     *
     * @mbggenerated
     */
    private String storeordercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_goods.tradeItemId
     *
     * @mbggenerated
     */
    private String tradeitemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_goods.tradeId
     *
     * @mbggenerated
     */
    private String tradeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_goods.itemCode
     *
     * @mbggenerated
     */
    private String itemcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_goods.itemQuantity
     *
     * @mbggenerated
     */
    private Integer itemquantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_goods.itemAmount
     *
     * @mbggenerated
     */
    private Long itemamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_goods.orderCode
     *
     * @mbggenerated
     */
    private String ordercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_goods.storeCode
     *
     * @mbggenerated
     */
    private String storecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_goods.consignTime
     *
     * @mbggenerated
     */
    private Date consigntime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_goods.data
     *
     * @mbggenerated
     */
    private String data;

    private String orderProductsCn;//旧网单号
    private String orderProductsCnNew;//新网单号
    private String packageCode;//tb单号
    private String tmsOrderCode;//运单号
    private Integer rows; //分页用
    private Integer page;//分页

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_goods.id
     *
     * @return the value of exchange_goods.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_goods.id
     *
     * @param id the value for exchange_goods.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_goods.status
     *
     * @return the value of exchange_goods.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_goods.status
     *
     * @param status the value for exchange_goods.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_goods.storeOrderCode
     *
     * @return the value of exchange_goods.storeOrderCode
     *
     * @mbggenerated
     */
    public String getStoreordercode() {
        return storeordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_goods.storeOrderCode
     *
     * @param storeordercode the value for exchange_goods.storeOrderCode
     *
     * @mbggenerated
     */
    public void setStoreordercode(String storeordercode) {
        this.storeordercode = storeordercode == null ? null : storeordercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_goods.tradeItemId
     *
     * @return the value of exchange_goods.tradeItemId
     *
     * @mbggenerated
     */
    public String getTradeitemid() {
        return tradeitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_goods.tradeItemId
     *
     * @param tradeitemid the value for exchange_goods.tradeItemId
     *
     * @mbggenerated
     */
    public void setTradeitemid(String tradeitemid) {
        this.tradeitemid = tradeitemid == null ? null : tradeitemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_goods.tradeId
     *
     * @return the value of exchange_goods.tradeId
     *
     * @mbggenerated
     */
    public String getTradeid() {
        return tradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_goods.tradeId
     *
     * @param tradeid the value for exchange_goods.tradeId
     *
     * @mbggenerated
     */
    public void setTradeid(String tradeid) {
        this.tradeid = tradeid == null ? null : tradeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_goods.itemCode
     *
     * @return the value of exchange_goods.itemCode
     *
     * @mbggenerated
     */
    public String getItemcode() {
        return itemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_goods.itemCode
     *
     * @param itemcode the value for exchange_goods.itemCode
     *
     * @mbggenerated
     */
    public void setItemcode(String itemcode) {
        this.itemcode = itemcode == null ? null : itemcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_goods.itemQuantity
     *
     * @return the value of exchange_goods.itemQuantity
     *
     * @mbggenerated
     */
    public Integer getItemquantity() {
        return itemquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_goods.itemQuantity
     *
     * @param itemquantity the value for exchange_goods.itemQuantity
     *
     * @mbggenerated
     */
    public void setItemquantity(Integer itemquantity) {
        this.itemquantity = itemquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_goods.itemAmount
     *
     * @return the value of exchange_goods.itemAmount
     *
     * @mbggenerated
     */
    public Long getItemamount() {
        return itemamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_goods.itemAmount
     *
     * @param itemamount the value for exchange_goods.itemAmount
     *
     * @mbggenerated
     */
    public void setItemamount(Long itemamount) {
        this.itemamount = itemamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_goods.orderCode
     *
     * @return the value of exchange_goods.orderCode
     *
     * @mbggenerated
     */
    public String getOrdercode() {
        return ordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_goods.orderCode
     *
     * @param ordercode the value for exchange_goods.orderCode
     *
     * @mbggenerated
     */
    public void setOrdercode(String ordercode) {
        this.ordercode = ordercode == null ? null : ordercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_goods.storeCode
     *
     * @return the value of exchange_goods.storeCode
     *
     * @mbggenerated
     */
    public String getStorecode() {
        return storecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_goods.storeCode
     *
     * @param storecode the value for exchange_goods.storeCode
     *
     * @mbggenerated
     */
    public void setStorecode(String storecode) {
        this.storecode = storecode == null ? null : storecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_goods.consignTime
     *
     * @return the value of exchange_goods.consignTime
     *
     * @mbggenerated
     */
    public Date getConsigntime() {
        return consigntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_goods.consignTime
     *
     * @param consigntime the value for exchange_goods.consignTime
     *
     * @mbggenerated
     */
    public void setConsigntime(Date consigntime) {
        this.consigntime = consigntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_goods.data
     *
     * @return the value of exchange_goods.data
     *
     * @mbggenerated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_goods.data
     *
     * @param data the value for exchange_goods.data
     *
     * @mbggenerated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    public String getOrderProductsCn() {
        return orderProductsCn;
    }

    public void setOrderProductsCn(String orderProductsCn) {
        this.orderProductsCn = orderProductsCn;
    }


    public String getOrderProductsCnNew() {
        return orderProductsCnNew;
    }

    public void setOrderProductsCnNew(String orderProductsCnNew) {
        this.orderProductsCnNew = orderProductsCnNew;
    }

    public String getPackageCode() {
        return packageCode;
    }

    public void setPackageCode(String packageCode) {
        this.packageCode = packageCode;
    }

    public String getTmsOrderCode() {
        return tmsOrderCode;
    }

    public void setTmsOrderCode(String tmsOrderCode) {
        this.tmsOrderCode = tmsOrderCode;
    }

    public Integer getRows() {
        return rows;
    }

    public void setRows(Integer rows) {
        this.rows = rows;
    }

    public Integer getPage() {
        return page;
    }

    public void setPage(Integer page) {
        this.page = page;
    }
}