package com.haier.purchase.data.model;

import java.io.Serializable;
import java.util.Date;

public class ReturnTable implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -5781730684445529423L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnTable.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnTable.subSourceOrderCode
     *
     * @mbggenerated
     */
    private String subSourceOrderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnTable.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnTable.data
     *
     * @mbggenerated
     */
    private String data;

    private int exceptionTimes;//匹配异常次数

    public ReturnTable() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnTable.id
     *
     * @return the value of returnTable.id
     *
     * @mbggenerated
     */
	  public Integer getId() {
		return id;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnTable.id
     *
     * @param integer the value for returnTable.id
     *
     * @mbggenerated
     */
	  public void setId(Integer id) {
		this.id = id;
	}

    public String getSubSourceOrderCode() {
        return subSourceOrderCode;
    }

    public void setSubSourceOrderCode(String subSourceOrderCode) {
        this.subSourceOrderCode = subSourceOrderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnTable.status
     *
     * @return the value of returnTable.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnTable.status
     *
     * @param status the value for returnTable.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnTable.data
     *
     * @return the value of returnTable.data
     *
     * @mbggenerated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnTable.data
     *
     * @param data the value for returnTable.data
     *
     * @mbggenerated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    public int getExceptionTimes() {
        return exceptionTimes;
    }

    public void setExceptionTimes(int exceptionTimes) {
        this.exceptionTimes = exceptionTimes;
    }

    private String returnOrderId;//lbx单号
    private String itemCode;
    private Integer rows; //分页用
    private Integer page;//分页


    public String getReturnOrderId() {
        return returnOrderId;
    }

    public void setReturnOrderId(String returnOrderId) {
        this.returnOrderId = returnOrderId;
    }

    public String getItemCode() {
        return itemCode;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    public String getWarehouseCode() {
        return warehouseCode;
    }

    public void setWarehouseCode(String warehouseCode) {
        this.warehouseCode = warehouseCode;
    }

    public Date getOrderConfirmTime() {
        return orderConfirmTime;
    }

    public void setOrderConfirmTime(Date orderConfirmTime) {
        this.orderConfirmTime = orderConfirmTime;
    }

    public int getActualQty() {
        return actualQty;
    }

    public void setActualQty(int actualQty) {
        this.actualQty = actualQty;
    }

    public String getDetailAddress() {
        return detailAddress;
    }

    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    private String warehouseCode;
    private Date orderConfirmTime;
    private int actualQty;
    private String detailAddress;
    private String name;
    private String mobile;

    public Integer getRows() {
        return rows;
    }

    public void setRows(Integer rows) {
        this.rows = rows;
    }

    public Integer getPage() {
        return page;
    }

    public void setPage(Integer page) {
        this.page = page;
    }
}