package com.haier.stock.canceltidan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-13T17:22:40.294+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://www.example.org/JdeAndLesLoseValidity/", name = "JdeAndLesLoseValidity")
@XmlSeeAlso({ObjectFactory.class})
public interface JdeAndLesLoseValidity {

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "JdeAndLesLoseValidity", targetNamespace = "http://www.example.org/JdeAndLesLoseValidity/", className = "com.haier.stock.canceltidan.JdeAndLesLoseValidity_Type")
    @WebMethod(operationName = "JdeAndLesLoseValidity", action = "http://www.example.org/JdeAndLesLoseValidity/JdeAndLesLoseValidity")
    @ResponseWrapper(localName = "JdeAndLesLoseValidityResponse", targetNamespace = "http://www.example.org/JdeAndLesLoseValidity/", className = "com.haier.stock.canceltidan.JdeAndLesLoseValidityResponse")
    public JdeAndLesLoseValidityResponse.Out jdeAndLesLoseValidity(
        @WebParam(name = "in", targetNamespace = "")
        JdeAndLesLoseValidity_Type.In in
    );
}
