package com.haier.stock.eai.finance.pushprosale;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 08 14:06:05 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebService(targetNamespace = "http://www.example.org/PushProSaleOrderToEhaierSAP/", name = "PushProSaleOrderToEhaierSAP")
@XmlSeeAlso({ ObjectFactory.class })
public interface PushProSaleOrderToEhaierSAP {

    @RequestWrapper(localName = "PushProSaleOrderToEhaierSAP", targetNamespace = "http://www.example.org/PushProSaleOrderToEhaierSAP/", className = "org.example.pushprosaleordertoehaiersap.PushProSaleOrderToEhaierSAP_Type")
    @ResponseWrapper(localName = "PushProSaleOrderToEhaierSAPResponse", targetNamespace = "http://www.example.org/PushProSaleOrderToEhaierSAP/", className = "org.example.pushprosaleordertoehaiersap.PushProSaleOrderToEhaierSAPResponse")
    @WebMethod(operationName = "PushProSaleOrderToEhaierSAP", action = "http://www.example.org/PushProSaleOrderToEhaierSAP/PushProSaleOrderToEhaierSAP")
    public void pushProSaleOrderToEhaierSAP(
        @WebParam(name = "T_ZSDS0008", targetNamespace = "") java.util.List<com.haier.stock.eai.finance.pushprosale.ZSDS0008> tZSDS0008,
        @WebParam(mode = WebParam.Mode.OUT, name = "EX_SUBRC", targetNamespace = "") javax.xml.ws.Holder<Integer> exSUBRC,
        @WebParam(mode = WebParam.Mode.OUT, name = "T_MSG", targetNamespace = "") javax.xml.ws.Holder<java.util.List<com.haier.stock.eai.finance.pushprosale.ZSDS0002>> tMSG);
}
