/*
 * 
 */

package com.haier.stock.eai.finance.pushprosale;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 08 14:06:05 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebServiceClient(name = "PushProSaleOrderToEhaierSAP", wsdlLocation = "file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/PushProSaleOrderToEhaierSAP.wsdl", targetNamespace = "http://www.example.org/PushProSaleOrderToEhaierSAP/")
public class PushProSaleOrderToEhaierSAP_Service extends Service {

    public final static URL   WSDL_LOCATION;
    public final static QName SERVICE                         = new QName(
                                                                  "http://www.example.org/PushProSaleOrderToEhaierSAP/",
                                                                  "PushProSaleOrderToEhaierSAP");
    public final static QName PushProSaleOrderToEhaierSAPSOAP = new QName(
                                                                  "http://www.example.org/PushProSaleOrderToEhaierSAP/",
                                                                  "PushProSaleOrderToEhaierSAPSOAP");
    static {
        URL url = null;
        try {
            url = new URL(
                "file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/PushProSaleOrderToEhaierSAP.wsdl");
        } catch (MalformedURLException e) {
            System.err
                .println("Can not initialize the default wsdl from file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/PushProSaleOrderToEhaierSAP.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PushProSaleOrderToEhaierSAP_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PushProSaleOrderToEhaierSAP_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PushProSaleOrderToEhaierSAP_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns PushProSaleOrderToEhaierSAP
     */
    @WebEndpoint(name = "PushProSaleOrderToEhaierSAPSOAP")
    public PushProSaleOrderToEhaierSAP getPushProSaleOrderToEhaierSAPSOAP() {
        return super.getPort(PushProSaleOrderToEhaierSAPSOAP, PushProSaleOrderToEhaierSAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PushProSaleOrderToEhaierSAP
     */
    @WebEndpoint(name = "PushProSaleOrderToEhaierSAPSOAP")
    public PushProSaleOrderToEhaierSAP getPushProSaleOrderToEhaierSAPSOAP(WebServiceFeature... features) {
        return super.getPort(PushProSaleOrderToEhaierSAPSOAP, PushProSaleOrderToEhaierSAP.class,
            features);
    }

}
