package com.haier.purchase.data.dao.purchase;

import java.util.List;

import com.haier.purchase.data.model.ExchangeGoods;
import com.haier.purchase.data.model.ReturnTable;

public interface ExchangeGoodsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_goods
     *
     * @mbggenerated
     */
    int insert(ExchangeGoods record);
    
    int insertEx(List<ExchangeGoods> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_goods
     *
     * @mbggenerated
     */
    int insertSelective(ExchangeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_goods
     *
     * @mbggenerated
     */
    ExchangeGoods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExchangeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ExchangeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExchangeGoods record);

	List<ExchangeGoods> findExchangeTable();

	int updateExchange(ExchangeGoods ex);

	String findMax();

    int updateWD(ExchangeGoods ex);

    List<ExchangeGoods> findAll(ExchangeGoods params);


    int findAllCount(ExchangeGoods params);
}