package com.haier.vehicle.wsdl.saleorder;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-08T14:42:07.342+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/Application/InsertSaleBill_ZKToCRM/BPELProcess", name = "BPELProcess")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BPELProcess {

    @WebResult(name = "InsertSaleBill_GVS2ProcessResponse", targetNamespace = "http://xmlns.oracle.com/Application/InsertSaleBill_ZKToCRM/BPELProcess", partName = "payload")
    @WebMethod(action = "process")
    public InsertSaleBillGVS2ProcessResponse process(
            @WebParam(partName = "payload", name = "InsertSaleBill_GVS2ProcessRequest", targetNamespace = "http://xmlns.oracle.com/Application/InsertSaleBill_ZKToCRM/BPELProcess")
                    InsertSaleBillGVS2ProcessRequest payload
    ) throws RemoteExceptionMessage;
}
