interconn:
  project: 3W-CBS
  app: order-svc
  monitor:
    url: http://collector.c.haier.net
    enable: false
  trace:
    url: http://collector-trace.c.haier.net
    sample: 0 #抽样率，0：关闭，1：全采样，sample<1：部分采样

dubbo:
  registry: 10.162.162.43:2181,10.162.162.44:2181,10.162.162.45:2181
  port: 20892
  timeout: 10000
  threads: 100
  heartBeats: 10000

wsdlPath: /wsdl_test
mdm:
  location: /wsdlFile


url:
  ##VOM开提单地址 START
  orderToLesUrl: http://10.138.40.168:8001/EAI/service/VOM/CommonGetWayToVOM/CommonGetWayToVOM
  ##VOM开提单地址 END

  ##dispatchingByHPUrl start 没有测试地址 所以测试先用正式地址 人工处理测试数据
  dispatchingByHPUrl: http://omsjd.rrswl.com:10001/services-jd/scorder/receiveOrder.do
  ##dispatchingByHPUrl end