interconn:
  project: 3W-CBS
  app: order-svc
  monitor:
    url: http://collector.c.haier.net
    enable: false
  trace:
    url: http://collector-trace.c.haier.net
    sample: 0 #抽样率，0：关闭，1：全采样，sample<1：部分采样

dubbo:
  registry: 10.138.8.223:2181,10.138.8.224:2181,10.138.8.225:2181
  port: 20892
  timeout: 10000
  threads: 100
  heartBeats: 10000

wsdlPath: /wsdl
mdm:
  location: /wsdlFile

url:
  ##orderToLesUrl START
  orderToLesUrl: http://10.135.1.110:7001/EAI/RoutingProxyService/EAI_REST_POST_ServiceRoot?INT_CODE=EAI_INT_1353
  ##orderToLesUrl END

  ##dispatchingByHPUrl start
  dispatchingByHPUrl: http://omsjd.rrswl.com:10001/services-jd/scorder/receiveOrder.do
  ##dispatchingByHPUrl end

