package com.haier.shop.model;


import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by CodeGen
 * Desc: 品类品牌产业数据维护表Model类
 * Date: 2018-05-22
 */
public class OdsTMFXCategoryIndustry implements Serializable {

    private static final long serialVersionUID = -7746939111531610510L;
    private Long id;
    
    /**
     * 品牌
     */
    private String brand;
    
    /**
     * 品类
     */
    private String category;
    
    /**
     * 产业
     */
    private String industry;
    
    /**
     * 创建时间
     */
    private Date createTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getIndustry() {
        return industry;
    }

    public void setIndustry(String industry) {
        this.industry = industry;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}
