package com.haier.shop.model;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Code generated by CodeGen
 * Desc: 佣金结算数据推送队列Model类
 * Date: 2018-05-28
 */
public class SettlementInvoiceData implements Serializable {

    private static final long serialVersionUID = 450840666699309744L;
    private Long id;
    
    /**
     * 佣金结算发票队列ID
     */
    private Integer settlementinvoicequeueid;
    
    /**
     * 网单号[发票表]
     */
    private String cordersn;
    
    /**
     * 网单号[网单表]
     */
    private String oldcordersn;
    
    /**
     * 来源订单号[订单表]
     */
    private String sourceordersn;
    
    /**
     * 订单来源[订单表]已转名称
     */
    private String source;
    
    /**
     * 销售代表[订单表]
     */
    private String sellpeople;
    
    /**
     * 品类[发票表]
     */
    private String productcatename;
    
    /**
     * 品牌[Brands表]
     */
    private String brandname;
    
    /**
     * SKU[网单表]
     */
    private String sku;
    
    /**
     * 宝贝型号[网单表]
     */
    private String productname;
    
    /**
     * 收货人姓名[订单表]
     */
    private String consignee;
    
    /**
     * 订单付款时间
     */
    private Integer paytime;
    
    /**
     * 销售数量[发票表]
     */
    private Integer number;
    
    /**
     * 总价(发票金额)[发票表]
     */
    private BigDecimal amount;
    
    /**
     * 期间
     */
    private String month;
    
    /**
     * 年度
     */
    private String year;
    
    /**
     * 开票状态[网单表]已转名称
     */
    private String ismakereceipt;
    
    /**
     * 结算方式,0:人工,1:系统
     */
    private Integer settlementtype;
    
    /**
     * 是否成功,0:否,1:是,2:不再处理
     */
    private Integer success;
    
    /**
     * 推送次数, 超过20就不在处理
     */
    private Integer count;
    
    /**
     * 发票状态,1:已开票,4:作废/冲红
     */
    private Integer statustype;
    
    /**
     * 发票时间(开票/作废时间)
     */
    private Long invoicetime;
    
    /**
     * 审核状态,0:无需审核,1:待业务审核,-1:业务审核拒绝,2:待财务审核,-2:财务审核拒绝,3:审核通过
     */
    private Integer state;
    
    /**
     * 业务审核人
     */
    private String busauditorpeople;
    
    /**
     * 业务审核时间
     */
    private Date busauditortime;
    
    /**
     * 财务审核人
     */
    private String finauditorpeople;
    
    /**
     * 财务审核时间
     */
    private Date finauditortime;
    
    /**
     * 推送数据
     */
    private String pushdata;
    
    /**
     * 反馈数据
     */
    private String returndata;
    
    /**
     * 信息
     */
    private String lastmessage;
    
    /**
     * 创建时间
     */
    private Date addtime;
    
    /**
     * 数据添加人
     */
    private String addpeople;
    
    /**
     * 数据更新时间
     */
    private Date modifytime;

    /**
     * 产业
     */
    private String industry;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSettlementinvoicequeueid() {
        return settlementinvoicequeueid;
    }

    public void setSettlementinvoicequeueid(Integer settlementinvoicequeueid) {
        this.settlementinvoicequeueid = settlementinvoicequeueid;
    }

    public String getCordersn() {
        return cordersn;
    }

    public void setCordersn(String cordersn) {
        this.cordersn = cordersn;
    }

    public String getOldcordersn() {
        return oldcordersn;
    }

    public void setOldcordersn(String oldcordersn) {
        this.oldcordersn = oldcordersn;
    }

    public String getSourceordersn() {
        return sourceordersn;
    }

    public void setSourceordersn(String sourceordersn) {
        this.sourceordersn = sourceordersn;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getSellpeople() {
        return sellpeople;
    }

    public void setSellpeople(String sellpeople) {
        this.sellpeople = sellpeople;
    }

    public String getProductcatename() {
        return productcatename;
    }

    public void setProductcatename(String productcatename) {
        this.productcatename = productcatename;
    }

    public String getBrandname() {
        return brandname;
    }

    public void setBrandname(String brandname) {
        this.brandname = brandname;
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public String getProductname() {
        return productname;
    }

    public void setProductname(String productname) {
        this.productname = productname;
    }

    public String getConsignee() {
        return consignee;
    }

    public void setConsignee(String consignee) {
        this.consignee = consignee;
    }

    public Integer getPaytime() {
        return paytime;
    }

    public void setPaytime(Integer paytime) {
        this.paytime = paytime;
    }

    public Integer getNumber() {
        return number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getMonth() {
        return month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public String getIsmakereceipt() {
        return ismakereceipt;
    }

    public void setIsmakereceipt(String ismakereceipt) {
        this.ismakereceipt = ismakereceipt;
    }

    public Integer getSettlementtype() {
        return settlementtype;
    }

    public void setSettlementtype(Integer settlementtype) {
        this.settlementtype = settlementtype;
    }

    public Integer getSuccess() {
        return success;
    }

    public void setSuccess(Integer success) {
        this.success = success;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Integer getStatustype() {
        return statustype;
    }

    public void setStatustype(Integer statustype) {
        this.statustype = statustype;
    }

    public Long getInvoicetime() {
        return invoicetime;
    }

    public void setInvoicetime(Long invoicetime) {
        this.invoicetime = invoicetime;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public String getBusauditorpeople() {
        return busauditorpeople;
    }

    public void setBusauditorpeople(String busauditorpeople) {
        this.busauditorpeople = busauditorpeople;
    }

    public Date getBusauditortime() {
        return busauditortime;
    }

    public void setBusauditortime(Date busauditortime) {
        this.busauditortime = busauditortime;
    }

    public String getFinauditorpeople() {
        return finauditorpeople;
    }

    public void setFinauditorpeople(String finauditorpeople) {
        this.finauditorpeople = finauditorpeople;
    }

    public Date getFinauditortime() {
        return finauditortime;
    }

    public void setFinauditortime(Date finauditortime) {
        this.finauditortime = finauditortime;
    }

    public String getPushdata() {
        return pushdata;
    }

    public void setPushdata(String pushdata) {
        this.pushdata = pushdata;
    }

    public String getReturndata() {
        return returndata;
    }

    public void setReturndata(String returndata) {
        this.returndata = returndata;
    }

    public String getLastmessage() {
        return lastmessage;
    }

    public void setLastmessage(String lastmessage) {
        this.lastmessage = lastmessage;
    }

    public Date getAddtime() {
        return addtime;
    }

    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    public String getAddpeople() {
        return addpeople;
    }

    public void setAddpeople(String addpeople) {
        this.addpeople = addpeople;
    }

    public Date getModifytime() {
        return modifytime;
    }

    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    public String getIndustry() {
        return industry;
    }

    public void setIndustry(String industry) {
        this.industry = industry;
    }
}
