package com.haier.shop.model;


import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by CodeGen
 * Desc: 结算日志表Model类
 * Date: 2018-08-01
 */
public class SettlementLog implements Serializable {


    private Long id;
    
    /**
     * 年度
     */
    private String year;
    
    /**
     * 月份
     */
    private String month;
    
    /**
     * 类型 y年度 q季度 m月度
     */
    private String type;
    
    /**
     * 1、执行中 2、执行出错 3、已结束
     */
    private String status;
    
    /**
     * 开始时间
     */
    private Date statusDate;
    
    /**
     * 结束时间
     */
    private Date endDate;
    
    /**
     * 创建时间
     */
    private Date createDate;
    
    /**
     * 修改时间
     */
    private Date updateDate;
    
    private String source;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public String getMonth() {
        return month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getStatusDate() {
        return statusDate;
    }

    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

	public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}
    
}
