package com.haier.shop.model;

import java.io.Serializable;

public class StoragesWwwRelas implements Serializable {

    private static final long serialVersionUID = -4657534706726190814L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storageswwwrelas.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storageswwwrelas.storLevel
     *
     * @mbggenerated
     */
    private Integer storlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storageswwwrelas.eStorName
     *
     * @mbggenerated
     */
    private String estorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storageswwwrelas.wwwStorName
     *
     * @mbggenerated
     */
    private String wwwstorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storageswwwrelas.wwwStorCode
     *
     * @mbggenerated
     */
    private String wwwstorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storageswwwrelas.waStorCode
     *
     * @mbggenerated
     */
    private String wastorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storageswwwrelas.tradeDescription
     *
     * @mbggenerated
     */
    private String tradedescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storageswwwrelas.corMainStor
     *
     * @mbggenerated
     */
    private String cormainstor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storageswwwrelas.corMainStorCode
     *
     * @mbggenerated
     */
    private String cormainstorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storageswwwrelas.mainStor
     *
     * @mbggenerated
     */
    private String mainstor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storageswwwrelas.centerCode
     *
     * @mbggenerated
     */
    private String centercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storageswwwrelas.gCode
     *
     * @mbggenerated
     */
    private String gcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storageswwwrelas.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storageswwwrelas.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storageswwwrelas.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storageswwwrelas.caiNiaoCode
     *
     * @mbggenerated
     */
    private String cainiaocode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storageswwwrelas.id
     *
     * @return the value of storageswwwrelas.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storageswwwrelas.id
     *
     * @param id the value for storageswwwrelas.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storageswwwrelas.storLevel
     *
     * @return the value of storageswwwrelas.storLevel
     *
     * @mbggenerated
     */
    public Integer getStorlevel() {
        return storlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storageswwwrelas.storLevel
     *
     * @param storlevel the value for storageswwwrelas.storLevel
     *
     * @mbggenerated
     */
    public void setStorlevel(Integer storlevel) {
        this.storlevel = storlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storageswwwrelas.eStorName
     *
     * @return the value of storageswwwrelas.eStorName
     *
     * @mbggenerated
     */
    public String getEstorname() {
        return estorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storageswwwrelas.eStorName
     *
     * @param estorname the value for storageswwwrelas.eStorName
     *
     * @mbggenerated
     */
    public void setEstorname(String estorname) {
        this.estorname = estorname == null ? null : estorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storageswwwrelas.wwwStorName
     *
     * @return the value of storageswwwrelas.wwwStorName
     *
     * @mbggenerated
     */
    public String getWwwstorname() {
        return wwwstorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storageswwwrelas.wwwStorName
     *
     * @param wwwstorname the value for storageswwwrelas.wwwStorName
     *
     * @mbggenerated
     */
    public void setWwwstorname(String wwwstorname) {
        this.wwwstorname = wwwstorname == null ? null : wwwstorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storageswwwrelas.wwwStorCode
     *
     * @return the value of storageswwwrelas.wwwStorCode
     *
     * @mbggenerated
     */
    public String getWwwstorcode() {
        return wwwstorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storageswwwrelas.wwwStorCode
     *
     * @param wwwstorcode the value for storageswwwrelas.wwwStorCode
     *
     * @mbggenerated
     */
    public void setWwwstorcode(String wwwstorcode) {
        this.wwwstorcode = wwwstorcode == null ? null : wwwstorcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storageswwwrelas.waStorCode
     *
     * @return the value of storageswwwrelas.waStorCode
     *
     * @mbggenerated
     */
    public String getWastorcode() {
        return wastorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storageswwwrelas.waStorCode
     *
     * @param wastorcode the value for storageswwwrelas.waStorCode
     *
     * @mbggenerated
     */
    public void setWastorcode(String wastorcode) {
        this.wastorcode = wastorcode == null ? null : wastorcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storageswwwrelas.tradeDescription
     *
     * @return the value of storageswwwrelas.tradeDescription
     *
     * @mbggenerated
     */
    public String getTradedescription() {
        return tradedescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storageswwwrelas.tradeDescription
     *
     * @param tradedescription the value for storageswwwrelas.tradeDescription
     *
     * @mbggenerated
     */
    public void setTradedescription(String tradedescription) {
        this.tradedescription = tradedescription == null ? null : tradedescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storageswwwrelas.corMainStor
     *
     * @return the value of storageswwwrelas.corMainStor
     *
     * @mbggenerated
     */
    public String getCormainstor() {
        return cormainstor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storageswwwrelas.corMainStor
     *
     * @param cormainstor the value for storageswwwrelas.corMainStor
     *
     * @mbggenerated
     */
    public void setCormainstor(String cormainstor) {
        this.cormainstor = cormainstor == null ? null : cormainstor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storageswwwrelas.corMainStorCode
     *
     * @return the value of storageswwwrelas.corMainStorCode
     *
     * @mbggenerated
     */
    public String getCormainstorcode() {
        return cormainstorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storageswwwrelas.corMainStorCode
     *
     * @param cormainstorcode the value for storageswwwrelas.corMainStorCode
     *
     * @mbggenerated
     */
    public void setCormainstorcode(String cormainstorcode) {
        this.cormainstorcode = cormainstorcode == null ? null : cormainstorcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storageswwwrelas.mainStor
     *
     * @return the value of storageswwwrelas.mainStor
     *
     * @mbggenerated
     */
    public String getMainstor() {
        return mainstor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storageswwwrelas.mainStor
     *
     * @param mainstor the value for storageswwwrelas.mainStor
     *
     * @mbggenerated
     */
    public void setMainstor(String mainstor) {
        this.mainstor = mainstor == null ? null : mainstor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storageswwwrelas.centerCode
     *
     * @return the value of storageswwwrelas.centerCode
     *
     * @mbggenerated
     */
    public String getCentercode() {
        return centercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storageswwwrelas.centerCode
     *
     * @param centercode the value for storageswwwrelas.centerCode
     *
     * @mbggenerated
     */
    public void setCentercode(String centercode) {
        this.centercode = centercode == null ? null : centercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storageswwwrelas.gCode
     *
     * @return the value of storageswwwrelas.gCode
     *
     * @mbggenerated
     */
    public String getGcode() {
        return gcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storageswwwrelas.gCode
     *
     * @param gcode the value for storageswwwrelas.gCode
     *
     * @mbggenerated
     */
    public void setGcode(String gcode) {
        this.gcode = gcode == null ? null : gcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storageswwwrelas.address
     *
     * @return the value of storageswwwrelas.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storageswwwrelas.address
     *
     * @param address the value for storageswwwrelas.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storageswwwrelas.remark
     *
     * @return the value of storageswwwrelas.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storageswwwrelas.remark
     *
     * @param remark the value for storageswwwrelas.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storageswwwrelas.mobile
     *
     * @return the value of storageswwwrelas.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storageswwwrelas.mobile
     *
     * @param mobile the value for storageswwwrelas.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storageswwwrelas.caiNiaoCode
     *
     * @return the value of storageswwwrelas.caiNiaoCode
     *
     * @mbggenerated
     */
    public String getCainiaocode() {
        return cainiaocode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storageswwwrelas.caiNiaoCode
     *
     * @param cainiaocode the value for storageswwwrelas.caiNiaoCode
     *
     * @mbggenerated
     */
    public void setCainiaocode(String cainiaocode) {
        this.cainiaocode = cainiaocode == null ? null : cainiaocode.trim();
    }
}