package com.haier.stock.eai.QueryTransferFeeFromHBDMToLES;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-04T09:34:05.807+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/sap/OSB/Logistics/ZWD_CBSINT01_NEW", name = "ZWD_CBSINT01_NEW_PT")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ZWDCBSINT01NEWPT {

    @WebMethod(operationName = "ZWD_CBSINT01_NEW", action = "ZWD_CBSINT01_NEW")
    @WebResult(name = "ZWD_CBSINT01_NEW_RESPONSE", targetNamespace = "urn:sap-com:document:sap:rfc:functions:ZWD_CBSINT01_NEW", partName = "parameters")
    public ZWDCBSINT01NEWRESPONSE zwdCBSINT01NEW(
        @WebParam(partName = "parameters", name = "ZWD_CBSINT01_NEW", targetNamespace = "urn:sap-com:document:sap:rfc:functions:ZWD_CBSINT01_NEW")
        ZWDCBSINT01NEW parameters
    );
}
