package com.haier.stock.eai.QueryTransferFeeFromHBDMToLES;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * OSB Service
 *
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-04T09:34:05.849+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "ZWD_CBSINT01_NEW_PT-bindingQSService",
                  wsdlLocation = "file:/D:/administrator/desktop/QueryTransferFeeFromHBDMToLES.wsdl",
                  targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/sap/OSB/Logistics/ZWD_CBSINT01_NEW")
public class ZWDCBSINT01NEWPTBindingQSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.oracle.com/pcbpel/adapter/sap/OSB/Logistics/ZWD_CBSINT01_NEW", "ZWD_CBSINT01_NEW_PT-bindingQSService");
    public final static QName ZWDCBSINT01NEWPTBindingQSPort = new QName("http://xmlns.oracle.com/pcbpel/adapter/sap/OSB/Logistics/ZWD_CBSINT01_NEW", "ZWD_CBSINT01_NEW_PT-bindingQSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/administrator/desktop/QueryTransferFeeFromHBDMToLES.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZWDCBSINT01NEWPTBindingQSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/administrator/desktop/QueryTransferFeeFromHBDMToLES.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZWDCBSINT01NEWPTBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZWDCBSINT01NEWPTBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWDCBSINT01NEWPTBindingQSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ZWDCBSINT01NEWPTBindingQSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZWDCBSINT01NEWPTBindingQSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZWDCBSINT01NEWPTBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ZWDCBSINT01NEWPT
     */
    @WebEndpoint(name = "ZWD_CBSINT01_NEW_PT-bindingQSPort")
    public ZWDCBSINT01NEWPT getZWDCBSINT01NEWPTBindingQSPort() {
        return super.getPort(ZWDCBSINT01NEWPTBindingQSPort, ZWDCBSINT01NEWPT.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWDCBSINT01NEWPT
     */
    @WebEndpoint(name = "ZWD_CBSINT01_NEW_PT-bindingQSPort")
    public ZWDCBSINT01NEWPT getZWDCBSINT01NEWPTBindingQSPort(WebServiceFeature... features) {
        return super.getPort(ZWDCBSINT01NEWPTBindingQSPort, ZWDCBSINT01NEWPT.class, features);
    }

}
