
package com.haier.invoice.model.invoiceapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-12-18T15:59:25.449+08:00
 * Generated source version: 2.7.6
 */

@WebFault(name = "Exception", targetNamespace = "http://v20.api.igs.einv.ruihong.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.haier.invoice.model.invoiceapi.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.haier.invoice.model.invoiceapi.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.haier.invoice.model.invoiceapi.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.haier.invoice.model.invoiceapi.Exception getFaultInfo() {
        return this.exception;
    }
}
