package com.haier.invoice.model.invoiceapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-12-18T15:59:25.589+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://v20.api.igs.einv.ruihong.com/", name = "V20Facade")
@XmlSeeAlso({ObjectFactory.class})
public interface V20Facade {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "ch", targetNamespace = "http://v20.api.igs.einv.ruihong.com/", className = "com.haier.invoice.model.invoiceapi.Ch")
    @WebMethod
    @ResponseWrapper(localName = "chResponse", targetNamespace = "http://v20.api.igs.einv.ruihong.com/", className = "com.haier.invoice.model.invoiceapi.ChResponse")
    public String ch(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "kp", targetNamespace = "http://v20.api.igs.einv.ruihong.com/", className = "com.haier.invoice.model.invoiceapi.Kp")
    @WebMethod
    @ResponseWrapper(localName = "kpResponse", targetNamespace = "http://v20.api.igs.einv.ruihong.com/", className = "com.haier.invoice.model.invoiceapi.KpResponse")
    public String kp(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "ch_async", targetNamespace = "http://v20.api.igs.einv.ruihong.com/", className = "com.haier.invoice.model.invoiceapi.ChAsync")
    @WebMethod(operationName = "ch_async")
    @ResponseWrapper(localName = "ch_asyncResponse", targetNamespace = "http://v20.api.igs.einv.ruihong.com/", className = "com.haier.invoice.model.invoiceapi.ChAsyncResponse")
    public String chAsync(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cx", targetNamespace = "http://v20.api.igs.einv.ruihong.com/", className = "com.haier.invoice.model.invoiceapi.Cx")
    @WebMethod
    @ResponseWrapper(localName = "cxResponse", targetNamespace = "http://v20.api.igs.einv.ruihong.com/", className = "com.haier.invoice.model.invoiceapi.CxResponse")
    public String cx(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "kp_async", targetNamespace = "http://v20.api.igs.einv.ruihong.com/", className = "com.haier.invoice.model.invoiceapi.KpAsync")
    @WebMethod(operationName = "kp_async")
    @ResponseWrapper(localName = "kp_asyncResponse", targetNamespace = "http://v20.api.igs.einv.ruihong.com/", className = "com.haier.invoice.model.invoiceapi.KpAsyncResponse")
    public String kpAsync(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    ) throws Exception_Exception;
}
