package com.haier.stock.eai.finance.transfer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri Aug 16 15:10:40 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebService(targetNamespace = "http://www.example.org/TransferGoodsInfoToEhaierSAP/", name = "TransferGoodsInfoToEhaierSAP")
@XmlSeeAlso({ ObjectFactory.class })
public interface TransferGoodsInfoToEhaierSAP {

    @RequestWrapper(localName = "TransferGoodsInfoToEhaierSAP", targetNamespace = "http://www.example.org/TransferGoodsInfoToEhaierSAP/", className = "org.example.transfergoodsinfotoehaiersap.TransferGoodsInfoToEhaierSAP_Type")
    @ResponseWrapper(localName = "TransferGoodsInfoToEhaierSAPResponse", targetNamespace = "http://www.example.org/TransferGoodsInfoToEhaierSAP/", className = "org.example.transfergoodsinfotoehaiersap.TransferGoodsInfoToEhaierSAPResponse")
    @WebMethod(operationName = "TransferGoodsInfoToEhaierSAP", action = "http://www.example.org/TransferGoodsInfoToEhaierSAP/TransferGoodsInfoToEhaierSAP")
    public void transferGoodsInfoToEhaierSAP(
        @WebParam(name = "T_ZMMS0010", targetNamespace = "") java.util.List<com.haier.stock.eai.finance.transfer.ZMMS0010> tZMMS0010,
        @WebParam(mode = WebParam.Mode.OUT, name = "EX_SUBRC", targetNamespace = "") javax.xml.ws.Holder<Integer> exSUBRC,
        @WebParam(mode = WebParam.Mode.OUT, name = "T_MSG", targetNamespace = "") javax.xml.ws.Holder<java.util.List<com.haier.stock.eai.finance.transfer.ZSDS0002>> tMSG);
}
