/*
 * 
 */

package com.haier.stock.eai.finance.transfer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri Aug 16 15:10:40 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebServiceClient(name = "TransferGoodsInfoToEhaierSAP", wsdlLocation = "file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/TransferGoodsInfoToEhaierSAP.WSDL", targetNamespace = "http://www.example.org/TransferGoodsInfoToEhaierSAP/")
public class TransferGoodsInfoToEhaierSAP_Service extends Service {

    public final static URL   WSDL_LOCATION;
    public final static QName SERVICE                          = new QName(
                                                                   "http://www.example.org/TransferGoodsInfoToEhaierSAP/",
                                                                   "TransferGoodsInfoToEhaierSAP");
    public final static QName TransferGoodsInfoToEhaierSAPSOAP = new QName(
                                                                   "http://www.example.org/TransferGoodsInfoToEhaierSAP/",
                                                                   "TransferGoodsInfoToEhaierSAPSOAP");
    static {
        URL url = null;
        try {
            url = new URL(
                "file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/TransferGoodsInfoToEhaierSAP.WSDL");
        } catch (MalformedURLException e) {
            System.err
                .println("Can not initialize the default wsdl from file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/TransferGoodsInfoToEhaierSAP.WSDL");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public TransferGoodsInfoToEhaierSAP_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TransferGoodsInfoToEhaierSAP_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransferGoodsInfoToEhaierSAP_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns TransferGoodsInfoToEhaierSAP
     */
    @WebEndpoint(name = "TransferGoodsInfoToEhaierSAPSOAP")
    public TransferGoodsInfoToEhaierSAP getTransferGoodsInfoToEhaierSAPSOAP() {
        return super.getPort(TransferGoodsInfoToEhaierSAPSOAP, TransferGoodsInfoToEhaierSAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransferGoodsInfoToEhaierSAP
     */
    @WebEndpoint(name = "TransferGoodsInfoToEhaierSAPSOAP")
    public TransferGoodsInfoToEhaierSAP getTransferGoodsInfoToEhaierSAPSOAP(WebServiceFeature... features) {
        return super.getPort(TransferGoodsInfoToEhaierSAPSOAP, TransferGoodsInfoToEhaierSAP.class,
            features);
    }

}
