interconn:
  project: 3W-CBS
  app: traderate-svc
  monitor:
    url: http://collector.c.haier.net
    enable: false
  trace:
    url: http://collector-trace.c.haier.net
    sample: 0.1 #抽样率，0：关闭，1：全采样，sample<1：部分采样

dubbo:
  registry: zookeeper://127.0.0.1:2181
  port: 20891
  timeout: 10000
  threads: 100
  heartBeats: 10000
#  host: 192.168.1.108

spring:
  mail:
    host: 10.135.1.238
    properties:
      mail:
        smtp:
          auth: false

workorder:
  smssend: \{0} \{1},\{2},联系人:\{3}\{4},\{5},申诉\{6}次咨询\{7}次,\{8}
  mailsend: \{0} \{1},\{2},联系人:\{3}\{4},\{5},\{6},\{7},\{8},申诉\{9}次咨询\{10}次,\{11}
  urlToHP: http://58.56.128.105:8080/rrs/center
  urlToSQM: http://sqm.rrs.com:9898/orderSqmPost/orderUpdateNotify



