package com.haier.stock.eai.finance.postaccounttoehaiersap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 22 09:29:01 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebService(targetNamespace = "http://www.example.org/PostAccountToEhaierSAP/", name = "PostAccountToEhaierSAP")
@XmlSeeAlso({ ObjectFactory.class })
public interface PostAccountToEhaierSAP {

    @WebResult(name = "T_ZMMS0108", targetNamespace = "")
    @RequestWrapper(localName = "PostAccountToEhaierSAP", targetNamespace = "http://www.example.org/PostAccountToEhaierSAP/", className = "org.example.postaccounttoehaiersap.PostAccountToEhaierSAP_Type")
    @ResponseWrapper(localName = "PostAccountToEhaierSAPResponse", targetNamespace = "http://www.example.org/PostAccountToEhaierSAP/", className = "org.example.postaccounttoehaiersap.PostAccountToEhaierSAPResponse")
    @WebMethod(operationName = "PostAccountToEhaierSAP", action = "http://www.example.org/PostAccountToEhaierSAP/PostAccountToEhaierSAP")
    public java.util.List<com.haier.stock.eai.finance.postaccounttoehaiersap.ZMMS0108> postAccountToEhaierSAP(
        @WebParam(name = "T_ZMMS0102", targetNamespace = "") java.util.List<com.haier.stock.eai.finance.postaccounttoehaiersap.ZMMS0102> tZMMS0102);
}
