package com.haier.svc.purchase.purchasefromgvs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 15 13:10:51 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebService(targetNamespace = "http://www.example.org/TransDNInfoFromEHAIERToGVS/", name = "TransDNInfoFromEHAIERToGVS")
@XmlSeeAlso({ ObjectFactory.class })
public interface TransDNInfoFromEHAIERToGVS {

    @RequestWrapper(localName = "TransDNInfoFromEHAIERToGVS", targetNamespace = "http://www.example.org/TransDNInfoFromEHAIERToGVS/", className = "org.example.transdninfofromehaiertogvs.TransDNInfoFromEHAIERToGVS_Type")
    @ResponseWrapper(localName = "TransDNInfoFromEHAIERToGVSResponse", targetNamespace = "http://www.example.org/TransDNInfoFromEHAIERToGVS/", className = "org.example.transdninfofromehaiertogvs.TransDNInfoFromEHAIERToGVSResponse")
    @WebMethod(operationName = "TransDNInfoFromEHAIERToGVS", action = "http://www.example.org/TransDNInfoFromEHAIERToGVS/TransDNInfoFromEHAIERToGVS")
    public void transDNInfoFromEHAIERToGVS(@WebParam(name = "T_ZMMS0003", targetNamespace = "") java.util.List<com.haier.svc.purchase.purchasefromgvs.ZMMS0003> tZMMS0003,
                                           @WebParam(mode = WebParam.Mode.OUT, name = "EX_SUBRC", targetNamespace = "") javax.xml.ws.Holder<java.lang.Integer> exSUBRC,
                                           @WebParam(mode = WebParam.Mode.OUT, name = "T_MSG", targetNamespace = "") javax.xml.ws.Holder<java.util.List<com.haier.svc.purchase.purchasefromgvs.ZSDS0002>> tMSG);
}
