/*
 * 
 */

package com.haier.svc.purchase.purchasefromgvs;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 15 13:10:51 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebServiceClient(name = "TransDNInfoFromEHAIERToGVS", wsdlLocation = "file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/TransDNInfoFromEHAIERToGVS.wsdl", targetNamespace = "http://www.example.org/TransDNInfoFromEHAIERToGVS/")
public class TransDNInfoFromEHAIERToGVS_Service extends Service {

    public final static URL   WSDL_LOCATION;
    public final static QName SERVICE                        = new QName(
                                                                 "http://www.example.org/TransDNInfoFromEHAIERToGVS/",
                                                                 "TransDNInfoFromEHAIERToGVS");
    public final static QName TransDNInfoFromEHAIERToGVSSOAP = new QName(
                                                                 "http://www.example.org/TransDNInfoFromEHAIERToGVS/",
                                                                 "TransDNInfoFromEHAIERToGVSSOAP");
    static {
        URL url = null;
        try {
            url = new URL(
                "file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/TransDNInfoFromEHAIERToGVS.wsdl");
        } catch (MalformedURLException e) {
            System.err
                .println("Can not initialize the default wsdl from file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/TransDNInfoFromEHAIERToGVS.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public TransDNInfoFromEHAIERToGVS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TransDNInfoFromEHAIERToGVS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransDNInfoFromEHAIERToGVS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns TransDNInfoFromEHAIERToGVS
     */
    @WebEndpoint(name = "TransDNInfoFromEHAIERToGVSSOAP")
    public TransDNInfoFromEHAIERToGVS getTransDNInfoFromEHAIERToGVSSOAP() {
        return super.getPort(TransDNInfoFromEHAIERToGVSSOAP, TransDNInfoFromEHAIERToGVS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransDNInfoFromEHAIERToGVS
     */
    @WebEndpoint(name = "TransDNInfoFromEHAIERToGVSSOAP")
    public TransDNInfoFromEHAIERToGVS getTransDNInfoFromEHAIERToGVSSOAP(WebServiceFeature... features) {
        return super.getPort(TransDNInfoFromEHAIERToGVSSOAP, TransDNInfoFromEHAIERToGVS.class,
            features);
    }

}
