
package com.haier.svc.purchase.shop;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InsertDataToHP", targetNamespace = "http://www.example.org/InsertDataToHP/", wsdlLocation = "file:/C:/wsdl/InsertDataToHP.wsdl")
public class InsertDataToHP_Service
    extends Service
{

    private final static URL INSERTDATATOHP_WSDL_LOCATION;
    private final static WebServiceException INSERTDATATOHP_EXCEPTION;
    private final static QName INSERTDATATOHP_QNAME = new QName("http://www.example.org/InsertDataToHP/", "InsertDataToHP");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/wsdl/InsertDataToHP.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSERTDATATOHP_WSDL_LOCATION = url;
        INSERTDATATOHP_EXCEPTION = e;
    }

    public InsertDataToHP_Service() {
        super(__getWsdlLocation(), INSERTDATATOHP_QNAME);
    }

    public InsertDataToHP_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSERTDATATOHP_QNAME, features);
    }

    public InsertDataToHP_Service(URL wsdlLocation) {
        super(wsdlLocation, INSERTDATATOHP_QNAME);
    }

    public InsertDataToHP_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSERTDATATOHP_QNAME, features);
    }

    public InsertDataToHP_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InsertDataToHP_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InsertDataToHP
     */
    @WebEndpoint(name = "InsertDataToHPSOAP")
    public InsertDataToHP getInsertDataToHPSOAP() {
        return super.getPort(new QName("http://www.example.org/InsertDataToHP/", "InsertDataToHPSOAP"), InsertDataToHP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InsertDataToHP
     */
    @WebEndpoint(name = "InsertDataToHPSOAP")
    public InsertDataToHP getInsertDataToHPSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/InsertDataToHP/", "InsertDataToHPSOAP"), InsertDataToHP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSERTDATATOHP_EXCEPTION!= null) {
            throw INSERTDATATOHP_EXCEPTION;
        }
        return INSERTDATATOHP_WSDL_LOCATION;
    }

}
