interconn:
  project: 3W-CBS
  app: vehicle-svc
  monitor:
    url: http://collector.c.haier.net
    enable: false
  trace:
    url: http://collector-trace.c.haier.net
    sample: 0.1 #抽样率，0：关闭，1：全采样，sample<1：部分采样

dubbo:
  registry: 10.138.8.223:2181,10.138.8.224:2181,10.138.8.225:2181
  port: 20895
  timeout: 10000
  threads: 100
  heartBeats: 10000

rrsLocation: http://10.138.26.127:8080/longfei/
materielPath: http://10.138.26.127:8080/longfei/tmallSample			

crmPriceUrl: http://10.135.1.185:7001/EAI/RoutingProxyService/EAI_REST_POST_ServiceRoot?INT_CODE=EAI_INT_1020

wsdlPath: /wsdl

entryOrderUrl: http://10.135.108.147:81/cainiao/getEntryOrder.html