
package com.haier.shop.dao.settleCenter;

import com.haier.common.PagerInfo;
import com.haier.shop.model.OdsTMFXRebatesDateDetail;
import com.haier.shop.model.OdsTMFXRebatesMonthlyDetail;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

/**
 * Code generated by CodeGen
 * Desc: 天猫分销-返利日期明细表Dao类
 * Date: 2018-05-24
 */
@Mapper
public interface OdsTMFXRebatesDateDetailDao {

    /**
     * 添加
     */
    void create(OdsTMFXRebatesDateDetail model);



}
