package com.haier.shop.dao.settleCenter;

import com.haier.shop.model.OdsTMFXCategoryIndustry;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

/**
 * Code generated by CodeGen
 * Desc: 品类品牌产业数据维护表Dao类
 * Date: 2018-05-22
 */
@Mapper
public interface OdsTMFXCategoryIndustryDao {

    /**
     * 添加
     */
    void create(OdsTMFXCategoryIndustry model);

    /**
     * 批量添加
     */
    void creates(List<OdsTMFXCategoryIndustry> model);

    /**
     * 根据网单号查询
     */
    List<OdsTMFXCategoryIndustry> load(@Param("id")String id);

    /**
     * 更新
     */
    void update(OdsTMFXCategoryIndustry model);

    /**
     * 删除
     */
    void delete(@Param("id")String id);

    /**
     * 批量删除
     */
    void deletes(List<String> list);

    /**
     * 查询
     */
    List<OdsTMFXCategoryIndustry> list(OdsTMFXCategoryIndustry model);

    /**
     * 分页查询
     */
    List<Map> paging(Map map);

    /**
     * 总条数查询
     */
    Long count(Map map);

}
