package com.haier.shop.dao.settleCenter;


import com.alibaba.fastjson.JSONObject;
import com.haier.common.PagerInfo;
import com.haier.shop.model.OdsTMFXPointMaintain;
import com.haier.shop.model.SettlementInvoiceData;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

/**
 * Code generated by CodeGen
 * Desc: 佣金结算数据推送队列Dao类
 * Date: 2018-05-28
 */
@Mapper
public interface SettlementInvoiceDataDao {

    /**
     * 添加
     */
    void create(SettlementInvoiceData model);

    /**
     * 批量添加
     */
    void creates(List<SettlementInvoiceData> model);

    /**
     * 根据网单号查询
     */
    List<SettlementInvoiceData> load(@Param("id")String id);

    /**
     * 更新
     */
    void update(SettlementInvoiceData model);

    /**
     * 删除
     */
    void delete(@Param("id")String id);

    /**
     * 批量删除
     */
    void deletes(List<String> list);

    /**
     * 查询
     */
    List<SettlementInvoiceData> list(SettlementInvoiceData model);

    /**
     * 分页查询
     */
    List<SettlementInvoiceData> paging(@Param("param") Map<String, String> param, @Param("page") PagerInfo pagerInfo);

    /**
     * 导入
     * @param list
     */
    void bulkImport(List<SettlementInvoiceData> list);
    /**
     * 导出
     * @param param
     * @return
     */
    List<Map<String,Object>> export(@Param("param") Map<String, String> param);
    /**
     * 总条数查询
     */
    long count(@Param("param") Map<String, String> param);

    /**
     * 根据年月 店铺 品牌 产业 汇总分销明细数据
     * @param year
     * @param month
     * @param type
     * @return
     */
    public List<SettlementInvoiceData> queryDetailToSummary(@Param("year") String year,@Param("month") String month,@Param("type") String type,@Param("source") String source);

    /**
     * 根据生态店年度期间产业品牌查询销量和销额
     * @param settlementInvoiceData
     * @return
     */
    public SettlementInvoiceData querySummaryVolumeOrAmount(SettlementInvoiceData settlementInvoiceData);

    /**
     * 季度年度汇总分销明细
     * @param year
     * @param month
     * @param type
     * @return
     */
    public List<SettlementInvoiceData> queryDetailToSummary2(String year,String month,String type,String source);

    /**
     * 根据网单号和发票状态查询数据
     */
    SettlementInvoiceData getByCOrderSnAndStatusType(@Param("cOrderSn") String cOrderSn,
                                                     @Param("statusType") int statusType);


    /**
     * 根据生态店年度期间产业品牌查询销量和销额
     * @param map
     * @return
     */
    public SettlementInvoiceData querySummaryVolumeOrAmountByDate(@Param("map") Map<String,Object> map);

	public List<String> getSelections();

}
