package com.haier.shop.dao.settleCenter;

import com.haier.shop.model.SettlementLog;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

/**
 * Code generated by CodeGen
 * Desc: 结算日志表Dao类
 * Date: 2018-08-01
 */
@Mapper
public interface SettlementLogDao{

  int create( SettlementLog param);
  int update( SettlementLog param);

  /**
   * 查询是否有计算任务正在执行
   * @return
   */
  int queryLog(String source);

  /**
   * 返回最后执行的计算任务信息
   * @return
   */
  String queryLogInfo(String source);
  
}
