package com.haier.shop.dao.settleCenter;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.haier.common.PagerInfo;
import com.haier.shop.model.SNOdsTMFXRebatesMonthlyDetail;

/**
 * Code generated by CodeGen
 * Desc: 苏宁分销-返利月度明细表Dao类
 * Date: 2018-05-24
 */
@Mapper
public interface SNOdsTMFXRebatesMonthlyDetailDao {

    /**
     * 添加
     */
    void create(SNOdsTMFXRebatesMonthlyDetail model);

    /**
     * 批量添加
     */
    void creates(List<SNOdsTMFXRebatesMonthlyDetail> model);

    /**
     * 主键查询
     */
    List<SNOdsTMFXRebatesMonthlyDetail> load(@Param("id")String id);

    /**
     * 更新
     */
    void update(SNOdsTMFXRebatesMonthlyDetail model);

    /**
     * 删除
     */
    void delete(@Param("id")String id);

    /**
     * 批量删除
     */
    void deletes(List<String> list);

    /**
     * 查询
     */
    List<SNOdsTMFXRebatesMonthlyDetail> list(SNOdsTMFXRebatesMonthlyDetail model);

    List<SNOdsTMFXRebatesMonthlyDetail> paging(@Param("param") SNOdsTMFXRebatesMonthlyDetail param, @Param("page") PagerInfo pagerInfo);
    List<Map<String,Object>> export(@Param("param") SNOdsTMFXRebatesMonthlyDetail param);
    long count(@Param("param") SNOdsTMFXRebatesMonthlyDetail param);

    /**
     * 清空
     */
    void clearHistoryData(@Param("year")String year, @Param("month")String month, @Param("type")String type);

    /**
     * 按产业汇总月度明细
     * @param year
     * @param month
     * @return
     */
    List<SNOdsTMFXRebatesMonthlyDetail> findMonthlySummaryList(String year,String month);

    /**
     * 查询生态店的总金额
     * @param year
     * @param month
     * @param ecologyShop
     * @return
     */
    public BigDecimal findAmountSummary(@Param("year")String year, @Param("month")String month,
                                        @Param("ecologyShop")String ecologyShop, @Param("brand")String brand,
                                                                            @Param("industry")String industry);


    /**
     * 查询季度下各月月度达标信息
     * @param param
     * @return
     */
    List<SNOdsTMFXRebatesMonthlyDetail> queryList(@Param("param") SNOdsTMFXRebatesMonthlyDetail param);

}
