
package com.haier.shop.dao.settleCenter;

import org.apache.ibatis.annotations.Mapper;

import com.haier.shop.model.SNOdsTMFXRebatesDateDetail;

/**
 * Code generated by CodeGen
 * Desc: 苏宁分销-返利日期明细表Dao类
 * Date: 2018-05-24
 */
@Mapper
public interface SNOdsTMFXRebatesDateDetailDao {

    /**
     * 添加
     */
    void create(SNOdsTMFXRebatesDateDetail model);



}
