package com.haier.svc.purchase.selectinfofrommdm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri Jul 19 10:09:45 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebService(targetNamespace = "http://www.example.org/SelectInfoFromMDM/", name = "SelectInfoFromMDM")
@XmlSeeAlso({ ObjectFactory.class })
public interface SelectInfoFromMDM {

    @WebResult(name = "Output", targetNamespace = "")
    @RequestWrapper(localName = "SelectInfoFromMDM_OP", targetNamespace = "http://www.example.org/SelectInfoFromMDM/", className = "org.example.selectinfofrommdm.SelectInfoFromMDMOP")
    @ResponseWrapper(localName = "SelectInfoFromMDM_OPResponse", targetNamespace = "http://www.example.org/SelectInfoFromMDM/", className = "org.example.selectinfofrommdm.SelectInfoFromMDMOPResponse")
    @WebMethod(operationName = "SelectInfoFromMDM_OP", action = "http://www.example.org/SelectInfoFromMDM/SelectInfoFromMDM_OP")
    public com.haier.svc.purchase.selectinfofrommdm.SelectInfoFromMDMOPResponse.Output selectInfoFromMDMOP(@WebParam(name = "in", targetNamespace = "") com.haier.svc.purchase.selectinfofrommdm.InType in);
}
