interconn:
  project: 3W-CBS
  app: stock-data
  monitor:
    url: http://collector.c.haier.net
    enable: false
  trace:
    url: http://collector-trace.c.haier.net
    sample: 0.1 #抽样率，0：关闭，1：全采样，sample<1：部分采样

dubbo:
  registry: 10.162.162.43:2181,10.162.162.44:2181,10.162.162.45:2181
  port: 20885
  timeout: 10000
  threads: 100
  heartBeats: 10000

spring:
  datasource:
    stock:
     url: jdbc:mysql://10.135.26.223:3306/db_stock?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true
     username: s_stock_stock_rw
     password: s_stock_stock_rw
     driver-class-name: com.mysql.jdbc.Driver
     testOnBorrow: true
     testOnReturn: true
     testWhileIdle: true
     validation-query: SELECT 1
     time-between-eviction-runs-millis: 30000
     min-evictable-idle-time-millis: 60000
     max-active: 200
     max-idle: 10

