/*
 * 
 */

package com.haier.stock.eai.transaccountcheckingfromcbstoles;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.2.3
 * Mon Jun 03 16:38:08 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebServiceClient(name = "GetKUCUNInfoFromLESToEHAIER", wsdlLocation = "file:/Users/benio/Documents/projects/wsdl-creator/wsdl-creator/src/main/resources/GetKUCUNInfoFromLESToEHAIER.wsdl", targetNamespace = "http://www.example.org/GetKUCUNInfoFromLESToEHAIER/")
public class GetKUCUNInfoFromLESToEHAIER_Service extends Service {

    public final static URL   WSDL_LOCATION;
    public final static QName SERVICE                         = new QName(
                                                                  "http://www.example.org/GetKUCUNInfoFromLESToEHAIER/",
                                                                  "GetKUCUNInfoFromLESToEHAIER");
    public final static QName GetKUCUNInfoFromLESToEHAIERSOAP = new QName(
                                                                  "http://www.example.org/GetKUCUNInfoFromLESToEHAIER/",
                                                                  "GetKUCUNInfoFromLESToEHAIERSOAP");
    static {
        URL url = null;
        try {
            url = new URL(
                "file:/Users/benio/Documents/projects/wsdl-creator/wsdl-creator/src/main/resources/GetKUCUNInfoFromLESToEHAIER.wsdl");
        } catch (MalformedURLException e) {
            System.err
                .println("Can not initialize the default wsdl from file:/Users/benio/Documents/projects/wsdl-creator/wsdl-creator/src/main/resources/GetKUCUNInfoFromLESToEHAIER.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public GetKUCUNInfoFromLESToEHAIER_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetKUCUNInfoFromLESToEHAIER_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetKUCUNInfoFromLESToEHAIER_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns GetKUCUNInfoFromLESToEHAIER
     */
    @WebEndpoint(name = "GetKUCUNInfoFromLESToEHAIERSOAP")
    public GetKUCUNInfoFromLESToEHAIER getGetKUCUNInfoFromLESToEHAIERSOAP() {
        return super.getPort(GetKUCUNInfoFromLESToEHAIERSOAP, GetKUCUNInfoFromLESToEHAIER.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetKUCUNInfoFromLESToEHAIER
     */
    @WebEndpoint(name = "GetKUCUNInfoFromLESToEHAIERSOAP")
    public GetKUCUNInfoFromLESToEHAIER getGetKUCUNInfoFromLESToEHAIERSOAP(WebServiceFeature... features) {
        return super.getPort(GetKUCUNInfoFromLESToEHAIERSOAP, GetKUCUNInfoFromLESToEHAIER.class,
            features);
    }

}
