package com.haier.stock.eai.transaccountcheckingfromcbstoles;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-12-13T10:20:13.503+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "TransAccountCheckingFromCBSToLES", 
                  wsdlLocation = "file:/G:/Firefox/old/wsdl-creator/wsdl-creator/src/main/resources/TransAccountCheckingFromCBSToLES.wsdl",
                  targetNamespace = "http://www.example.org/TransAccountCheckingFromCBSToLES/") 
public class TransAccountCheckingFromCBSToLES_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/TransAccountCheckingFromCBSToLES/", "TransAccountCheckingFromCBSToLES");
    public final static QName TransAccountCheckingFromCBSToLESSOAP = new QName("http://www.example.org/TransAccountCheckingFromCBSToLES/", "TransAccountCheckingFromCBSToLESSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/G:/Firefox/old/wsdl-creator/wsdl-creator/src/main/resources/TransAccountCheckingFromCBSToLES.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TransAccountCheckingFromCBSToLES_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/G:/Firefox/old/wsdl-creator/wsdl-creator/src/main/resources/TransAccountCheckingFromCBSToLES.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TransAccountCheckingFromCBSToLES_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TransAccountCheckingFromCBSToLES_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransAccountCheckingFromCBSToLES_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns TransAccountCheckingFromCBSToLES
     */
    @WebEndpoint(name = "TransAccountCheckingFromCBSToLESSOAP")
    public TransAccountCheckingFromCBSToLES getTransAccountCheckingFromCBSToLESSOAP() {
        return super.getPort(TransAccountCheckingFromCBSToLESSOAP, TransAccountCheckingFromCBSToLES.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransAccountCheckingFromCBSToLES
     */
    @WebEndpoint(name = "TransAccountCheckingFromCBSToLESSOAP")
    public TransAccountCheckingFromCBSToLES getTransAccountCheckingFromCBSToLESSOAP(WebServiceFeature... features) {
        return super.getPort(TransAccountCheckingFromCBSToLESSOAP, TransAccountCheckingFromCBSToLES.class, features);
    }

}
