interconn:
  project: 3W-CBS
  app: svc-svc
  monitor:
    url: http://collector.c.haier.net
    enable: false
  trace:
    url: http://collector-trace.c.haier.net
    sample: 0.1 #抽样率，0：关闭，1：全采样，sample<1：部分采样
#
#dubbo:
#  protocol:   
#    prot: 20880  
#    name: dubbo  
#  application:   
#    name: provider  
#  registry:  
#    address: zookeeper://127.0.0.1:2181
#  packageName: com.haier.svc
#  threads: 100
#  heartBeats: 10000
#  timeout: 100000
#  retries: 0

dubbo:
  registry: 10.162.162.43:2181,10.162.162.44:2181,10.162.162.45:2181
  port: 20880     #服务提供者服务端口，默认-1
  threads: 100    #服务线程池大小(固定大小)，默认为2
  heartBeats: 10000 #心跳间隔，检查连接是否已断开，默认30000
  serialization: hessian2    #协议序列化方式（可选配置，Dubbo有默认值）;


#spring:
#  datasource:
#    url: jdbc:mysql://10.135.108.143:3306/db_purchase?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF8&useSSL=false
#    url: jdbc:mysql://127.0.0.1:3306/db_purchase?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF8&useSSL=false
#    username: root
#    password: haier123456
#    driver-class-name: com.mysql.jdbc.Driver

spring:
  datasource:
    shop:
     url: jdbc:mysql://10.135.26.223:3306/shop?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true
     username: root
     password: haier123456
     driver-class-name: com.mysql.jdbc.Driver
     testOnBorrow: true
     testOnReturn: true
     testWhileIdle: true
     validation-query: SELECT 1
     time-between-eviction-runs-millis: 30000
     min-evictable-idle-time-millis: 60000
     max-active: 200
     max-idle: 10
    stock:
     url: jdbc:mysql://10.135.26.223:3306/db_stock?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true
     username: root
     password: haier123456
     driver-class-name: com.mysql.jdbc.Driver
     testOnBorrow: true
     testOnReturn: true
     testWhileIdle: true
     validation-query: SELECT 1
     time-between-eviction-runs-millis: 30000
     min-evictable-idle-time-millis: 60000
     max-active: 200
     max-idle: 10
    base:
     url: jdbc:mysql://10.135.26.223:3306/base_system?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true
     username: root
     password: haier123456
     driver-class-name: com.mysql.jdbc.Driver
     testOnBorrow: true
     testOnReturn: true
     testWhileIdle: true
     validation-query: SELECT 1
     time-between-eviction-runs-millis: 30000
     min-evictable-idle-time-millis: 60000
     max-active: 200
     max-idle: 10
    pop:
     url: jdbc:mysql://10.135.26.223:3306/shop?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true
     username: root
     password: haier123456
     driver-class-name: com.mysql.jdbc.Driver
     testOnBorrow: true
     testOnReturn: true
     testWhileIdle: true
     validation-query: SELECT 1
     time-between-eviction-runs-millis: 30000
     min-evictable-idle-time-millis: 60000
     max-active: 200
     max-idle: 10
    finance:
     url: jdbc:mysql://10.135.26.223:3306/shop?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true
     username: root
     password: haier123456
     driver-class-name: com.mysql.jdbc.Driver
     testOnBorrow: true
     testOnReturn: true
     testWhileIdle: true
     validation-query: SELECT 1
     time-between-eviction-runs-millis: 30000
     min-evictable-idle-time-millis: 60000
     max-active: 200
     max-idle: 10
    eis:
     url: jdbc:mysql://localhost:3306/db_eis?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true
     username: root
     password: haier123456
     driver-class-name: com.mysql.jdbc.Driver
     testOnBorrow: true
     testOnReturn: true
     testWhileIdle: true
     validation-query: SELECT 1
     time-between-eviction-runs-millis: 30000
     min-evictable-idle-time-millis: 60000
     max-active: 200
     max-idle: 10

#T+2订单下发CRM
t2Order:
  wsdl:
   url: http://10.138.40.168:8001/EAI/RoutingProxyService/EAI_REST_POST_ServiceRoot?INT_CODE=CRM_INT_OMS_4
  kxPath: 
   priceUrl: http://10.138.40.168:8001/EAI/RoutingProxyService/EAI_REST_POST_ServiceRoot?INT_CODE=EAI_INT_1020
   crm_int_oms_4: http://10.138.40.168:8001/EAI/RoutingProxyService/EAI_SOAP_ServiceRoot?INT_CODE=CRM_INT_OMS_4

#获取wsdl路径
t2OrderResponse:
  location: /wsdl_test

mybatis:
  typeAliasesPackage: com.haier.svc
  mapper-locations: classpath:mapper/*/*Mapper.xml


#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql
#    rowBoundsWithCount: true
