package com.haier.stock.eai.finance.pushreturn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Tue Aug 06 09:58:31 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebService(targetNamespace = "http://www.example.org/PushReturnInfoToGVS/", name = "PushReturnInfoToGVS")
@XmlSeeAlso({ ObjectFactory.class })
public interface PushReturnInfoToGVS {

    @RequestWrapper(localName = "PushReturnInfoToGVS", targetNamespace = "http://www.example.org/PushReturnInfoToGVS/", className = "org.example.pushreturninfotogvs.PushReturnInfoToGVS_Type")
    @ResponseWrapper(localName = "PushReturnInfoToGVSResponse", targetNamespace = "http://www.example.org/PushReturnInfoToGVS/", className = "org.example.pushreturninfotogvs.PushReturnInfoToGVSResponse")
    @WebMethod(operationName = "PushReturnInfoToGVS", action = "http://www.example.org/PushReturnInfoToGVS/PushReturnInfoToGVS")
    public void pushReturnInfoToGVS(
        @WebParam(name = "T_ZSDS0004", targetNamespace = "") java.util.List<ZSDS0004> tZSDS0004,
        @WebParam(mode = WebParam.Mode.OUT, name = "EX_SUBRC", targetNamespace = "") javax.xml.ws.Holder<Integer> exSUBRC,
        @WebParam(mode = WebParam.Mode.OUT, name = "T_MSG", targetNamespace = "") javax.xml.ws.Holder<java.util.List<ZSDS0002>> tMSG);
}
