
package com.haier.svc.api.webService.WwwHpRecords.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CommonServiceImplService", targetNamespace = "http://ServiceImpl.WwwHpRecords.webService.api.svc.haier.com/", wsdlLocation = "http://10.130.50.45:9095/xmlString?wsdl")
public class CommonServiceImplService
    extends Service
{

    private final static URL COMMONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMMONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName COMMONSERVICEIMPLSERVICE_QNAME = new QName("http://ServiceImpl.WwwHpRecords.webService.api.svc.haier.com/", "CommonServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.130.50.45:9095/xmlString?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMMONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        COMMONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CommonServiceImplService() {
        super(__getWsdlLocation(), COMMONSERVICEIMPLSERVICE_QNAME);
    }

    public CommonServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMMONSERVICEIMPLSERVICE_QNAME, features);
    }

    public CommonServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, COMMONSERVICEIMPLSERVICE_QNAME);
    }

    public CommonServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMMONSERVICEIMPLSERVICE_QNAME, features);
    }

    public CommonServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommonServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CommonServiceImpl
     */
    @WebEndpoint(name = "CommonServiceImplPort")
    public CommonServiceImpl getCommonServiceImplPort() {
        return super.getPort(new QName("http://ServiceImpl.WwwHpRecords.webService.api.svc.haier.com/", "CommonServiceImplPort"), CommonServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommonServiceImpl
     */
    @WebEndpoint(name = "CommonServiceImplPort")
    public CommonServiceImpl getCommonServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ServiceImpl.WwwHpRecords.webService.api.svc.haier.com/", "CommonServiceImplPort"), CommonServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMMONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw COMMONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return COMMONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
