interconn:
  project: 3W-CBS
  app: shop-data
  monitor:
    url: http://collector.c.haier.net
    enable: false

dubbo:
  registry: zookeeper://127.0.0.1:2181
  port: 20884
  timeout: 10000
  threads: 100
  heartBeats: 10000
#  host: 192.168.1.108

spring:
  datasource:
    shopread:
      url: jdbc:mysql://10.135.26.223:3306/shop?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true&tinyInt1isBit=false
      username: s_shop_shop_rd
      password: s_shop_shop_rd
      driver-class-name: com.mysql.jdbc.Driver
      testOnBorrow: true
      testOnReturn: true
      testWhileIdle: true
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 60000
      max-active: 200
      max-idle: 10
    shopwrite:
      url: jdbc:mysql://10.135.26.223:3306/shop?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true
      username: s_shop_shop_rw
      password: s_shop_shop_rw
      driver-class-name: com.mysql.jdbc.Driver
      testOnBorrow: true
      testOnReturn: true
      testWhileIdle: true
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 60000
      max-active: 200
      max-idle: 10


workorder:
   smssend: \{0} \{1},\{2},联系人:\{3}\{4},\{5},申诉\{6}次咨询\{7}次,\{8} 
  mailsend: \{0} \{1},\{2},联系人:\{3}\{4},\{5},\{6},\{7},\{8},申诉\{9}次咨询\{10}次,\{11}
  urlToHP: http://58.56.128.105:8080/rrs/center
  urlToSQM: http://sqm.rrs.com:9898/orderSqmPost/orderUpdateNotify