interconn:
  project: 3W-CBS
  app: stock-svc
  monitor:
    url: http://collector.c.haier.net
    enable: false
  trace:
    url: http://collector-trace.c.haier.net
    sample: 0 #抽样率，0：关闭，1：全采样，sample<1：部分采样

dubbo:
  registry: 10.138.8.223:2181,10.138.8.224:2181,10.138.8.225:2181
  port: 20887
  timeout: 10000
  threads: 100
  heartBeats: 10000

wsdlPath: /wsdl
stock_wsdl:
  location: /wsdl

stock.lock.time.minute: 10

url:
  ##orderToLesUrl START
  orderToLesUrl: http://10.135.1.110:7001/EAI/RoutingProxyService/EAI_REST_POST_ServiceRoot?INT_CODE=EAI_INT_1353
  ##orderToLesUrl END

  #取消VOM订单接口 正式地址 start
  vomSynOrderEaiUrl: http://10.135.1.185:7001/EAI/RoutingProxyService/EAI_REST_POST_ServiceRoot?INT_CODE=EAI_INT_1353
  #取消VOM订单接口 正式地址 end

  #更新日日单采购的生产信息 start
  queryFromOmsUrl: http://10.135.1.185:7001/EAI/RoutingProxyService/EAI_SOAP_ServiceRoot?INT_CODE=EAI_INT_1409
  #更新日日单采购的生产信息 end

