package com.haier.invoice.model.queryinvoiceinfofromtaxtoehaier;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-10-30T09:15:18.841+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://www.example.org/QueryInvoiceInfoFromTAXtoEHAIER/", name = "QueryInvoiceInfoFromTAXtoEHAIER")
@XmlSeeAlso({ ObjectFactory.class })
public interface QueryInvoiceInfoFromTAXtoEHAIER {

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "QueryInvoiceInfoFromTAXtoEHAIER", targetNamespace = "http://www.example.org/QueryInvoiceInfoFromTAXtoEHAIER/", className = "org.example.queryinvoiceinfofromtaxtoehaier.QueryInvoiceInfoFromTAXtoEHAIER_Type")
    @WebMethod(operationName = "QueryInvoiceInfoFromTAXtoEHAIER", action = "http://www.example.org/QueryInvoiceInfoFromTAXtoEHAIER/QueryInvoiceInfoFromTAXtoEHAIER")
    @ResponseWrapper(localName = "QueryInvoiceInfoFromTAXtoEHAIERResponse", targetNamespace = "http://www.example.org/QueryInvoiceInfoFromTAXtoEHAIER/", className = "org.example.queryinvoiceinfofromtaxtoehaier.QueryInvoiceInfoFromTAXtoEHAIERResponse")
    public QueryInvoiceInfoFromTAXtoEHAIERResponse.Out queryInvoiceInfoFromTAXtoEHAIER(@WebParam(name = "in", targetNamespace = "") QueryInvoiceInfoFromTAXtoEHAIER_Type.In in);
}
