package com.haier.invoice.model.queryinvoiceinfofromtaxtoehaier;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-10-30T09:15:18.886+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "QueryInvoiceInfoFromTAXtoEHAIER", wsdlLocation = "file:/E:/EHAIER/wsdl-creator/wsdl-creator/src/main/resources/QueryInvoiceInfoFromTAXtoEHAIER.wsdl", targetNamespace = "http://www.example.org/QueryInvoiceInfoFromTAXtoEHAIER/")
public class QueryInvoiceInfoFromTAXtoEHAIER_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE                             = new QName(
                                                                      "http://www.example.org/QueryInvoiceInfoFromTAXtoEHAIER/",
                                                                      "QueryInvoiceInfoFromTAXtoEHAIER");
    public final static QName QueryInvoiceInfoFromTAXtoEHAIERSOAP = new QName(
                                                                      "http://www.example.org/QueryInvoiceInfoFromTAXtoEHAIER/",
                                                                      "QueryInvoiceInfoFromTAXtoEHAIERSOAP");
    static {
        URL url = null;
        try {
            url = new URL(
                "file:/E:/EHAIER/wsdl-creator/wsdl-creator/src/main/resources/QueryInvoiceInfoFromTAXtoEHAIER.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger
                .getLogger(QueryInvoiceInfoFromTAXtoEHAIER_Service.class.getName())
                .log(java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
                    "file:/E:/EHAIER/wsdl-creator/wsdl-creator/src/main/resources/QueryInvoiceInfoFromTAXtoEHAIER.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QueryInvoiceInfoFromTAXtoEHAIER_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryInvoiceInfoFromTAXtoEHAIER_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryInvoiceInfoFromTAXtoEHAIER_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public QueryInvoiceInfoFromTAXtoEHAIER_Service(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public QueryInvoiceInfoFromTAXtoEHAIER_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public QueryInvoiceInfoFromTAXtoEHAIER_Service(URL wsdlLocation, QName serviceName,
                                                   WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns QueryInvoiceInfoFromTAXtoEHAIER
     */
    @WebEndpoint(name = "QueryInvoiceInfoFromTAXtoEHAIERSOAP")
    public QueryInvoiceInfoFromTAXtoEHAIER getQueryInvoiceInfoFromTAXtoEHAIERSOAP() {
        return super.getPort(QueryInvoiceInfoFromTAXtoEHAIERSOAP,
            QueryInvoiceInfoFromTAXtoEHAIER.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryInvoiceInfoFromTAXtoEHAIER
     */
    @WebEndpoint(name = "QueryInvoiceInfoFromTAXtoEHAIERSOAP")
    public QueryInvoiceInfoFromTAXtoEHAIER getQueryInvoiceInfoFromTAXtoEHAIERSOAP(WebServiceFeature... features) {
        return super.getPort(QueryInvoiceInfoFromTAXtoEHAIERSOAP,
            QueryInvoiceInfoFromTAXtoEHAIER.class, features);
    }

}
