/*
 * 
 */

package com.haier.stock.eai.finance.order.query;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.2.3
 * Tue Aug 06 10:07:03 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebServiceClient(name = "QueryOrderHandleInfoFromGVS", wsdlLocation = "file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/QueryOrderHandleInfoFromGVS.wsdl", targetNamespace = "http://www.example.org/QueryOrderHandleInfoFromGVS/")
public class QueryOrderHandleInfoFromGVS_Service extends Service {

    public final static URL   WSDL_LOCATION;
    public final static QName SERVICE                         = new QName(
                                                                  "http://www.example.org/QueryOrderHandleInfoFromGVS/",
                                                                  "QueryOrderHandleInfoFromGVS");
    public final static QName QueryOrderHandleInfoFromGVSSOAP = new QName(
                                                                  "http://www.example.org/QueryOrderHandleInfoFromGVS/",
                                                                  "QueryOrderHandleInfoFromGVSSOAP");
    static {
        URL url = null;
        try {
            url = new URL(
                "file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/QueryOrderHandleInfoFromGVS.wsdl");
        } catch (MalformedURLException e) {
            System.err
                .println("Can not initialize the default wsdl from file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/QueryOrderHandleInfoFromGVS.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public QueryOrderHandleInfoFromGVS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryOrderHandleInfoFromGVS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryOrderHandleInfoFromGVS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns QueryOrderHandleInfoFromGVS
     */
    @WebEndpoint(name = "QueryOrderHandleInfoFromGVSSOAP")
    public QueryOrderHandleInfoFromGVS getQueryOrderHandleInfoFromGVSSOAP() {
        return super.getPort(QueryOrderHandleInfoFromGVSSOAP, QueryOrderHandleInfoFromGVS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryOrderHandleInfoFromGVS
     */
    @WebEndpoint(name = "QueryOrderHandleInfoFromGVSSOAP")
    public QueryOrderHandleInfoFromGVS getQueryOrderHandleInfoFromGVSSOAP(WebServiceFeature... features) {
        return super.getPort(QueryOrderHandleInfoFromGVSSOAP, QueryOrderHandleInfoFromGVS.class,
            features);
    }

}
