package com.haier.svc.purchase.crmmanual;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-08T16:31:37.916+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://www.example.org/InsertWAOrderBillFromEhaierToCRM/", name = "InsertWAOrderBillFromEhaierToCRM")
@XmlSeeAlso({ObjectFactory.class})
public interface InsertWAOrderBillFromEhaierToCRM {

    @RequestWrapper(localName = "InsertWAOrderBillFromEhaierToCRM", targetNamespace = "http://www.example.org/InsertWAOrderBillFromEhaierToCRM/", className = "com.haier.svc.purchase.crmmanual.InsertWAOrderBillFromEhaierToCRM_Type")
    @WebMethod(operationName = "InsertWAOrderBillFromEhaierToCRM", action = "http://www.example.org/InsertWAOrderBillFromEhaierToCRM/InsertWAOrderBillFromEhaierToCRM")
    @ResponseWrapper(localName = "InsertWAOrderBillFromEhaierToCRMResponse", targetNamespace = "http://www.example.org/InsertWAOrderBillFromEhaierToCRM/", className = "com.haier.svc.purchase.crmmanual.InsertWAOrderBillFromEhaierToCRMResponse")
    public void insertWAOrderBillFromEhaierToCRM(
        @WebParam(name = "SysName", targetNamespace = "")
        java.lang.String sysName,
        @WebParam(name = "Master", targetNamespace = "")
        com.haier.svc.purchase.crmmanual.MasterType master,
        @WebParam(name = "Detail", targetNamespace = "")
        java.util.List<com.haier.svc.purchase.crmmanual.DetailType> detail,
        @WebParam(mode = WebParam.Mode.OUT, name = "BillCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> billCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "FLAG", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> flag,
        @WebParam(mode = WebParam.Mode.OUT, name = "MESSAGE", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> message,
        @WebParam(mode = WebParam.Mode.OUT, name = "VBELN", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> vbeln,
        @WebParam(mode = WebParam.Mode.OUT, name = "VBELN_DN", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> vbelnDN
    );
}
