interconn:
  project: 3W-CBS
  app: after-sale
  monitor:
    url: http://collector.c.haier.net
    enable: false
  trace:
    url: http://collector-trace.c.haier.net
    sample: 0.1 #抽样率，0：关闭，1：全采样，sample<1：部分采样

dubbo:
  registry: 10.162.162.43:2181,10.162.162.44:2181,10.162.162.45:2181
  port: 20898
  timeout: 10000
  threads: 100
  heartBeats: 10000

wsdlPath: /wsdl_test

