interconn:
  project: 3W-CBS
  app: after-sale
  monitor:
    url: http://collector.c.haier.net
    enable: false
  trace:
    url: http://collector-trace.c.haier.net
    sample: 0.1 #抽样率，0：关闭，1：全采样，sample<1：部分采样

dubbo:
  registry: zookeeper://127.0.0.1:2181
  port: 20898
  timeout: 10000
  threads: 100
  heartBeats: 10000


wsdlPath: /wsdl_test

stock.lock.time.minute: 10

url:
  ##orderToLesUrl START
  orderToLesUrl: http://10.138.40.168:7100/EAI/service/VOM/CommonGetWayToVOM/CommonGetWayToVOM
  ##orderToLesUrl END

  #取消VOM订单接口 测试地址 start
  vomSynOrderEaiUrl: http://58.56.128.84:9001/EAI/service/VOM/CommonGetWayToVOM/CommonGetWayToVOM
  #取消VOM订单接口 测试地址 end