package com.haier.stock.eai.finance.pushReturnInfoToGVS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2017-06-06T11:31:27.921+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://www.example.org/PushReturnInfoToGVS/", name = "PushReturnInfoToGVS")
@XmlSeeAlso({ObjectFactory.class})
public interface PushReturnInfoToGVS {

    @WebMethod(operationName = "PushReturnInfoToGVS", action = "http://www.example.org/PushReturnInfoToGVS/PushReturnInfoToGVS")
    @RequestWrapper(localName = "PushReturnInfoToGVS", targetNamespace = "http://www.example.org/PushReturnInfoToGVS/", className = "org.example.pushreturninfotogvs.PushReturnInfoToGVS_Type")
    @ResponseWrapper(localName = "PushReturnInfoToGVSResponse", targetNamespace = "http://www.example.org/PushReturnInfoToGVS/", className = "org.example.pushreturninfotogvs.PushReturnInfoToGVSResponse")
    @WebResult(name = "out", targetNamespace = "")
    public OutType pushReturnInfoToGVS(
        @WebParam(name = "in", targetNamespace = "")
            java.util.List<InType> in
    );
}
