
package com.haier.order.wsdl.transordernoticefromehaiertohp;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransSCTailOrder", targetNamespace = "http://xmlns.oracle.com/VOM/TransSCTailOrder/TransSCTailOrder")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransSCTailOrder {


    /**
     * 
     * @param mscode
     * @param input
     * @param message
     */
    @WebMethod(action = "process")
    @RequestWrapper(localName = "process", targetNamespace = "http://xmlns.oracle.com/VOM/TransSCTailOrder/TransSCTailOrder", className = "com.haier.order.wsdl.transordernoticefromehaiertohp.Process")
    @ResponseWrapper(localName = "processResponse", targetNamespace = "http://xmlns.oracle.com/VOM/TransSCTailOrder/TransSCTailOrder", className = "com.haier.order.wsdl.transordernoticefromehaiertohp.ProcessResponse")
    public void process(
        @WebParam(name = "input", targetNamespace = "http://xmlns.oracle.com/VOM/TransSCTailOrder/TransSCTailOrder")
            List<InputType> input,
        @WebParam(name = "MSCODE", targetNamespace = "http://xmlns.oracle.com/VOM/TransSCTailOrder/TransSCTailOrder", mode = WebParam.Mode.OUT)
            Holder<String> mscode,
        @WebParam(name = "MESSAGE", targetNamespace = "http://xmlns.oracle.com/VOM/TransSCTailOrder/TransSCTailOrder", mode = WebParam.Mode.OUT)
            Holder<String> message);

}
