
package com.haier.order.wsdl.transordernoticefromehaiertohp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "transsctailorder_client_ep", targetNamespace = "http://xmlns.oracle.com/VOM/TransSCTailOrder/TransSCTailOrder", wsdlLocation = "file:/C:/Users/gaohaiming/Desktop/HBDM/TransSCTailOrder.wsdl")
public class TranssctailorderClientEp
    extends Service
{

    private final static URL TRANSSCTAILORDERCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException TRANSSCTAILORDERCLIENTEP_EXCEPTION;
    private final static QName TRANSSCTAILORDERCLIENTEP_QNAME = new QName("http://xmlns.oracle.com/VOM/TransSCTailOrder/TransSCTailOrder", "transsctailorder_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/gaohaiming/Desktop/HBDM/TransSCTailOrder.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSSCTAILORDERCLIENTEP_WSDL_LOCATION = url;
        TRANSSCTAILORDERCLIENTEP_EXCEPTION = e;
    }

    public TranssctailorderClientEp() {
        super(__getWsdlLocation(), TRANSSCTAILORDERCLIENTEP_QNAME);
    }

    public TranssctailorderClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSSCTAILORDERCLIENTEP_QNAME, features);
    }

    public TranssctailorderClientEp(URL wsdlLocation) {
        super(wsdlLocation, TRANSSCTAILORDERCLIENTEP_QNAME);
    }

    public TranssctailorderClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSSCTAILORDERCLIENTEP_QNAME, features);
    }

    public TranssctailorderClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TranssctailorderClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TransSCTailOrder
     */
    @WebEndpoint(name = "TransSCTailOrder_pt")
    public TransSCTailOrder getTransSCTailOrderPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/VOM/TransSCTailOrder/TransSCTailOrder", "TransSCTailOrder_pt"), TransSCTailOrder.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransSCTailOrder
     */
    @WebEndpoint(name = "TransSCTailOrder_pt")
    public TransSCTailOrder getTransSCTailOrderPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/VOM/TransSCTailOrder/TransSCTailOrder", "TransSCTailOrder_pt"), TransSCTailOrder.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSSCTAILORDERCLIENTEP_EXCEPTION!= null) {
            throw TRANSSCTAILORDERCLIENTEP_EXCEPTION;
        }
        return TRANSSCTAILORDERCLIENTEP_WSDL_LOCATION;
    }

}
