/*
 * 
 */

package com.haier.stock.eai.finance.rebacktocvs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 15 19:39:46 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebServiceClient(name = "TransReBackInfoFromEHAIERToGVS", wsdlLocation = "file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/TransReBackInfoFromEHAIERToGVS.wsdl", targetNamespace = "http://www.example.org/TransReBackInfoFromEHAIERToGVS/")
public class TransReBackInfoFromEHAIERToGVS_Service extends Service {

    public final static URL   WSDL_LOCATION;
    public final static QName SERVICE                            = new QName(
                                                                     "http://www.example.org/TransReBackInfoFromEHAIERToGVS/",
                                                                     "TransReBackInfoFromEHAIERToGVS");
    public final static QName TransReBackInfoFromEHAIERToGVSSOAP = new QName(
                                                                     "http://www.example.org/TransReBackInfoFromEHAIERToGVS/",
                                                                     "TransReBackInfoFromEHAIERToGVSSOAP");
    static {
        URL url = null;
        try {
            url = new URL(
                "file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/TransReBackInfoFromEHAIERToGVS.wsdl");
        } catch (MalformedURLException e) {
            System.err
                .println("Can not initialize the default wsdl from file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/TransReBackInfoFromEHAIERToGVS.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public TransReBackInfoFromEHAIERToGVS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TransReBackInfoFromEHAIERToGVS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransReBackInfoFromEHAIERToGVS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns TransReBackInfoFromEHAIERToGVS
     */
    @WebEndpoint(name = "TransReBackInfoFromEHAIERToGVSSOAP")
    public TransReBackInfoFromEHAIERToGVS getTransReBackInfoFromEHAIERToGVSSOAP() {
        return super.getPort(TransReBackInfoFromEHAIERToGVSSOAP,
            TransReBackInfoFromEHAIERToGVS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransReBackInfoFromEHAIERToGVS
     */
    @WebEndpoint(name = "TransReBackInfoFromEHAIERToGVSSOAP")
    public TransReBackInfoFromEHAIERToGVS getTransReBackInfoFromEHAIERToGVSSOAP(WebServiceFeature... features) {
        return super.getPort(TransReBackInfoFromEHAIERToGVSSOAP,
            TransReBackInfoFromEHAIERToGVS.class, features);
    }

}
