package com.haier.afterSale.webService.emptyOutSAP;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-03-16T14:42:32.145+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "TransBadGoodsInfoFromGVSToEHAIERSOAPQSService", 
                  wsdlLocation = "file:/D:/java/TransBadGoodsInfoFromGVSToEHAIER.wsdl",
                  targetNamespace = "http://www.example.org/TransBadGoodsInfoFromGVSToEHAIER/") 
public class TransBadGoodsInfoFromGVSToEHAIERSOAPQSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/TransBadGoodsInfoFromGVSToEHAIER/", "TransBadGoodsInfoFromGVSToEHAIERSOAPQSService");
    public final static QName TransBadGoodsInfoFromGVSToEHAIERSOAPQSPort = new QName("http://www.example.org/TransBadGoodsInfoFromGVSToEHAIER/", "TransBadGoodsInfoFromGVSToEHAIERSOAPQSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/java/TransBadGoodsInfoFromGVSToEHAIER.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TransBadGoodsInfoFromGVSToEHAIERSOAPQSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/java/TransBadGoodsInfoFromGVSToEHAIER.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TransBadGoodsInfoFromGVSToEHAIERSOAPQSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TransBadGoodsInfoFromGVSToEHAIERSOAPQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransBadGoodsInfoFromGVSToEHAIERSOAPQSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns TransBadGoodsInfoFromGVSToEHAIER
     */
    @WebEndpoint(name = "TransBadGoodsInfoFromGVSToEHAIERSOAPQSPort")
    public TransBadGoodsInfoFromGVSToEHAIER getTransBadGoodsInfoFromGVSToEHAIERSOAPQSPort() {
        return super.getPort(TransBadGoodsInfoFromGVSToEHAIERSOAPQSPort, TransBadGoodsInfoFromGVSToEHAIER.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransBadGoodsInfoFromGVSToEHAIER
     */
    @WebEndpoint(name = "TransBadGoodsInfoFromGVSToEHAIERSOAPQSPort")
    public TransBadGoodsInfoFromGVSToEHAIER getTransBadGoodsInfoFromGVSToEHAIERSOAPQSPort(WebServiceFeature... features) {
        return super.getPort(TransBadGoodsInfoFromGVSToEHAIERSOAPQSPort, TransBadGoodsInfoFromGVSToEHAIER.class, features);
    }

}
