
package com.haier.afterSale.webService.emptyOutSAP;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-03-16T14:42:31.855+08:00
 * Generated source version: 3.1.12
 * 
 */
public final class TransBadGoodsInfoFromGVSToEHAIER_TransBadGoodsInfoFromGVSToEHAIERSOAPQSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/TransBadGoodsInfoFromGVSToEHAIER/", "TransBadGoodsInfoFromGVSToEHAIERSOAPQSService");

    private TransBadGoodsInfoFromGVSToEHAIER_TransBadGoodsInfoFromGVSToEHAIERSOAPQSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TransBadGoodsInfoFromGVSToEHAIERSOAPQSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TransBadGoodsInfoFromGVSToEHAIERSOAPQSService ss = new TransBadGoodsInfoFromGVSToEHAIERSOAPQSService(wsdlURL, SERVICE_NAME);
        TransBadGoodsInfoFromGVSToEHAIER port = ss.getTransBadGoodsInfoFromGVSToEHAIERSOAPQSPort();  
        
        {
        System.out.println("Invoking transBadGoodsInfoFromGVSToEHAIER...");
        java.lang.String _transBadGoodsInfoFromGVSToEHAIER_sysname = "";
        java.util.List<com.haier.afterSale.webService.emptyOutSAP.ZMMINBOUND010IN> _transBadGoodsInfoFromGVSToEHAIER_tZMMS0008 = null;
        com.haier.afterSale.webService.emptyOutSAP.OutType _transBadGoodsInfoFromGVSToEHAIER__return = port.transBadGoodsInfoFromGVSToEHAIER(_transBadGoodsInfoFromGVSToEHAIER_sysname, _transBadGoodsInfoFromGVSToEHAIER_tZMMS0008);
        System.out.println("transBadGoodsInfoFromGVSToEHAIER.result=" + _transBadGoodsInfoFromGVSToEHAIER__return);


        }

        System.exit(0);
    }

}
