package com.haier.stock.eai.queryProdDateFromEDW;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-03-24T17:06:04.609+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "QueryProOrderAndSaleOrderFromEDW", 
                  wsdlLocation = "file:/Users/YanZhao/work/workspace/wsdl-creator/wsdl-creator/src/main/resources/QueryProOrderAndSaleOrderFromEDW.wsdl",
                  targetNamespace = "http://www.example.org/QueryProOrderAndSaleOrderFromEDW/") 
public class QueryProOrderAndSaleOrderFromEDW_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/QueryProOrderAndSaleOrderFromEDW/", "QueryProOrderAndSaleOrderFromEDW");
    public final static QName QueryProOrderAndSaleOrderFromEDWSOAP = new QName("http://www.example.org/QueryProOrderAndSaleOrderFromEDW/", "QueryProOrderAndSaleOrderFromEDWSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/YanZhao/work/workspace/wsdl-creator/wsdl-creator/src/main/resources/QueryProOrderAndSaleOrderFromEDW.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueryProOrderAndSaleOrderFromEDW_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/YanZhao/work/workspace/wsdl-creator/wsdl-creator/src/main/resources/QueryProOrderAndSaleOrderFromEDW.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QueryProOrderAndSaleOrderFromEDW_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryProOrderAndSaleOrderFromEDW_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryProOrderAndSaleOrderFromEDW_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns QueryProOrderAndSaleOrderFromEDW
     */
    @WebEndpoint(name = "QueryProOrderAndSaleOrderFromEDWSOAP")
    public QueryProOrderAndSaleOrderFromEDW getQueryProOrderAndSaleOrderFromEDWSOAP() {
        return super.getPort(QueryProOrderAndSaleOrderFromEDWSOAP, QueryProOrderAndSaleOrderFromEDW.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryProOrderAndSaleOrderFromEDW
     */
    @WebEndpoint(name = "QueryProOrderAndSaleOrderFromEDWSOAP")
    public QueryProOrderAndSaleOrderFromEDW getQueryProOrderAndSaleOrderFromEDWSOAP(WebServiceFeature... features) {
        return super.getPort(QueryProOrderAndSaleOrderFromEDWSOAP, QueryProOrderAndSaleOrderFromEDW.class, features);
    }

}
