package com.haier.svc.purchase.queryDNFrom;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * OSB Service
 *
 * This class was generated by Apache CXF 3.1.12
 * 2018-02-01T19:02:54.368+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "QueryDNFromLEStoAPP", 
                  wsdlLocation = "file:/D:/java/QueryDNFromLEStoAPP.wsdl",
                  targetNamespace = "http://www.example.org/QueryDNFromLEStoAPP/") 
public class QueryDNFromLEStoAPP_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/QueryDNFromLEStoAPP/", "QueryDNFromLEStoAPP");
    public final static QName QueryDNFromLEStoAPPSOAP = new QName("http://www.example.org/QueryDNFromLEStoAPP/", "QueryDNFromLEStoAPPSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/java/QueryDNFromLEStoAPP.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueryDNFromLEStoAPP_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/java/QueryDNFromLEStoAPP.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QueryDNFromLEStoAPP_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryDNFromLEStoAPP_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryDNFromLEStoAPP_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns QueryDNFromLEStoAPP
     */
    @WebEndpoint(name = "QueryDNFromLEStoAPPSOAP")
    public QueryDNFromLEStoAPP getQueryDNFromLEStoAPPSOAP() {
        return super.getPort(QueryDNFromLEStoAPPSOAP, QueryDNFromLEStoAPP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryDNFromLEStoAPP
     */
    @WebEndpoint(name = "QueryDNFromLEStoAPPSOAP")
    public QueryDNFromLEStoAPP getQueryDNFromLEStoAPPSOAP(WebServiceFeature... features) {
        return super.getPort(QueryDNFromLEStoAPPSOAP, QueryDNFromLEStoAPP.class, features);
    }

}
