
package com.haier.svc.purchase.queryDNFrom;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-02-01T19:02:54.157+08:00
 * Generated source version: 3.1.12
 * 
 */
public final class QueryDNFromLEStoAPP_QueryDNFromLEStoAPPSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/QueryDNFromLEStoAPP/", "QueryDNFromLEStoAPP");

    private QueryDNFromLEStoAPP_QueryDNFromLEStoAPPSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = QueryDNFromLEStoAPP_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        QueryDNFromLEStoAPP_Service ss = new QueryDNFromLEStoAPP_Service(wsdlURL, SERVICE_NAME);
        QueryDNFromLEStoAPP port = ss.getQueryDNFromLEStoAPPSOAP();  
        
        {
        System.out.println("Invoking queryDNFromLEStoAPP...");
        java.lang.String _queryDNFromLEStoAPP_callcode = "";
        java.lang.String _queryDNFromLEStoAPP_source = "";
        java.util.List<com.haier.svc.purchase.queryDNFrom.ZINTWXWTLOG> _queryDNFromLEStoAPP_input = null;
        javax.xml.ws.Holder<java.lang.String> _queryDNFromLEStoAPP_flag = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _queryDNFromLEStoAPP_message = new javax.xml.ws.Holder<java.lang.String>();
        port.queryDNFromLEStoAPP(_queryDNFromLEStoAPP_callcode, _queryDNFromLEStoAPP_source, _queryDNFromLEStoAPP_input, _queryDNFromLEStoAPP_flag, _queryDNFromLEStoAPP_message);

        System.out.println("queryDNFromLEStoAPP._queryDNFromLEStoAPP_flag=" + _queryDNFromLEStoAPP_flag.value);
        System.out.println("queryDNFromLEStoAPP._queryDNFromLEStoAPP_message=" + _queryDNFromLEStoAPP_message.value);

        }

        System.exit(0);
    }

}
