package com.haier.svc.purchase.querywaorderbillfromihs;

import java.util.Date;
import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "QueryWAOrderBillFromIHS", targetNamespace = "http://www.example.org/QueryWAOrderBillFromIHS/")
@XmlSeeAlso({ ObjectFactory.class })
public interface QueryWAOrderBillFromIHS {

    /**
     * 
     * @param sysName
     * @return
     *     returns java.util.List<org.example.querywaorderbillfromihs.VWWAOrderBillYTJOutput>
     */
    @WebMethod(operationName = "QueryWAOrderBillFromIHS", action = "http://www.example.org/QueryWAOrderBillFromIHS/QueryWAOrderBillFromIHS")
    @WebResult(name = "VW_WAOrderBillYTJOutput", targetNamespace = "")
    @RequestWrapper(localName = "QueryWAOrderBillFromIHS", targetNamespace = "http://www.example.org/QueryWAOrderBillFromIHS/", className = "org.example.querywaorderbillfromihs.QueryWAOrderBillFromIHS_Type")
    @ResponseWrapper(localName = "QueryWAOrderBillFromIHSResponse", targetNamespace = "http://www.example.org/QueryWAOrderBillFromIHS/", className = "org.example.querywaorderbillfromihs.QueryWAOrderBillFromIHSResponse")
    public List<VWWAOrderBillYTJOutput> queryWAOrderBillFromIHS(@WebParam(name = "SysName", targetNamespace = "") String SysName,@WebParam(name = "BeginDate", targetNamespace = "") Date BeginDate,@WebParam(name = "EndDate", targetNamespace = "") Date EndDate,@WebParam(name = "BillCode", targetNamespace = "") String BillCode);

}
