package com.haier.svc.purchase.querywaorderbillfromihs;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "QueryWAOrderBillFromIHS", targetNamespace = "http://www.example.org/QueryWAOrderBillFromIHS/", wsdlLocation = "file:/C:/Users/Administrator/Desktop/ws/QueryWAOrderBillFromIHS.wsdl")
public class QueryWAOrderBillFromIHS_Service extends Service {

    private final static URL    QUERYWAORDERBILLFROMIHS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(QueryWAOrderBillFromIHS_Service.class
                                           .getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = QueryWAOrderBillFromIHS_Service.class.getResource(".");
            url = new URL(baseUrl,
                "file:/C:/Users/Administrator/Desktop/ws/QueryWAOrderBillFromIHS.wsdl");
        } catch (MalformedURLException e) {
            logger
                .warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/Administrator/Desktop/ws/QueryWAOrderBillFromIHS.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        QUERYWAORDERBILLFROMIHS_WSDL_LOCATION = url;
    }

    public QueryWAOrderBillFromIHS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryWAOrderBillFromIHS_Service() {
        super(QUERYWAORDERBILLFROMIHS_WSDL_LOCATION, new QName(
            "http://www.example.org/QueryWAOrderBillFromIHS/", "QueryWAOrderBillFromIHS"));
    }

    public QueryWAOrderBillFromIHS_Service(URL wsdlLocation) {
        super(wsdlLocation, new QName("http://www.example.org/QueryWAOrderBillFromIHS/",
            "QueryWAOrderBillFromIHS"));
    }

    /**
     * 
     * @return
     *     returns QueryWAOrderBillFromIHS
     */
    @WebEndpoint(name = "QueryWAOrderBillFromIHSSOAP")
    public QueryWAOrderBillFromIHS getQueryWAOrderBillFromIHSSOAP() {
        return super.getPort(new QName("http://www.example.org/QueryWAOrderBillFromIHS/",
            "QueryWAOrderBillFromIHSSOAP"), QueryWAOrderBillFromIHS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryWAOrderBillFromIHS
     */
    @WebEndpoint(name = "QueryWAOrderBillFromIHSSOAP")
    public QueryWAOrderBillFromIHS getQueryWAOrderBillFromIHSSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/QueryWAOrderBillFromIHS/",
            "QueryWAOrderBillFromIHSSOAP"), QueryWAOrderBillFromIHS.class, features);
    }

}
