/*
 * 
 */

package com.haier.stock.eai.finance.pushprosale.query;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 08 14:09:20 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebServiceClient(name = "QueryProSaleHandleFromEhaierSAP", wsdlLocation = "file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/QueryProSaleHandleFromEhaierSAP.wsdl", targetNamespace = "http://www.example.org/QueryProSaleHandleFromEhaierSAP/")
public class QueryProSaleHandleFromEhaierSAP_Service extends Service {

    public final static URL   WSDL_LOCATION;
    public final static QName SERVICE                             = new QName(
                                                                      "http://www.example.org/QueryProSaleHandleFromEhaierSAP/",
                                                                      "QueryProSaleHandleFromEhaierSAP");
    public final static QName QueryProSaleHandleFromEhaierSAPSOAP = new QName(
                                                                      "http://www.example.org/QueryProSaleHandleFromEhaierSAP/",
                                                                      "QueryProSaleHandleFromEhaierSAPSOAP");
    static {
        URL url = null;
        try {
            url = new URL(
                "file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/QueryProSaleHandleFromEhaierSAP.wsdl");
        } catch (MalformedURLException e) {
            System.err
                .println("Can not initialize the default wsdl from file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/QueryProSaleHandleFromEhaierSAP.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public QueryProSaleHandleFromEhaierSAP_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryProSaleHandleFromEhaierSAP_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryProSaleHandleFromEhaierSAP_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns QueryProSaleHandleFromEhaierSAP
     */
    @WebEndpoint(name = "QueryProSaleHandleFromEhaierSAPSOAP")
    public QueryProSaleHandleFromEhaierSAP getQueryProSaleHandleFromEhaierSAPSOAP() {
        return super.getPort(QueryProSaleHandleFromEhaierSAPSOAP,
            QueryProSaleHandleFromEhaierSAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryProSaleHandleFromEhaierSAP
     */
    @WebEndpoint(name = "QueryProSaleHandleFromEhaierSAPSOAP")
    public QueryProSaleHandleFromEhaierSAP getQueryProSaleHandleFromEhaierSAPSOAP(WebServiceFeature... features) {
        return super.getPort(QueryProSaleHandleFromEhaierSAPSOAP,
            QueryProSaleHandleFromEhaierSAP.class, features);
    }

}
