package com.haier.stock.eai.finance.pushprosale.query;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 08 14:09:20 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebService(targetNamespace = "http://www.example.org/QueryProSaleHandleFromEhaierSAP/", name = "QueryProSaleHandleFromEhaierSAP")
@XmlSeeAlso({ ObjectFactory.class })
public interface QueryProSaleHandleFromEhaierSAP {

    @WebResult(name = "T_ZSDS0003", targetNamespace = "")
    @RequestWrapper(localName = "QueryProSaleHandleFromEhaierSAP", targetNamespace = "http://www.example.org/QueryProSaleHandleFromEhaierSAP/", className = "org.example.queryprosalehandlefromehaiersap.QueryProSaleHandleFromEhaierSAP_Type")
    @ResponseWrapper(localName = "QueryProSaleHandleFromEhaierSAPResponse", targetNamespace = "http://www.example.org/QueryProSaleHandleFromEhaierSAP/", className = "org.example.queryprosalehandlefromehaiersap.QueryProSaleHandleFromEhaierSAPResponse")
    @WebMethod(operationName = "QueryProSaleHandleFromEhaierSAP", action = "http://www.example.org/QueryProSaleHandleFromEhaierSAP/QueryProSaleHandleFromEhaierSAP")
    public java.util.List<com.haier.stock.eai.finance.pushprosale.query.ZSDS0003> queryProSaleHandleFromEhaierSAP(
        @WebParam(name = "T_SELCOND", targetNamespace = "") java.util.List<com.haier.stock.eai.finance.pushprosale.query.ZSDS0006> tSELCOND);
}
