package com.haier.vehicle.wsdl.les;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * OSB Service
 *
 * This class was generated by Apache CXF 3.1.12
 * 2017-10-19T16:08:45.656+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "ZHIFA_CUSTOMER_PT-bindingQSService", 
                  wsdlLocation = "file:/D:/java/TransWuLiuInfoFromLESToCBSXIN.WSDL",
                  targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/sap/OSB/Logistics/ZHIFA_CUSTOMER") 
public class ZHIFACUSTOMERPTBindingQSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.oracle.com/pcbpel/adapter/sap/OSB/Logistics/ZHIFA_CUSTOMER", "ZHIFA_CUSTOMER_PT-bindingQSService");
    public final static QName ZHIFACUSTOMERPTBindingQSPort = new QName("http://xmlns.oracle.com/pcbpel/adapter/sap/OSB/Logistics/ZHIFA_CUSTOMER", "ZHIFA_CUSTOMER_PT-bindingQSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/java/TransWuLiuInfoFromLESToCBSXIN.WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZHIFACUSTOMERPTBindingQSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/java/TransWuLiuInfoFromLESToCBSXIN.WSDL");
        }
        WSDL_LOCATION = url;
    }

    public ZHIFACUSTOMERPTBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZHIFACUSTOMERPTBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZHIFACUSTOMERPTBindingQSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns ZHIFACUSTOMERPT
     */
    @WebEndpoint(name = "ZHIFA_CUSTOMER_PT-bindingQSPort")
    public ZHIFACUSTOMERPT getZHIFACUSTOMERPTBindingQSPort() {
        return super.getPort(ZHIFACUSTOMERPTBindingQSPort, ZHIFACUSTOMERPT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZHIFACUSTOMERPT
     */
    @WebEndpoint(name = "ZHIFA_CUSTOMER_PT-bindingQSPort")
    public ZHIFACUSTOMERPT getZHIFACUSTOMERPTBindingQSPort(WebServiceFeature... features) {
        return super.getPort(ZHIFACUSTOMERPTBindingQSPort, ZHIFACUSTOMERPT.class, features);
    }

}
