package com.haier.vehicle.wsdl.les;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-10-19T16:08:45.650+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/sap/OSB/Logistics/ZHIFA_CUSTOMER", name = "ZHIFA_CUSTOMER_PT")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ZHIFACUSTOMERPT {

    @WebResult(name = "ZHIFA_CUSTOMER_RESPONSE", targetNamespace = "urn:sap-com:document:sap:rfc:functions:ZHIFA_CUSTOMER", partName = "parameters")
    @WebMethod(operationName = "ZHIFA_CUSTOMER", action = "ZHIFA_CUSTOMER")
    public ZHIFACUSTOMERRESPONSE zhifaCUSTOMER(
        @WebParam(partName = "parameters", name = "ZHIFA_CUSTOMER", targetNamespace = "urn:sap-com:document:sap:rfc:functions:ZHIFA_CUSTOMER")
        ZHIFACUSTOMER parameters
    );
}
