
package com.haier.vehicle.wsdl.les;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-10-19T16:08:45.612+08:00
 * Generated source version: 3.1.12
 * 
 */
public final class ZHIFACUSTOMERPT_ZHIFACUSTOMERPTBindingQSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://xmlns.oracle.com/pcbpel/adapter/sap/OSB/Logistics/ZHIFA_CUSTOMER", "ZHIFA_CUSTOMER_PT-bindingQSService");

    private ZHIFACUSTOMERPT_ZHIFACUSTOMERPTBindingQSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ZHIFACUSTOMERPTBindingQSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ZHIFACUSTOMERPTBindingQSService ss = new ZHIFACUSTOMERPTBindingQSService(wsdlURL, SERVICE_NAME);
        ZHIFACUSTOMERPT port = ss.getZHIFACUSTOMERPTBindingQSPort();  
        
        {
        System.out.println("Invoking zhifaCUSTOMER...");
        com.haier.vehicle.wsdl.les.ZHIFACUSTOMER _zhifaCUSTOMER_parameters = null;
        com.haier.vehicle.wsdl.les.ZHIFACUSTOMERRESPONSE _zhifaCUSTOMER__return = port.zhifaCUSTOMER(_zhifaCUSTOMER_parameters);
        System.out.println("zhifaCUSTOMER.result=" + _zhifaCUSTOMER__return);


        }

        System.exit(0);
    }

}
