package com.haier.vehicle.wsdl.sendorder;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * OSB Service
 *
 * This class was generated by Apache CXF 3.1.12
 * 2017-12-12T16:52:18.875+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "insertorderbill_zktooms_client_ep", 
                  wsdlLocation = "file:/D:/java/InsertOrderBill_ZKToOMS.wsdl",
                  targetNamespace = "http://xmlns.oracle.com/Application/InsertOrderBill_ZKToOMS/InsertOrderBill_ZKToOMS") 
public class InsertorderbillZktoomsClientEp extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.oracle.com/Application/InsertOrderBill_ZKToOMS/InsertOrderBill_ZKToOMS", "insertorderbill_zktooms_client_ep");
    public final static QName InsertOrderBillZKToOMSPt = new QName("http://xmlns.oracle.com/Application/InsertOrderBill_ZKToOMS/InsertOrderBill_ZKToOMS", "InsertOrderBill_ZKToOMS_pt");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/java/InsertOrderBill_ZKToOMS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InsertorderbillZktoomsClientEp.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/java/InsertOrderBill_ZKToOMS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InsertorderbillZktoomsClientEp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InsertorderbillZktoomsClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InsertorderbillZktoomsClientEp() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns InsertOrderBillZKToOMS
     */
    @WebEndpoint(name = "InsertOrderBill_ZKToOMS_pt")
    public InsertOrderBillZKToOMS getInsertOrderBillZKToOMSPt() {
        return super.getPort(InsertOrderBillZKToOMSPt, InsertOrderBillZKToOMS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InsertOrderBillZKToOMS
     */
    @WebEndpoint(name = "InsertOrderBill_ZKToOMS_pt")
    public InsertOrderBillZKToOMS getInsertOrderBillZKToOMSPt(WebServiceFeature... features) {
        return super.getPort(InsertOrderBillZKToOMSPt, InsertOrderBillZKToOMS.class, features);
    }

}
