package com.haier.vehicle.wsdl.sendorder;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-12-12T16:52:18.857+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/Application/InsertOrderBill_ZKToOMS/InsertOrderBill_ZKToOMS", name = "InsertOrderBill_ZKToOMS")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface InsertOrderBillZKToOMS {

    @WebMethod(action = "process")
    @WebResult(name = "InsertOrderBill_OMS2ProcessResponse", targetNamespace = "http://xmlns.oracle.com/Application/InsertOrderBill_ZKToOMS/InsertOrderBill_ZKToOMS", partName = "payload")
    public InsertOrderBillOMS2ProcessResponse process(
        @WebParam(partName = "payload", name = "InsertOrderBill_OMS2ProcessRequest", targetNamespace = "http://xmlns.oracle.com/Application/InsertOrderBill_ZKToOMS/InsertOrderBill_ZKToOMS")
        InsertOrderBillOMS2ProcessRequest payload
    ) throws RemoteExceptionMessage;
}
