
package com.haier.vehicle.wsdl.sendorder;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-12-12T16:52:18.830+08:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "InsertOrderBill_OMS2ProcessResponse", targetNamespace = "http://xmlns.oracle.com/Application/InsertOrderBill_ZKToOMS/InsertOrderBill_ZKToOMS")
public class RemoteExceptionMessage extends Exception {
    
    private com.haier.vehicle.wsdl.sendorder.InsertOrderBillOMS2ProcessResponse insertOrderBillOMS2ProcessResponse;

    public RemoteExceptionMessage() {
        super();
    }
    
    public RemoteExceptionMessage(String message) {
        super(message);
    }
    
    public RemoteExceptionMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public RemoteExceptionMessage(String message, com.haier.vehicle.wsdl.sendorder.InsertOrderBillOMS2ProcessResponse insertOrderBillOMS2ProcessResponse) {
        super(message);
        this.insertOrderBillOMS2ProcessResponse = insertOrderBillOMS2ProcessResponse;
    }

    public RemoteExceptionMessage(String message, com.haier.vehicle.wsdl.sendorder.InsertOrderBillOMS2ProcessResponse insertOrderBillOMS2ProcessResponse, Throwable cause) {
        super(message, cause);
        this.insertOrderBillOMS2ProcessResponse = insertOrderBillOMS2ProcessResponse;
    }

    public com.haier.vehicle.wsdl.sendorder.InsertOrderBillOMS2ProcessResponse getFaultInfo() {
        return this.insertOrderBillOMS2ProcessResponse;
    }
}
