package com.haier.svc.purchase.cancelorderfromehaiertooms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-13T14:36:56.846+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://www.example.org/CancelOrderFromEHaierToOMS/", name = "CancelOrderFromEHaierToOMS")
@XmlSeeAlso({ObjectFactory.class})
public interface CancelOrderFromEHaierToOMS {

    @WebMethod(operationName = "CancelOrderFromEHaierToOMS", action = "http://www.example.org/CancelOrderFromEHaierToOMS/CancelOrderFromEHaierToOMS")
    @RequestWrapper(localName = "CancelOrderFromEHaierToOMS", targetNamespace = "http://www.example.org/CancelOrderFromEHaierToOMS/", className = "com.haier.svc.purchase.cancelorderfromehaiertooms.CancelOrderFromEHaierToOMS_Type")
    @ResponseWrapper(localName = "CancelOrderFromEHaierToOMSResponse", targetNamespace = "http://www.example.org/CancelOrderFromEHaierToOMS/", className = "com.haier.svc.purchase.cancelorderfromehaiertooms.CancelOrderFromEHaierToOMSResponse")
    @WebResult(name = "requestDataReturn", targetNamespace = "")
    public com.haier.svc.purchase.cancelorderfromehaiertooms.ResponseData cancelOrderFromEHaierToOMS(
        @WebParam(name = "RequestData", targetNamespace = "")
        com.haier.svc.purchase.cancelorderfromehaiertooms.RequestData requestData
    );
}
