package com.haier.svc.purchase.cancelorderfromehaiertooms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-05T14:23:29.036+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "CancelOrderFromEHaierToOMS", 
                  wsdlLocation = "file:/C:/Users/admin/Desktop/ws/CancelOrderFromEHaierToOMS.wsdl",
                  targetNamespace = "http://www.example.org/CancelOrderFromEHaierToOMS/") 
public class CancelOrderFromEHaierToOMS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/CancelOrderFromEHaierToOMS/", "CancelOrderFromEHaierToOMS");
    public final static QName CancelOrderFromEHaierToOMSSOAP = new QName("http://www.example.org/CancelOrderFromEHaierToOMS/", "CancelOrderFromEHaierToOMSSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/admin/Desktop/ws/CancelOrderFromEHaierToOMS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CancelOrderFromEHaierToOMS_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/admin/Desktop/ws/CancelOrderFromEHaierToOMS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CancelOrderFromEHaierToOMS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CancelOrderFromEHaierToOMS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CancelOrderFromEHaierToOMS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CancelOrderFromEHaierToOMS
     */
    @WebEndpoint(name = "CancelOrderFromEHaierToOMSSOAP")
    public CancelOrderFromEHaierToOMS getCancelOrderFromEHaierToOMSSOAP() {
        return super.getPort(CancelOrderFromEHaierToOMSSOAP, CancelOrderFromEHaierToOMS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CancelOrderFromEHaierToOMS
     */
    @WebEndpoint(name = "CancelOrderFromEHaierToOMSSOAP")
    public CancelOrderFromEHaierToOMS getCancelOrderFromEHaierToOMSSOAP(WebServiceFeature... features) {
        return super.getPort(CancelOrderFromEHaierToOMSSOAP, CancelOrderFromEHaierToOMS.class, features);
    }

}
