package com.haier.svc.purchase.cancelorderfromehaiertooms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-05T14:23:28.987+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://www.example.org/CancelOrderFromEHaierToOMS/", name = "CancelOrderFromEHaierToOMS")
@XmlSeeAlso({ObjectFactory.class})
public interface CancelOrderFromEHaierToOMS {

    @WebResult(name = "requestDataReturn", targetNamespace = "")
    @RequestWrapper(localName = "CancelOrderFromEHaierToOMS", targetNamespace = "http://www.example.org/CancelOrderFromEHaierToOMS/", className = "com.haier.svc.purchase.cancelorderfromehaiertooms.CancelOrderFromEHaierToOMS_Type")
    @WebMethod(operationName = "CancelOrderFromEHaierToOMS", action = "http://www.example.org/CancelOrderFromEHaierToOMS/CancelOrderFromEHaierToOMS")
    @ResponseWrapper(localName = "CancelOrderFromEHaierToOMSResponse", targetNamespace = "http://www.example.org/CancelOrderFromEHaierToOMS/", className = "com.haier.svc.purchase.cancelorderfromehaiertooms.CancelOrderFromEHaierToOMSResponse")
    public ResponseData cancelOrderFromEHaierToOMS(
        @WebParam(name = "RequestData", targetNamespace = "")
        RequestData requestData
    );
}
