package com.haier.stock.eai.finance.transBadGoodsInfoFromGvsToEhaier;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-04-13T10:32:08.999+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://www.example.org/TransBadGoodsInfoFromGVSToEHAIER/", name = "TransBadGoodsInfoFromGVSToEHAIER")
@XmlSeeAlso({ ObjectFactory.class })
public interface TransBadGoodsInfoFromGVSToEHAIER {

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "TransBadGoodsInfoFromGVSToEHAIER", targetNamespace = "http://www.example.org/TransBadGoodsInfoFromGVSToEHAIER/", className = "org.example.transbadgoodsinfofromgvstoehaier.TransBadGoodsInfoFromGVSToEHAIER_Type")
    @WebMethod(operationName = "TransBadGoodsInfoFromGVSToEHAIER", action = "http://www.example.org/TransBadGoodsInfoFromGVSToEHAIER/TransBadGoodsInfoFromGVSToEHAIER")
    @ResponseWrapper(localName = "TransBadGoodsInfoFromGVSToEHAIERResponse", targetNamespace = "http://www.example.org/TransBadGoodsInfoFromGVSToEHAIER/", className = "org.example.transbadgoodsinfofromgvstoehaier.TransBadGoodsInfoFromGVSToEHAIERResponse")
    public OutType transBadGoodsInfoFromGVSToEHAIER(
        @WebParam(name = "SYSNAME", targetNamespace = "") String sysname,
        @WebParam(name = "T_ZMMS0008", targetNamespace = "") java.util.List<ZMMINBOUND010IN> tZMMS0008);
}
