package com.haier.stock.eai.finance.transBadGoodsInfoFromGvsToEhaier;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-04-13T10:32:09.096+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "TransBadGoodsInfoFromGVSToEHAIERSOAPQSService", wsdlLocation = "file:wsdl/TransBadGoodsInfoFromGVSToEHAIER.wsdl", targetNamespace = "http://www.example.org/TransBadGoodsInfoFromGVSToEHAIER/")
public class TransBadGoodsInfoFromGVSToEHAIERSOAPQSService extends Service {

    public final static URL   WSDL_LOCATION;

    public final static QName SERVICE                                    = new QName(
                                                                             "http://www.example.org/TransBadGoodsInfoFromGVSToEHAIER/",
                                                                             "TransBadGoodsInfoFromGVSToEHAIERSOAPQSService");
    public final static QName TransBadGoodsInfoFromGVSToEHAIERSOAPQSPort = new QName(
                                                                             "http://www.example.org/TransBadGoodsInfoFromGVSToEHAIER/",
                                                                             "TransBadGoodsInfoFromGVSToEHAIERSOAPQSPort");
    static {
        URL url = null;
        try {
            url = new URL(
                "file:/D:/Users/sjc/ehaier_workspace/wsdl-creator/wsdl-creator/src/main/resources/TransBadGoodsInfoFromGVSToEHAIER.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger
                .getLogger(TransBadGoodsInfoFromGVSToEHAIERSOAPQSService.class.getName())
                .log(
                    java.util.logging.Level.INFO,
                    "Can not initialize the default wsdl from {0}",
                    "file:/D:/Users/sjc/ehaier_workspace/wsdl-creator/wsdl-creator/src/main/resources/TransBadGoodsInfoFromGVSToEHAIER.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TransBadGoodsInfoFromGVSToEHAIERSOAPQSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TransBadGoodsInfoFromGVSToEHAIERSOAPQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransBadGoodsInfoFromGVSToEHAIERSOAPQSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     * @return
     *     returns TransBadGoodsInfoFromGVSToEHAIER
     */
    @WebEndpoint(name = "TransBadGoodsInfoFromGVSToEHAIERSOAPQSPort")
    public TransBadGoodsInfoFromGVSToEHAIER getTransBadGoodsInfoFromGVSToEHAIERSOAPQSPort() {
        return getPort(TransBadGoodsInfoFromGVSToEHAIERSOAPQSPort,
            TransBadGoodsInfoFromGVSToEHAIER.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransBadGoodsInfoFromGVSToEHAIER
     */
    @WebEndpoint(name = "TransBadGoodsInfoFromGVSToEHAIERSOAPQSPort")
    public TransBadGoodsInfoFromGVSToEHAIER getTransBadGoodsInfoFromGVSToEHAIERSOAPQSPort(WebServiceFeature... features) {
        return getPort(TransBadGoodsInfoFromGVSToEHAIERSOAPQSPort,
            TransBadGoodsInfoFromGVSToEHAIER.class, features);
    }

}
