package com.haier.stock.createscordertoles;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-01T16:48:01.424+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "CreateSCOrderToLES",
                  wsdlLocation = "file:/D:/CreateSCOrderToLES.wsdl",
                  targetNamespace = "http://www.example.org/CreateSCOrderToLES/")
public class CreateSCOrderToLES_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/CreateSCOrderToLES/", "CreateSCOrderToLES");
    public final static QName CreateSCOrderToLESSOAP = new QName("http://www.example.org/CreateSCOrderToLES/", "CreateSCOrderToLESSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/CreateSCOrderToLES.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CreateSCOrderToLES_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/CreateSCOrderToLES.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CreateSCOrderToLES_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreateSCOrderToLES_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreateSCOrderToLES_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CreateSCOrderToLES_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CreateSCOrderToLES_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CreateSCOrderToLES_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CreateSCOrderToLES
     */
    @WebEndpoint(name = "CreateSCOrderToLESSOAP")
    public CreateSCOrderToLES getCreateSCOrderToLESSOAP() {
        return super.getPort(CreateSCOrderToLESSOAP, CreateSCOrderToLES.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreateSCOrderToLES
     */
    @WebEndpoint(name = "CreateSCOrderToLESSOAP")
    public CreateSCOrderToLES getCreateSCOrderToLESSOAP(WebServiceFeature... features) {
        return super.getPort(CreateSCOrderToLESSOAP, CreateSCOrderToLES.class, features);
    }

}
