
package com.haier.stock.createscordertoles;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-01T16:48:01.365+08:00
 * Generated source version: 3.2.4
 *
 */
public final class CreateSCOrderToLES_CreateSCOrderToLESSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/CreateSCOrderToLES/", "CreateSCOrderToLES");

    private CreateSCOrderToLES_CreateSCOrderToLESSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CreateSCOrderToLES_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        CreateSCOrderToLES_Service ss = new CreateSCOrderToLES_Service(wsdlURL, SERVICE_NAME);
        CreateSCOrderToLES port = ss.getCreateSCOrderToLESSOAP();

        {
        System.out.println("Invoking createSCOrderToLES...");
        java.util.List<com.haier.stock.createscordertoles.InputType> _createSCOrderToLES_input = null;
        java.util.List<com.haier.stock.createscordertoles.OutputType> _createSCOrderToLES__return = port.createSCOrderToLES(_createSCOrderToLES_input);
        System.out.println("createSCOrderToLES.result=" + _createSCOrderToLES__return);


        }

        System.exit(0);
    }

}
