
package com.haier.svc.purchase.products;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetMTLInfoMDM2SHC_Mine", targetNamespace = "http://www.example.org/GetMTLInfoMDM2SHC_Mine/", wsdlLocation = "file:/D:/GetMTLInfoMDM2SHC.wsdl")
public class GetMTLInfoMDM2SHCMine_Service
    extends Service
{

    private final static URL GETMTLINFOMDM2SHCMINE_WSDL_LOCATION;
    private final static WebServiceException GETMTLINFOMDM2SHCMINE_EXCEPTION;
    private final static QName GETMTLINFOMDM2SHCMINE_QNAME = new QName("http://www.example.org/GetMTLInfoMDM2SHC_Mine/", "GetMTLInfoMDM2SHC_Mine");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/GetMTLInfoMDM2SHC.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETMTLINFOMDM2SHCMINE_WSDL_LOCATION = url;
        GETMTLINFOMDM2SHCMINE_EXCEPTION = e;
    }

    public GetMTLInfoMDM2SHCMine_Service() {
        super(__getWsdlLocation(), GETMTLINFOMDM2SHCMINE_QNAME);
    }

    public GetMTLInfoMDM2SHCMine_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETMTLINFOMDM2SHCMINE_QNAME, features);
    }

    public GetMTLInfoMDM2SHCMine_Service(URL wsdlLocation) {
        super(wsdlLocation, GETMTLINFOMDM2SHCMINE_QNAME);
    }

    public GetMTLInfoMDM2SHCMine_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETMTLINFOMDM2SHCMINE_QNAME, features);
    }

    public GetMTLInfoMDM2SHCMine_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetMTLInfoMDM2SHCMine_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetMTLInfoMDM2SHCMine
     */
    @WebEndpoint(name = "GetMTLInfoMDM2SHC_MineSOAP")
    public GetMTLInfoMDM2SHCMine getGetMTLInfoMDM2SHCMineSOAP() {
        return super.getPort(new QName("http://www.example.org/GetMTLInfoMDM2SHC_Mine/", "GetMTLInfoMDM2SHC_MineSOAP"), GetMTLInfoMDM2SHCMine.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetMTLInfoMDM2SHCMine
     */
    @WebEndpoint(name = "GetMTLInfoMDM2SHC_MineSOAP")
    public GetMTLInfoMDM2SHCMine getGetMTLInfoMDM2SHCMineSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/GetMTLInfoMDM2SHC_Mine/", "GetMTLInfoMDM2SHC_MineSOAP"), GetMTLInfoMDM2SHCMine.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETMTLINFOMDM2SHCMINE_EXCEPTION!= null) {
            throw GETMTLINFOMDM2SHCMINE_EXCEPTION;
        }
        return GETMTLINFOMDM2SHCMINE_WSDL_LOCATION;
    }

}
