
package com.haier.svc.purchase.products;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetMTLInfoMDM2SHC_Mine", targetNamespace = "http://www.example.org/GetMTLInfoMDM2SHC_Mine/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetMTLInfoMDM2SHCMine {


    /**
     * 
     * @param materialCode
     * @return
     *     returns com.haier.ois.shop.demo.OutType
     */
    @WebMethod(operationName = "GetMTLInfoMDM2SHC_Mine", action = "http://www.example.org/GetMTLInfoMDM2SHC_Mine/GetMTLInfoMDM2SHC_Mine")
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "GetMTLInfoMDM2SHC_Mine", targetNamespace = "http://www.example.org/GetMTLInfoMDM2SHC_Mine/", className = "com.haier.ois.shop.demo.GetMTLInfoMDM2SHCMine_Type")
    @ResponseWrapper(localName = "GetMTLInfoMDM2SHC_MineResponse", targetNamespace = "http://www.example.org/GetMTLInfoMDM2SHC_Mine/", className = "com.haier.ois.shop.demo.GetMTLInfoMDM2SHCMineResponse")
    public OutType getMTLInfoMDM2SHCMine(
            @WebParam(name = "materialCode", targetNamespace = "")
                    String materialCode);

}
