interconn:
  project: 3W-CBS
  app: invoice-svc
  monitor:
    url: http://collector.c.haier.net
    enable: false
  trace:
    url: http://collector-trace.c.haier.net
    sample: 0 #抽样率，0：关闭，1：全采样，sample<1：部分采样

dubbo:
  registry: 10.138.8.223:2181,10.138.8.224:2181,10.138.8.225:2181
  port: 20890
  timeout: 10000
  threads: 100
  heartBeats: 10000

invoice:
  platformcode: PT000002
  version: 2.0
  wsdl:
    location: /wsdl

einvoice:
  cerpath: /einvoice/ChiEinv.cer
  scriptpath: /einvoice/Ehaier.keystore
  keyStoreAbner: q_ehaier_cde
  keyStorePassWord: a4q_8uy

logging:
    config: classpath:logback-spring.xml
    path: /home/haieradmin/admin/javalog/invoice-svc/