package com.haier.afterSale.eai.transaccountcheckingfromcbstoles;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-12-13T10:20:13.389+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://www.example.org/TransAccountCheckingFromCBSToLES/", name = "TransAccountCheckingFromCBSToLES")
@XmlSeeAlso({ObjectFactory.class})
public interface TransAccountCheckingFromCBSToLES {

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "TransAccountCheckingFromCBSToLES", targetNamespace = "http://www.example.org/TransAccountCheckingFromCBSToLES/", className = "org.example.transaccountcheckingfromcbstoles.TransAccountCheckingFromCBSToLES_Type")
    @WebMethod(operationName = "TransAccountCheckingFromCBSToLES", action = "http://www.example.org/TransAccountCheckingFromCBSToLES/TransAccountCheckingFromCBSToLES")
    @ResponseWrapper(localName = "TransAccountCheckingFromCBSToLESResponse", targetNamespace = "http://www.example.org/TransAccountCheckingFromCBSToLES/", className = "org.example.transaccountcheckingfromcbstoles.TransAccountCheckingFromCBSToLESResponse")
    public com.haier.afterSale.eai.transaccountcheckingfromcbstoles.OutType transAccountCheckingFromCBSToLES(
            @WebParam(name = "in", targetNamespace = "")
                    com.haier.afterSale.eai.transaccountcheckingfromcbstoles.InType in
    );
}
