package com.haier.shop.service;

import com.alibaba.fastjson.JSONObject;
import com.haier.common.PagerInfo;
import com.haier.shop.model.DistributionDetails;

import java.util.List;

/**
* Code generated by CodeGen
* Desc: 天猫分销明细表服务`
* Date: 2018-05-22
*/
public interface DistributionDetailsDataService {

    /**
     * 查询
     * @param model
     * @return
     */
    public List<DistributionDetails> queryDistributionDetails(DistributionDetails model);

    /**
     * 根据网单号查询
     * @param netSn
     * @return
     */
    public List<DistributionDetails> queryDistributionDetailsByNetSn(String netSn);

    /**
     * 新增
     * @param model
     */
    public void create(DistributionDetails model);

    /**
     * 批量插入
     * @param modelList
     */
    public void creates(List<DistributionDetails> modelList);


    /**
     * 更新
     * @param model
     */
    public void updateDistributionDetails(DistributionDetails model);

    public JSONObject paging(DistributionDetails param, PagerInfo page);

    public JSONObject export(DistributionDetails param) ;
}
