package com.haier.shop.service;

import com.haier.shop.model.DistributionDetails;
import com.haier.shop.model.OdsTMFXCategoryIndustry;

import java.util.List;
import java.util.Map;

/**
* Code generated by CodeGen
* Desc: 品类品牌产业数据维护表服务`
* Date: 2018-05-22
*/
public interface OdsTMFXCategoryIndustryService {

    /**
     * 查询
     * @param model
     * @return
     */
    public List<OdsTMFXCategoryIndustry> queryOdsTMFXCategoryIndustry(OdsTMFXCategoryIndustry model);

    /**
     * 分页查询
     * @param map
     * @return
     * @throws Exception
     */
    public Map<String, Object> queryOdsTMFXCategoryIndustry(Map<String, Object> map) throws Exception;

    /**
     * 根据id查询
     * @param id
     * @return
     */
    public List<OdsTMFXCategoryIndustry> queryOdsTMFXCategoryIndustryById(String id);

    /**
     * 新增
     * @param model
     */
    public void create(OdsTMFXCategoryIndustry model);

    /**
     * 批量插入
     * @param modelList
     */
    public void creates(List<OdsTMFXCategoryIndustry> modelList);


    /**
     * 更新
     * @param model
     */
    public void updateOdsTMFXCategoryIndustry(OdsTMFXCategoryIndustry model);

}
