package com.haier.shop.service;

import com.alibaba.fastjson.JSONObject;
import com.haier.common.PagerInfo;
import com.haier.shop.model.OdsTMFXPointMaintain;
import com.haier.shop.model.SettlementInvoiceData;
import java.util.List;
import java.util.Map;

/**
* Code generated by CodeGen
* Desc: 佣金结算数据推送队列服务`
* Date: 2018-05-28
*/
public interface SettlementInvoiceDataDataService {

    /**
     * 查询
     * @param model
     * @return
     */
    public List<SettlementInvoiceData> querySettlementInvoiceData(SettlementInvoiceData model);

    /**
     * 查询
     * @param id
     * @return
     */
    public List<SettlementInvoiceData> querySettlementInvoiceDataById(String id);

    /**
     * 新增
     * @param model
     */
    public void create(SettlementInvoiceData model);

    /**
     * 批量插入
     * @param modelList
     */
    public void creates(List<SettlementInvoiceData> modelList);


    /**
     * 更新
     * @param model
     */
    public void updateSettlementInvoiceData(SettlementInvoiceData model);

    /**
     * 分页查询
     * @param param
     * @param page
     * @return
     */
    public JSONObject paging(Map<String, String> param, PagerInfo page);

    /**
     * 导出
     * @param param
     * @return
     */
    public JSONObject export(Map<String, String> param) ;

    /**
     * 导入
     * @param list
     */
    public void bulkImport(List<SettlementInvoiceData> list);


    public SettlementInvoiceData getByCOrderSnAndStatusType(String cOrderSn,int statusType);

	public List<String> getSelections();
}
