package com.haier.shop.service;

import java.util.List;

import com.alibaba.fastjson.JSONObject;
import com.haier.common.PagerInfo;
import com.haier.shop.model.SNOdsTMFXPeculiarCategory;
import com.haier.shop.model.SNOdsTMFXRebatesMonthlyDetail;

/**
* Code generated by CodeGen
* Desc: 苏宁分销-返利月度明细表服务`
* Date: 2018-05-24
*/
public interface SNOdsTMFXRebatesMonthlyDetailDataService {

    /**
     * 查询
     * @param model
     * @return
     */
    public List<SNOdsTMFXRebatesMonthlyDetail> queryOdsTMFXRebatesMonthlyDetail(SNOdsTMFXRebatesMonthlyDetail model);

    /**
     * 根据id查询
     * @param id
     * @return
     */
    public List<SNOdsTMFXRebatesMonthlyDetail> queryOdsTMFXRebatesMonthlyDetailById(String id);

    /**
     * 新增
     * @param model
     */
    public void create(SNOdsTMFXRebatesMonthlyDetail model);

    /**
     * 批量插入
     * @param modelList
     */
    public void creates(List<SNOdsTMFXRebatesMonthlyDetail> modelList);


    /**
     * 更新
     * @param model
     */
    public void updateOdsTMFXRebatesMonthlyDetail(SNOdsTMFXRebatesMonthlyDetail model);

    /**
     * 数据生成
     * @return
     */

    public JSONObject createData(String year,String month,String type);

    /**
     * 生成返利月度明细
     * 查询最新点位的时候分开查,查1条的用queryPointByDistribution 查多条的用queryPointByDistribution3 --2018.02.26
     * @param year
     * @param month
     * @param type
     */
    public String createDetail(String year,String month,String type);

    /**
     * 返利汇总 按生态店 产业 品牌
     */
    public void createSummary(String year,String month,String type);

    /**
     * 返利汇总 按生态店
     */
    public String createShopData(String year,String month,String type);

    /**
     * 按产业汇总生成营销费用及比例
     * @param year
     * @param month
     * @param type
     */
    public String createPromotionCostSummary(String year,String month,String type);

    /**
     * 只按品牌产业汇总
     * @param year
     * @param month
     * @param type
     */
    public void createIndustrySummary(String year,String month,String type);

//    public void createPeculiar(SNOdsTMFXPeculiarCategory old, SNOdsTMFXPeculiarCategory newcome);

    public JSONObject paging(SNOdsTMFXRebatesMonthlyDetail param, PagerInfo page);

    public JSONObject export(SNOdsTMFXRebatesMonthlyDetail param) ;

}
