package com.haier.stock.eai.finance.transqualitygoodsreturnfromgvs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-05-12T16:29:46.708+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "TransQualityGoodsReturnFromGVS", wsdlLocation = "file:/D:/Users/sjc/ehaier_workspace/wsdl-creator/wsdl-creator/src/main/resources/TransQualityGoodsReturnFromGVS.wsdl", targetNamespace = "http://www.example.org/TransQualityGoodsReturnFromGVS/")
public class TransQualityGoodsReturnFromGVS_Service extends Service {

    public final static URL   WSDL_LOCATION;

    public final static QName SERVICE                            = new QName(
                                                                     "http://www.example.org/TransQualityGoodsReturnFromGVS/",
                                                                     "TransQualityGoodsReturnFromGVS");
    public final static QName TransQualityGoodsReturnFromGVSSOAP = new QName(
                                                                     "http://www.example.org/TransQualityGoodsReturnFromGVS/",
                                                                     "TransQualityGoodsReturnFromGVSSOAP");
    static {
        URL url = null;
        try {
            url = new URL(
                "file:/D:/Users/sjc/ehaier_workspace/wsdl-creator/wsdl-creator/src/main/resources/TransQualityGoodsReturnFromGVS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger
                .getLogger(TransQualityGoodsReturnFromGVS_Service.class.getName())
                .log(
                    java.util.logging.Level.INFO,
                    "Can not initialize the default wsdl from {0}",
                    "file:/D:/Users/sjc/ehaier_workspace/wsdl-creator/wsdl-creator/src/main/resources/TransQualityGoodsReturnFromGVS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TransQualityGoodsReturnFromGVS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TransQualityGoodsReturnFromGVS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransQualityGoodsReturnFromGVS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     * @return
     *     returns TransQualityGoodsReturnFromGVS
     */
    @WebEndpoint(name = "TransQualityGoodsReturnFromGVSSOAP")
    public TransQualityGoodsReturnFromGVS getTransQualityGoodsReturnFromGVSSOAP() {
        return super.getPort(TransQualityGoodsReturnFromGVSSOAP,
            TransQualityGoodsReturnFromGVS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransQualityGoodsReturnFromGVS
     */
    @WebEndpoint(name = "TransQualityGoodsReturnFromGVSSOAP")
    public TransQualityGoodsReturnFromGVS getTransQualityGoodsReturnFromGVSSOAP(WebServiceFeature... features) {
        return super.getPort(TransQualityGoodsReturnFromGVSSOAP,
            TransQualityGoodsReturnFromGVS.class, features);
    }

}
