package com.haier.stock.eai.finance.transqualitygoodsreturnfromgvs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-05-12T16:29:46.639+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://www.example.org/TransQualityGoodsReturnFromGVS/", name = "TransQualityGoodsReturnFromGVS")
@XmlSeeAlso({ ObjectFactory.class })
public interface TransQualityGoodsReturnFromGVS {

    @WebResult(name = "OUTPUT", targetNamespace = "")
    @RequestWrapper(localName = "TransQualityGoodsReturnFromGVS", targetNamespace = "http://www.example.org/TransQualityGoodsReturnFromGVS/", className = "org.example.transqualitygoodsreturnfromgvs.TransQualityGoodsReturnFromGVS_Type")
    @WebMethod(operationName = "TransQualityGoodsReturnFromGVS", action = "http://www.example.org/TransQualityGoodsReturnFromGVS/TransQualityGoodsReturnFromGVS")
    @ResponseWrapper(localName = "TransQualityGoodsReturnFromGVSResponse", targetNamespace = "http://www.example.org/TransQualityGoodsReturnFromGVS/", className = "org.example.transqualitygoodsreturnfromgvs.TransQualityGoodsReturnFromGVSResponse")
    public java.util.List<ZMMINBOUND018OUT> transQualityGoodsReturnFromGVS(
        @WebParam(name = "SysName", targetNamespace = "") String sysName,
        @WebParam(name = "INPUT", targetNamespace = "") java.util.List<ZMMINBOUND018IN> input);
}
