<?xml version="1.0" encoding="UTF-8"?>
<WL5G3N0:definitions name="ZWD_CBSINT01_NEW-concrete" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/sap/OSB/Logistics/ZWD_CBSINT01_NEW" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://xmlns.oracle.com/pcbpel/adapter/sap/OSB/Logistics/ZWD_CBSINT01_NEW" xmlns:WL5G3N2="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:import location="http://10.135.1.185:7001/Logistics/LES/QueryTransferFeeFromHBDMToLES/QueryTransferFeeFromHBDMToLES?WSDL%2FLogistics%2FLES%2FQueryTransferFeeFromHBDMToLES%2FZWD_CBSINT01_NEW" namespace="http://xmlns.oracle.com/pcbpel/adapter/sap/OSB/Logistics/ZWD_CBSINT01_NEW"/>
  <WL5G3N0:binding name="ZWD_CBSINT01_NEW_PT-binding" type="WL5G3N1:ZWD_CBSINT01_NEW_PT">
    <WL5G3N2:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="ZWD_CBSINT01_NEW">
      <WL5G3N2:operation soapAction="ZWD_CBSINT01_NEW"/>
      <WL5G3N0:input>
        <WL5G3N2:body use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N2:body use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="ZWD_CBSINT01_NEW_PT-bindingQSService">
    <WL5G3N0:documentation>OSB Service</WL5G3N0:documentation>
    <WL5G3N0:port binding="WL5G3N1:ZWD_CBSINT01_NEW_PT-binding" name="ZWD_CBSINT01_NEW_PT-bindingQSPort">
      <WL5G3N2:address location="http://10.135.1.185:7001/Logistics/LES/QueryTransferFeeFromHBDMToLES/QueryTransferFeeFromHBDMToLES"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>