package com.haier.stock.eai.finance.order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Tue Aug 06 09:48:54 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebService(targetNamespace = "http://www.example.org/TransOrderInfoFromEhaierToGVS/", name = "TransOrderInfoFromEhaierToGVS")
@XmlSeeAlso({ ObjectFactory.class })
public interface TransOrderInfoFromEhaierToGVS {

    @RequestWrapper(localName = "TransOrderInfoFromEhaierToGVS", targetNamespace = "http://www.example.org/TransOrderInfoFromEhaierToGVS/", className = "org.example.transorderinfofromehaiertogvs.TransOrderInfoFromEhaierToGVS_Type")
    @ResponseWrapper(localName = "TransOrderInfoFromEhaierToGVSResponse", targetNamespace = "http://www.example.org/TransOrderInfoFromEhaierToGVS/", className = "org.example.transorderinfofromehaiertogvs.TransOrderInfoFromEhaierToGVSResponse")
    @WebMethod(operationName = "TransOrderInfoFromEhaierToGVS", action = "http://www.example.org/TransOrderInfoFromEhaierToGVS/TransOrderInfoFromEhaierToGVS")
    public void transOrderInfoFromEhaierToGVS(
        @WebParam(name = "T_ZSDS0001", targetNamespace = "") java.util.List<com.haier.stock.eai.finance.order.ZSDS0001> tZSDS0001,
        @WebParam(mode = WebParam.Mode.OUT, name = "EX_SUBRC", targetNamespace = "") javax.xml.ws.Holder<Integer> exSUBRC,
        @WebParam(mode = WebParam.Mode.OUT, name = "T_MSG", targetNamespace = "") javax.xml.ws.Holder<java.util.List<com.haier.stock.eai.finance.order.ZSDS0002>> tMSG);
}
