package com.haier.svc.bean.getucunioninfofromles;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-04-10T15:38:02.128+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.example.org/GetKUCUNInfoFromLESToEHAIER/", name = "GetKUCUNInfoFromLESToEHAIER")
@XmlSeeAlso({ObjectFactory.class})
public interface GetKUCUNInfoFromLESToEHAIER {

    @WebMethod(operationName = "GetKUCUNInfoFromLESToEHAIER", action = "http://www.example.org/GetKUCUNInfoFromLESToEHAIER/GetKUCUNInfoFromLESToEHAIER")
    @RequestWrapper(localName = "GetKUCUNInfoFromLESToEHAIER", targetNamespace = "http://www.example.org/GetKUCUNInfoFromLESToEHAIER/", className = "com.haier.svc.bean.getucunioninfofromles.GetKUCUNInfoFromLESToEHAIER_Type")
    @ResponseWrapper(localName = "GetKUCUNInfoFromLESToEHAIERResponse", targetNamespace = "http://www.example.org/GetKUCUNInfoFromLESToEHAIER/", className = "com.haier.svc.bean.getucunioninfofromles.GetKUCUNInfoFromLESToEHAIERResponse")
    public void getKUCUNInfoFromLESToEHAIER(
            @WebParam(name = "CRK", targetNamespace = "")
                    String crk,
            @WebParam(name = "DATE_BEGIN", targetNamespace = "")
                    String dateBEGIN,
            @WebParam(name = "DATE_END", targetNamespace = "")
                    String dateEND,
            @WebParam(name = "KUWEI", targetNamespace = "")
                    String kuwei,
            @WebParam(name = "TIME_BEGIN", targetNamespace = "")
                    String timeBEGIN,
            @WebParam(name = "TIME_END", targetNamespace = "")
                    String timeEND,
            @WebParam(mode = WebParam.Mode.OUT, name = "FLAG", targetNamespace = "")
                    javax.xml.ws.Holder<String> flag,
            @WebParam(mode = WebParam.Mode.OUT, name = "MESSAGE", targetNamespace = "")
                    javax.xml.ws.Holder<String> message,
            @WebParam(mode = WebParam.Mode.OUT, name = "OUTPUT", targetNamespace = "")
                    javax.xml.ws.Holder<java.util.List<com.haier.svc.bean.getucunioninfofromles.GetKUCUNInfoFromLESToEHAIERResponse.OUTPUT>> output,
            @WebParam(mode = WebParam.Mode.OUT, name = "OUTPUT1", targetNamespace = "")
                    javax.xml.ws.Holder<java.util.List<com.haier.svc.bean.getucunioninfofromles.GetKUCUNInfoFromLESToEHAIERResponse.OUTPUT1>> output1
    );
}
