
package com.haier.svc.bean.getucunioninfofromles;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-04-10T15:38:01.954+08:00
 * Generated source version: 3.1.12
 * 
 */
public final class GetKUCUNInfoFromLESToEHAIER_GetKUCUNInfoFromLESToEHAIERSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/GetKUCUNInfoFromLESToEHAIER/", "GetKUCUNInfoFromLESToEHAIER");

    private GetKUCUNInfoFromLESToEHAIER_GetKUCUNInfoFromLESToEHAIERSOAP_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = GetKUCUNInfoFromLESToEHAIER_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GetKUCUNInfoFromLESToEHAIER_Service ss = new GetKUCUNInfoFromLESToEHAIER_Service(wsdlURL, SERVICE_NAME);
        GetKUCUNInfoFromLESToEHAIER port = ss.getGetKUCUNInfoFromLESToEHAIERSOAP();  
        
        {
        System.out.println("Invoking getKUCUNInfoFromLESToEHAIER...");
        String _getKUCUNInfoFromLESToEHAIER_crk = "";
        String _getKUCUNInfoFromLESToEHAIER_dateBEGIN = "";
        String _getKUCUNInfoFromLESToEHAIER_dateEND = "";
        String _getKUCUNInfoFromLESToEHAIER_kuwei = "";
        String _getKUCUNInfoFromLESToEHAIER_timeBEGIN = "";
        String _getKUCUNInfoFromLESToEHAIER_timeEND = "";
        javax.xml.ws.Holder<String> _getKUCUNInfoFromLESToEHAIER_flag = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getKUCUNInfoFromLESToEHAIER_message = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<java.util.List<GetKUCUNInfoFromLESToEHAIERResponse.OUTPUT>> _getKUCUNInfoFromLESToEHAIER_output = new javax.xml.ws.Holder<java.util.List<GetKUCUNInfoFromLESToEHAIERResponse.OUTPUT>>();
        javax.xml.ws.Holder<java.util.List<GetKUCUNInfoFromLESToEHAIERResponse.OUTPUT1>> _getKUCUNInfoFromLESToEHAIER_output1 = new javax.xml.ws.Holder<java.util.List<GetKUCUNInfoFromLESToEHAIERResponse.OUTPUT1>>();
        port.getKUCUNInfoFromLESToEHAIER(_getKUCUNInfoFromLESToEHAIER_crk, _getKUCUNInfoFromLESToEHAIER_dateBEGIN, _getKUCUNInfoFromLESToEHAIER_dateEND, _getKUCUNInfoFromLESToEHAIER_kuwei, _getKUCUNInfoFromLESToEHAIER_timeBEGIN, _getKUCUNInfoFromLESToEHAIER_timeEND, _getKUCUNInfoFromLESToEHAIER_flag, _getKUCUNInfoFromLESToEHAIER_message, _getKUCUNInfoFromLESToEHAIER_output, _getKUCUNInfoFromLESToEHAIER_output1);

        System.out.println("getKUCUNInfoFromLESToEHAIER._getKUCUNInfoFromLESToEHAIER_flag=" + _getKUCUNInfoFromLESToEHAIER_flag.value);
        System.out.println("getKUCUNInfoFromLESToEHAIER._getKUCUNInfoFromLESToEHAIER_message=" + _getKUCUNInfoFromLESToEHAIER_message.value);
        System.out.println("getKUCUNInfoFromLESToEHAIER._getKUCUNInfoFromLESToEHAIER_output=" + _getKUCUNInfoFromLESToEHAIER_output.value);
        System.out.println("getKUCUNInfoFromLESToEHAIER._getKUCUNInfoFromLESToEHAIER_output1=" + _getKUCUNInfoFromLESToEHAIER_output1.value);

        }

        System.exit(0);
    }

}
