package com.haier.stock.eai.finance.plpurchase;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 15 13:04:22 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebService(targetNamespace = "http://www.example.org/CreatePurchaseOrderInfoFromEhaier/", name = "CreatePurchaseOrderInfoFromEhaier")
@XmlSeeAlso({ ObjectFactory.class })
public interface CreatePurchaseOrderInfoFromEhaier {

    @RequestWrapper(localName = "CreatePurchaseOrderInfoFromEhaier", targetNamespace = "http://www.example.org/CreatePurchaseOrderInfoFromEhaier/", className = "org.example.createpurchaseorderinfofromehaier.CreatePurchaseOrderInfoFromEhaier_Type")
    @ResponseWrapper(localName = "CreatePurchaseOrderInfoFromEhaierResponse", targetNamespace = "http://www.example.org/CreatePurchaseOrderInfoFromEhaier/", className = "org.example.createpurchaseorderinfofromehaier.CreatePurchaseOrderInfoFromEhaierResponse")
    @WebMethod(operationName = "CreatePurchaseOrderInfoFromEhaier", action = "http://www.example.org/CreatePurchaseOrderInfoFromEhaier/CreatePurchaseOrderInfoFromEhaier")
    public void createPurchaseOrderInfoFromEhaier(
        @WebParam(name = "T_ZMMS0006", targetNamespace = "") java.util.List<com.haier.stock.eai.finance.plpurchase.ZMMS0006> tZMMS0006,
        @WebParam(mode = WebParam.Mode.OUT, name = "EX_SUBRC", targetNamespace = "") javax.xml.ws.Holder<Integer> exSUBRC,
        @WebParam(mode = WebParam.Mode.OUT, name = "T_MSG", targetNamespace = "") javax.xml.ws.Holder<java.util.List<com.haier.stock.eai.finance.plpurchase.ZSDS0002>> tMSG);
}
