/*
 * 
 */

package com.haier.stock.eai.finance.plpurchase;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 15 13:04:22 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebServiceClient(name = "CreatePurchaseOrderInfoFromEhaier", wsdlLocation = "file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/CreatePurchaseOrderInfoFromEhaier.WSDL", targetNamespace = "http://www.example.org/CreatePurchaseOrderInfoFromEhaier/")
public class CreatePurchaseOrderInfoFromEhaier_Service extends Service {

    public final static URL   WSDL_LOCATION;
    public final static QName SERVICE                               = new QName(
                                                                        "http://www.example.org/CreatePurchaseOrderInfoFromEhaier/",
                                                                        "CreatePurchaseOrderInfoFromEhaier");
    public final static QName CreatePurchaseOrderInfoFromEhaierSOAP = new QName(
                                                                        "http://www.example.org/CreatePurchaseOrderInfoFromEhaier/",
                                                                        "CreatePurchaseOrderInfoFromEhaierSOAP");
    static {
        URL url = null;
        try {
            url = new URL(
                "file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/CreatePurchaseOrderInfoFromEhaier.WSDL");
        } catch (MalformedURLException e) {
            System.err
                .println("Can not initialize the default wsdl from file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/CreatePurchaseOrderInfoFromEhaier.WSDL");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CreatePurchaseOrderInfoFromEhaier_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreatePurchaseOrderInfoFromEhaier_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreatePurchaseOrderInfoFromEhaier_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns CreatePurchaseOrderInfoFromEhaier
     */
    @WebEndpoint(name = "CreatePurchaseOrderInfoFromEhaierSOAP")
    public CreatePurchaseOrderInfoFromEhaier getCreatePurchaseOrderInfoFromEhaierSOAP() {
        return super.getPort(CreatePurchaseOrderInfoFromEhaierSOAP,
            CreatePurchaseOrderInfoFromEhaier.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreatePurchaseOrderInfoFromEhaier
     */
    @WebEndpoint(name = "CreatePurchaseOrderInfoFromEhaierSOAP")
    public CreatePurchaseOrderInfoFromEhaier getCreatePurchaseOrderInfoFromEhaierSOAP(WebServiceFeature... features) {
        return super.getPort(CreatePurchaseOrderInfoFromEhaierSOAP,
            CreatePurchaseOrderInfoFromEhaier.class, features);
    }

}
