package com.haier.vehicle.wsdl.querystatus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-19T10:50:27.793+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.example.org/QueryOrderStaToEstore/", name = "QueryOrderStaToEstore")
@XmlSeeAlso({ObjectFactory.class})
public interface QueryOrderStaToEstore {

    @RequestWrapper(localName = "QueryOrderStaToEstore_wsdl", targetNamespace = "http://www.example.org/QueryOrderStaToEstore/", className = "com.haier.cbs.vehicle.querystatus.QueryOrderStaToEstoreWsdl")
    @WebMethod(operationName = "QueryOrderStaToEstore_wsdl", action = "http://www.example.org/QueryOrderStaToEstore/QueryOrderStaToEstore_wsdl")
    @ResponseWrapper(localName = "QueryOrderStaToEstore_wsdlResponse", targetNamespace = "http://www.example.org/QueryOrderStaToEstore/", className = "com.haier.cbs.vehicle.querystatus.QueryOrderStaToEstoreWsdlResponse")
    public void queryOrderStaToEstoreWsdl(
            @WebParam(name = "in", targetNamespace = "")
                    java.util.List<com.haier.vehicle.wsdl.querystatus.InputType> in,
            @WebParam(mode = WebParam.Mode.OUT, name = "out", targetNamespace = "")
                    javax.xml.ws.Holder<java.util.List<com.haier.vehicle.wsdl.querystatus.OutputType>> out,
            @WebParam(mode = WebParam.Mode.OUT, name = "flag", targetNamespace = "")
                    javax.xml.ws.Holder<String> flag,
            @WebParam(mode = WebParam.Mode.OUT, name = "message", targetNamespace = "")
                    javax.xml.ws.Holder<String> message,
            @WebParam(mode = WebParam.Mode.OUT, name = "error_detail", targetNamespace = "")
                    javax.xml.ws.Holder<String> errorDetail
    );
}
