package com.haier.vehicle.wsdl.querystatus;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-19T10:50:27.804+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "QueryOrderStaToEstore", 
                  wsdlLocation = "file:/D:/java/QueryOrderStatusToEstore.wsdl",
                  targetNamespace = "http://www.example.org/QueryOrderStaToEstore/") 
public class QueryOrderStaToEstore_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/QueryOrderStaToEstore/", "QueryOrderStaToEstore");
    public final static QName QueryOrderStaToEstoreSOAP = new QName("http://www.example.org/QueryOrderStaToEstore/", "QueryOrderStaToEstoreSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/java/QueryOrderStatusToEstore.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueryOrderStaToEstore_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/java/QueryOrderStatusToEstore.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QueryOrderStaToEstore_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryOrderStaToEstore_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryOrderStaToEstore_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns QueryOrderStaToEstore
     */
    @WebEndpoint(name = "QueryOrderStaToEstoreSOAP")
    public QueryOrderStaToEstore getQueryOrderStaToEstoreSOAP() {
        return super.getPort(QueryOrderStaToEstoreSOAP, QueryOrderStaToEstore.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryOrderStaToEstore
     */
    @WebEndpoint(name = "QueryOrderStaToEstoreSOAP")
    public QueryOrderStaToEstore getQueryOrderStaToEstoreSOAP(WebServiceFeature... features) {
        return super.getPort(QueryOrderStaToEstoreSOAP, QueryOrderStaToEstore.class, features);
    }

}
