
package com.haier.vehicle.wsdl.querystatus;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-19T10:50:27.750+08:00
 * Generated source version: 3.1.12
 * 
 */
public final class QueryOrderStaToEstore_QueryOrderStaToEstoreSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/QueryOrderStaToEstore/", "QueryOrderStaToEstore");

    private QueryOrderStaToEstore_QueryOrderStaToEstoreSOAP_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = QueryOrderStaToEstore_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        QueryOrderStaToEstore_Service ss = new QueryOrderStaToEstore_Service(wsdlURL, SERVICE_NAME);
        QueryOrderStaToEstore port = ss.getQueryOrderStaToEstoreSOAP();  
        
        {
        System.out.println("Invoking queryOrderStaToEstoreWsdl...");
        java.util.List<com.haier.vehicle.wsdl.querystatus.InputType> _queryOrderStaToEstoreWsdl_in = null;
        javax.xml.ws.Holder<java.util.List<com.haier.vehicle.wsdl.querystatus.OutputType>> _queryOrderStaToEstoreWsdl_out = new javax.xml.ws.Holder<java.util.List<com.haier.vehicle.wsdl.querystatus.OutputType>>();
        javax.xml.ws.Holder<String> _queryOrderStaToEstoreWsdl_flag = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _queryOrderStaToEstoreWsdl_message = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _queryOrderStaToEstoreWsdl_errorDetail = new javax.xml.ws.Holder<String>();
        port.queryOrderStaToEstoreWsdl(_queryOrderStaToEstoreWsdl_in, _queryOrderStaToEstoreWsdl_out, _queryOrderStaToEstoreWsdl_flag, _queryOrderStaToEstoreWsdl_message, _queryOrderStaToEstoreWsdl_errorDetail);

        System.out.println("queryOrderStaToEstoreWsdl._queryOrderStaToEstoreWsdl_out=" + _queryOrderStaToEstoreWsdl_out.value);
        System.out.println("queryOrderStaToEstoreWsdl._queryOrderStaToEstoreWsdl_flag=" + _queryOrderStaToEstoreWsdl_flag.value);
        System.out.println("queryOrderStaToEstoreWsdl._queryOrderStaToEstoreWsdl_message=" + _queryOrderStaToEstoreWsdl_message.value);
        System.out.println("queryOrderStaToEstoreWsdl._queryOrderStaToEstoreWsdl_errorDetail=" + _queryOrderStaToEstoreWsdl_errorDetail.value);

        }

        System.exit(0);
    }

}
