package com.haier.svc.purchase.omst3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * OSB Service
 *
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-08T15:59:30.610+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "InterfaceOMSForecastService",
                  wsdlLocation = "http://10.138.40.168:8001/Production/CBS/TranForecastSubmissionFromOMSToCBS/TranForecastSubmissionFromOMSToCBS?wsdl",
                  targetNamespace = "http://service.oms.haier.com/services/InterfaceOMSForecast")
public class InterfaceOMSForecastService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.oms.haier.com/services/InterfaceOMSForecast", "InterfaceOMSForecastService");
    public final static QName InterfaceOMSForecast = new QName("http://service.oms.haier.com/services/InterfaceOMSForecast", "InterfaceOMSForecast");
    static {
        URL url = null;
        try {
            url = new URL("http://10.138.40.168:8001/Production/CBS/TranForecastSubmissionFromOMSToCBS/TranForecastSubmissionFromOMSToCBS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InterfaceOMSForecastService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.138.40.168:8001/Production/CBS/TranForecastSubmissionFromOMSToCBS/TranForecastSubmissionFromOMSToCBS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InterfaceOMSForecastService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InterfaceOMSForecastService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InterfaceOMSForecastService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public InterfaceOMSForecastService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public InterfaceOMSForecastService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public InterfaceOMSForecastService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns InterfaceOMSForecast
     */
    @WebEndpoint(name = "InterfaceOMSForecast")
    public InterfaceOMSForecast getInterfaceOMSForecast() {
        return super.getPort(InterfaceOMSForecast, InterfaceOMSForecast.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterfaceOMSForecast
     */
    @WebEndpoint(name = "InterfaceOMSForecast")
    public InterfaceOMSForecast getInterfaceOMSForecast(WebServiceFeature... features) {
        return super.getPort(InterfaceOMSForecast, InterfaceOMSForecast.class, features);
    }

}
