package com.haier.svc.purchase.omst3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-08T15:59:30.601+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://service.oms.haier.com/services/InterfaceOMSForecast", name = "InterfaceOMSForecast")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface InterfaceOMSForecast {

    @WebMethod
    @WebResult(name = "getForecastRecordReturn", targetNamespace = "http://service.oms.haier.com/services/InterfaceOMSForecast", partName = "getForecastRecordReturn")
    public ResponseData getForecastRecord(
        @WebParam(partName = "requestData", name = "requestData", targetNamespace = "http://service.oms.haier.com/services/InterfaceOMSForecast")
        RequestData requestData
    );
}
