
package com.haier.svc.purchase.omst3;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-08T15:59:30.554+08:00
 * Generated source version: 3.2.4
 *
 */
public final class InterfaceOMSForecast_InterfaceOMSForecast_Client {

    private static final QName SERVICE_NAME = new QName("http://service.oms.haier.com/services/InterfaceOMSForecast", "InterfaceOMSForecastService");

    private InterfaceOMSForecast_InterfaceOMSForecast_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = InterfaceOMSForecastService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        InterfaceOMSForecastService ss = new InterfaceOMSForecastService(wsdlURL, SERVICE_NAME);
        InterfaceOMSForecast port = ss.getInterfaceOMSForecast();

        {
        System.out.println("Invoking getForecastRecord...");
        com.haier.svc.purchase.omst3.RequestData _getForecastRecord_requestData = null;
        com.haier.svc.purchase.omst3.ResponseData _getForecastRecord__return = port.getForecastRecord(_getForecastRecord_requestData);
        System.out.println("getForecastRecord.result=" + _getForecastRecord__return);


        }

        System.exit(0);
    }

}
