package com.haier.svc.purchase.omst3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T12:55:37.494+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://www.example.org/TransForecastInfoFromOMS/", name = "TransForecastInfoFromOMS")
@XmlSeeAlso({ObjectFactory.class})
public interface TransForecastInfoFromOMS {

    @WebResult(name = "requestDataReturn", targetNamespace = "")
    @RequestWrapper(localName = "TransForecastInfoFromOMS", targetNamespace = "http://www.example.org/TransForecastInfoFromOMS/", className = "com.haier.svc.purchase.omst3.TransForecastInfoFromOMS_Type")
    @WebMethod(operationName = "TransForecastInfoFromOMS", action = "http://www.example.org/TransForecastInfoFromOMS/TransForecastInfoFromOMS")
    @ResponseWrapper(localName = "TransForecastInfoFromOMSResponse", targetNamespace = "http://www.example.org/TransForecastInfoFromOMS/", className = "com.haier.svc.purchase.omst3.TransForecastInfoFromOMSResponse")
    public com.haier.svc.purchase.omst3.ResponseData transForecastInfoFromOMS(
        @WebParam(name = "requestData", targetNamespace = "")
        com.haier.svc.purchase.omst3.RequestData requestData
    );
}
