package com.haier.svc.purchase.canceltidan;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-13T17:22:40.411+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "JdeAndLesLoseValidity", 
                  wsdlLocation = "JdeAndLesLoseValidity.wsdl",
                  targetNamespace = "http://www.example.org/JdeAndLesLoseValidity/") 
public class JdeAndLesLoseValidity_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/JdeAndLesLoseValidity/", "JdeAndLesLoseValidity");
    public final static QName JdeAndLesLoseValiditySOAP = new QName("http://www.example.org/JdeAndLesLoseValidity/", "JdeAndLesLoseValiditySOAP");
    static {
        URL url = JdeAndLesLoseValidity_Service.class.getResource("JdeAndLesLoseValidity.wsdl");
        if (url == null) {
            url = JdeAndLesLoseValidity_Service.class.getClassLoader().getResource("JdeAndLesLoseValidity.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(JdeAndLesLoseValidity_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "JdeAndLesLoseValidity.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public JdeAndLesLoseValidity_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public JdeAndLesLoseValidity_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JdeAndLesLoseValidity_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns JdeAndLesLoseValidity
     */
    @WebEndpoint(name = "JdeAndLesLoseValiditySOAP")
    public JdeAndLesLoseValidity getJdeAndLesLoseValiditySOAP() {
        return super.getPort(JdeAndLesLoseValiditySOAP, JdeAndLesLoseValidity.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JdeAndLesLoseValidity
     */
    @WebEndpoint(name = "JdeAndLesLoseValiditySOAP")
    public JdeAndLesLoseValidity getJdeAndLesLoseValiditySOAP(WebServiceFeature... features) {
        return super.getPort(JdeAndLesLoseValiditySOAP, JdeAndLesLoseValidity.class, features);
    }

}
