package com.haier.svc.purchase.querydninfofromlestoehaier;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-07T23:07:49.203+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://www.example.org/QueryDNinfoFromLEStoEhaier/", name = "QueryDNinfoFromLEStoEhaier")
@XmlSeeAlso({ObjectFactory.class})
public interface QueryDNinfoFromLEStoEhaier {

    @RequestWrapper(localName = "QueryDNinfoFromLEStoEhaier", targetNamespace = "http://www.example.org/QueryDNinfoFromLEStoEhaier/", className = "com.haier.svc.purchase.querydninfofromlestoehaier.QueryDNinfoFromLEStoEhaier_Type")
    @WebMethod(operationName = "QueryDNinfoFromLEStoEhaier", action = "http://www.example.org/QueryDNinfoFromLEStoEhaier/QueryDNinfoFromLEStoEhaier")
    @ResponseWrapper(localName = "QueryDNinfoFromLEStoEhaierResponse", targetNamespace = "http://www.example.org/QueryDNinfoFromLEStoEhaier/", className = "com.haier.svc.purchase.querydninfofromlestoehaier.QueryDNinfoFromLEStoEhaierResponse")
    public void queryDNinfoFromLEStoEhaier(
        @WebParam(name = "SysName", targetNamespace = "")
        java.lang.String sysName,
        @WebParam(name = "ZFLAG", targetNamespace = "")
        java.lang.String zflag,
        @WebParam(name = "INPUT", targetNamespace = "")
        java.util.List<com.haier.svc.purchase.querydninfofromlestoehaier.ZBSTKD> input,
        @WebParam(mode = WebParam.Mode.OUT, name = "FLAG", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> flag,
        @WebParam(mode = WebParam.Mode.OUT, name = "MESSAGE", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> message,
        @WebParam(mode = WebParam.Mode.OUT, name = "FAULT_DETAIL", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> faultDETAIL,
        @WebParam(mode = WebParam.Mode.OUT, name = "ZFLAG1", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> zflag1,
        @WebParam(mode = WebParam.Mode.OUT, name = "OUTPUT", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.haier.svc.purchase.querydninfofromlestoehaier.ZBSTKDWD>> output
    );
}
