package com.haier.svc.purchase.querydninfofromlestoehaier;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-07T23:07:49.320+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "QueryDNinfoFromLEStoEhaier", 
                  wsdlLocation = "file:/C:/Users/Administrator/Desktop/QueryDNinfoFromLEStoEhaier.wsdl",
                  targetNamespace = "http://www.example.org/QueryDNinfoFromLEStoEhaier/") 
public class QueryDNinfoFromLEStoEhaier_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/QueryDNinfoFromLEStoEhaier/", "QueryDNinfoFromLEStoEhaier");
    public final static QName QueryDNinfoFromLEStoEhaierSOAP = new QName("http://www.example.org/QueryDNinfoFromLEStoEhaier/", "QueryDNinfoFromLEStoEhaierSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Administrator/Desktop/QueryDNinfoFromLEStoEhaier.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueryDNinfoFromLEStoEhaier_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Administrator/Desktop/QueryDNinfoFromLEStoEhaier.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QueryDNinfoFromLEStoEhaier_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryDNinfoFromLEStoEhaier_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryDNinfoFromLEStoEhaier_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns QueryDNinfoFromLEStoEhaier
     */
    @WebEndpoint(name = "QueryDNinfoFromLEStoEhaierSOAP")
    public QueryDNinfoFromLEStoEhaier getQueryDNinfoFromLEStoEhaierSOAP() {
        return super.getPort(QueryDNinfoFromLEStoEhaierSOAP, QueryDNinfoFromLEStoEhaier.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryDNinfoFromLEStoEhaier
     */
    @WebEndpoint(name = "QueryDNinfoFromLEStoEhaierSOAP")
    public QueryDNinfoFromLEStoEhaier getQueryDNinfoFromLEStoEhaierSOAP(WebServiceFeature... features) {
        return super.getPort(QueryDNinfoFromLEStoEhaierSOAP, QueryDNinfoFromLEStoEhaier.class, features);
    }

}
