package com.haier.vehicle.wsdl.queryDNFrom;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-02-01T19:02:54.335+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.example.org/QueryDNFromLEStoAPP/", name = "QueryDNFromLEStoAPP")
@XmlSeeAlso({ObjectFactory.class})
public interface QueryDNFromLEStoAPP {

    @WebMethod(operationName = "QueryDNFromLEStoAPP", action = "http://www.example.org/QueryDNFromLEStoAPP/QueryDNFromLEStoAPP")
    @RequestWrapper(localName = "QueryDNFromLEStoAPP", targetNamespace = "http://www.example.org/QueryDNFromLEStoAPP/", className = "com.haier.vehicle.wsdl.queryDNFrom.QueryDNFromLEStoAPP_Type")
    @ResponseWrapper(localName = "QueryDNFromLEStoAPPResponse", targetNamespace = "http://www.example.org/QueryDNFromLEStoAPP/", className = "com.haier.vehicle.wsdl.queryDNFrom.QueryDNFromLEStoAPPResponse")
    public void queryDNFromLEStoAPP(
        @WebParam(name = "CALLCODE", targetNamespace = "")
        java.lang.String callcode,
        @WebParam(name = "SOURCE", targetNamespace = "")
        java.lang.String source,
        @WebParam(name = "INPUT", targetNamespace = "")
        java.util.List<com.haier.vehicle.wsdl.queryDNFrom.ZINTWXWTLOG> input,
        @WebParam(mode = WebParam.Mode.OUT, name = "FLAG", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> flag,
        @WebParam(mode = WebParam.Mode.OUT, name = "MESSAGE", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> message
    );
}
