/*
 * 
 */

package com.haier.stock.eai.finance.pushreturn.query;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.2.3
 * Tue Aug 06 10:09:30 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebServiceClient(name = "QueryHandleResultFromGVS", wsdlLocation = "file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/QueryHandleResultFromGVS.wsdl", targetNamespace = "http://www.example.org/QueryHandleResultFromGVS/")
public class QueryHandleResultFromGVS_Service extends Service {

    public final static URL   WSDL_LOCATION;
    public final static QName SERVICE                      = new QName(
                                                               "http://www.example.org/QueryHandleResultFromGVS/",
                                                               "QueryHandleResultFromGVS");
    public final static QName QueryHandleResultFromGVSSOAP = new QName(
                                                               "http://www.example.org/QueryHandleResultFromGVS/",
                                                               "QueryHandleResultFromGVSSOAP");
    static {
        URL url = null;
        try {
            url = new URL(
                "file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/QueryHandleResultFromGVS.wsdl");
        } catch (MalformedURLException e) {
            System.err
                .println("Can not initialize the default wsdl from file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/QueryHandleResultFromGVS.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public QueryHandleResultFromGVS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryHandleResultFromGVS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryHandleResultFromGVS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns QueryHandleResultFromGVS
     */
    @WebEndpoint(name = "QueryHandleResultFromGVSSOAP")
    public QueryHandleResultFromGVS getQueryHandleResultFromGVSSOAP() {
        return super.getPort(QueryHandleResultFromGVSSOAP, QueryHandleResultFromGVS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryHandleResultFromGVS
     */
    @WebEndpoint(name = "QueryHandleResultFromGVSSOAP")
    public QueryHandleResultFromGVS getQueryHandleResultFromGVSSOAP(WebServiceFeature... features) {
        return super
            .getPort(QueryHandleResultFromGVSSOAP, QueryHandleResultFromGVS.class, features);
    }

}
