package com.haier.traderate.services.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-11-03T18:36:08.445+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://demo.server.webservice.cc.neusoft.com/", name = "DemoWs")
@XmlSeeAlso({ObjectFactory.class})
public interface DemoWs {

    @WebMethod
    @RequestWrapper(localName = "rrsResult", targetNamespace = "http://demo.server.webservice.cc.neusoft.com/", className = "com.ehaier.eop.review.stock.service.impl.RrsResult")
    @ResponseWrapper(localName = "rrsResultResponse", targetNamespace = "http://demo.server.webservice.cc.neusoft.com/", className = "com.ehaier.eop.review.stock.service.impl.RrsResultResponse")
    @WebResult(name = "return", targetNamespace = "")
    public RrsOrder rrsResult(
            @WebParam(name = "arg0", targetNamespace = "")
                    RrsOrder arg0
    );

    @WebMethod
    @RequestWrapper(localName = "testWs", targetNamespace = "http://demo.server.webservice.cc.neusoft.com/", className = "com.ehaier.eop.review.stock.service.impl.TestWs")
    @ResponseWrapper(localName = "testWsResponse", targetNamespace = "http://demo.server.webservice.cc.neusoft.com/", className = "com.ehaier.eop.review.stock.service.impl.TestWsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public DemoVo testWs(
            @WebParam(name = "arg0", targetNamespace = "")
                    DemoVo arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getVo", targetNamespace = "http://demo.server.webservice.cc.neusoft.com/", className = "com.ehaier.eop.review.stock.service.impl.GetVo")
    @ResponseWrapper(localName = "getVoResponse", targetNamespace = "http://demo.server.webservice.cc.neusoft.com/", className = "com.ehaier.eop.review.stock.service.impl.GetVoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public DemoVo getVo();

    @WebMethod
    @RequestWrapper(localName = "ehaierOrderShare", targetNamespace = "http://demo.server.webservice.cc.neusoft.com/", className = "com.ehaier.eop.review.stock.service.impl.EhaierOrderShare")
    @ResponseWrapper(localName = "ehaierOrderShareResponse", targetNamespace = "http://demo.server.webservice.cc.neusoft.com/", className = "com.ehaier.eop.review.stock.service.impl.EhaierOrderShareResponse")
    @WebResult(name = "return", targetNamespace = "")
    public EhaierOrder ehaierOrderShare(
            @WebParam(name = "arg0", targetNamespace = "")
                    EhaierOrder arg0
    );

    @WebMethod
    @RequestWrapper(localName = "upQygResult", targetNamespace = "http://demo.server.webservice.cc.neusoft.com/", className = "com.ehaier.eop.review.stock.service.impl.UpQygResult")
    @ResponseWrapper(localName = "upQygResultResponse", targetNamespace = "http://demo.server.webservice.cc.neusoft.com/", className = "com.ehaier.eop.review.stock.service.impl.UpQygResultResponse")
    @WebResult(name = "return", targetNamespace = "")
    public QygOrder upQygResult(
            @WebParam(name = "arg0", targetNamespace = "")
                    QygOrder arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getHCSPHandleResultEhaier", targetNamespace = "http://demo.server.webservice.cc.neusoft.com/", className = "com.ehaier.eop.review.stock.service.impl.GetHCSPHandleResultEhaier")
    @ResponseWrapper(localName = "getHCSPHandleResultEhaierResponse", targetNamespace = "http://demo.server.webservice.cc.neusoft.com/", className = "com.ehaier.eop.review.stock.service.impl.GetHCSPHandleResultEhaierResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getHCSPHandleResultEhaier(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebMethod(operationName = "SQMOrderShare")
    @RequestWrapper(localName = "SQMOrderShare", targetNamespace = "http://demo.server.webservice.cc.neusoft.com/", className = "com.ehaier.eop.review.stock.service.impl.SQMOrderShare")
    @ResponseWrapper(localName = "SQMOrderShareResponse", targetNamespace = "http://demo.server.webservice.cc.neusoft.com/", className = "com.ehaier.eop.review.stock.service.impl.SQMOrderShareResponse")
    @WebResult(name = "return", targetNamespace = "")
    public SqmOrder sqmOrderShare(
            @WebParam(name = "arg0", targetNamespace = "")
                    SqmOrder arg0
    );
}
