
package com.haier.traderate.services.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-11-03T18:36:08.295+08:00
 * Generated source version: 3.1.12
 * 
 */
public final class DemoWs_DemoWsImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://demo.server.webservice.cc.neusoft.com/", "DemoWs");

    private DemoWs_DemoWsImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = DemoWs_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DemoWs_Service ss = new DemoWs_Service(wsdlURL, SERVICE_NAME);
        DemoWs port = ss.getDemoWsImplPort();  
        
        {
        System.out.println("Invoking rrsResult...");
        RrsOrder _rrsResult_arg0 = null;
        RrsOrder _rrsResult__return = port.rrsResult(_rrsResult_arg0);
        System.out.println("rrsResult.result=" + _rrsResult__return);


        }
        {
        System.out.println("Invoking testWs...");
        DemoVo _testWs_arg0 = null;
        DemoVo _testWs__return = port.testWs(_testWs_arg0);
        System.out.println("testWs.result=" + _testWs__return);


        }
        {
        System.out.println("Invoking getVo...");
        DemoVo _getVo__return = port.getVo();
        System.out.println("getVo.result=" + _getVo__return);


        }
        {
        System.out.println("Invoking ehaierOrderShare...");
        EhaierOrder _ehaierOrderShare_arg0 = null;
        EhaierOrder _ehaierOrderShare__return = port.ehaierOrderShare(_ehaierOrderShare_arg0);
        System.out.println("ehaierOrderShare.result=" + _ehaierOrderShare__return);


        }
        {
        System.out.println("Invoking upQygResult...");
        QygOrder _upQygResult_arg0 = null;
        QygOrder _upQygResult__return = port.upQygResult(_upQygResult_arg0);
        System.out.println("upQygResult.result=" + _upQygResult__return);


        }
        {
        System.out.println("Invoking getHCSPHandleResultEhaier...");
        String _getHCSPHandleResultEhaier_arg0 = "";
        String _getHCSPHandleResultEhaier__return = port.getHCSPHandleResultEhaier(_getHCSPHandleResultEhaier_arg0);
        System.out.println("getHCSPHandleResultEhaier.result=" + _getHCSPHandleResultEhaier__return);


        }
        {
        System.out.println("Invoking sqmOrderShare...");
        SqmOrder _sqmOrderShare_arg0 = null;
        SqmOrder _sqmOrderShare__return = port.sqmOrderShare(_sqmOrderShare_arg0);
        System.out.println("sqmOrderShare.result=" + _sqmOrderShare__return);


        }

        System.exit(0);
    }

}
