package com.haier.traderate.services.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-11-03T18:36:08.480+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "DemoWs", 
                  wsdlLocation = "http://10.155.3.3//DemoWs?wsdl",
                  targetNamespace = "http://demo.server.webservice.cc.neusoft.com/") 
public class DemoWs_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://demo.server.webservice.cc.neusoft.com/", "DemoWs");
    public final static QName DemoWsImplPort = new QName("http://demo.server.webservice.cc.neusoft.com/", "DemoWsImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.155.3.3//DemoWs?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DemoWs_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.155.3.3//DemoWs?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DemoWs_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DemoWs_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemoWs_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns DemoWs
     */
    @WebEndpoint(name = "DemoWsImplPort")
    public DemoWs getDemoWsImplPort() {
        return super.getPort(DemoWsImplPort, DemoWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DemoWs
     */
    @WebEndpoint(name = "DemoWsImplPort")
    public DemoWs getDemoWsImplPort(WebServiceFeature... features) {
        return super.getPort(DemoWsImplPort, DemoWs.class, features);
    }

}
