package com.haier.stock.eai.createpurchaseordertoles;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-11-03T16:32:46.984+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://www.example.org/CreateSCOrderToLES/", name = "CreateSCOrderToLES")
@XmlSeeAlso({ ObjectFactory.class })
public interface CreateSCOrderToLES {

    @WebResult(name = "Output", targetNamespace = "")
    @RequestWrapper(localName = "CreateSCOrderToLES", targetNamespace = "http://www.example.org/CreateSCOrderToLES/", className = "org.example.createscordertoles.CreateSCOrderToLES_Type")
    @WebMethod(operationName = "CreateSCOrderToLES", action = "http://www.example.org/CreateSCOrderToLES/CreateSCOrderToLES")
    @ResponseWrapper(localName = "CreateSCOrderToLESResponse", targetNamespace = "http://www.example.org/CreateSCOrderToLES/", className = "org.example.createscordertoles.CreateSCOrderToLESResponse")
    public java.util.List<com.haier.stock.eai.createpurchaseordertoles.OutputType> createSCOrderToLES(
        @WebParam(name = "Input", targetNamespace = "") java.util.List<com.haier.stock.eai.createpurchaseordertoles.InputType> input);
}
