package com.haier.svc.purchase.omsquery;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-12-06T18:41:26.953+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "QueryOrderFromEHaierToOMS", 
                  wsdlLocation = "file:/D:/java/QueryOrderFromEHaierToOMS.wsdl",
                  targetNamespace = "http://www.example.org/QueryOrderFromEHaierToOMS/") 
public class QueryOrderFromEHaierToOMS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/QueryOrderFromEHaierToOMS/", "QueryOrderFromEHaierToOMS");
    public final static QName QueryOrderFromEHaierToOMSSOAP = new QName("http://www.example.org/QueryOrderFromEHaierToOMS/", "QueryOrderFromEHaierToOMSSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/java/QueryOrderFromEHaierToOMS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueryOrderFromEHaierToOMS_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/java/QueryOrderFromEHaierToOMS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QueryOrderFromEHaierToOMS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryOrderFromEHaierToOMS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryOrderFromEHaierToOMS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns QueryOrderFromEHaierToOMS
     */
    @WebEndpoint(name = "QueryOrderFromEHaierToOMSSOAP")
    public QueryOrderFromEHaierToOMS getQueryOrderFromEHaierToOMSSOAP() {
        return super.getPort(QueryOrderFromEHaierToOMSSOAP, QueryOrderFromEHaierToOMS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryOrderFromEHaierToOMS
     */
    @WebEndpoint(name = "QueryOrderFromEHaierToOMSSOAP")
    public QueryOrderFromEHaierToOMS getQueryOrderFromEHaierToOMSSOAP(WebServiceFeature... features) {
        return super.getPort(QueryOrderFromEHaierToOMSSOAP, QueryOrderFromEHaierToOMS.class, features);
    }

}
