package com.haier.svc.purchase.omsquery;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-12-06T18:41:26.931+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.example.org/QueryOrderFromEHaierToOMS/", name = "QueryOrderFromEHaierToOMS")
@XmlSeeAlso({ObjectFactory.class})
public interface QueryOrderFromEHaierToOMS {

    @WebMethod(operationName = "QueryOrderFromEHaierToOMS", action = "http://www.example.org/QueryOrderFromEHaierToOMS/QueryOrderFromEHaierToOMS")
    @RequestWrapper(localName = "QueryOrderFromEHaierToOMS", targetNamespace = "http://www.example.org/QueryOrderFromEHaierToOMS/", className = "com.haier.svc.purchase.omsquery.QueryOrderFromEHaierToOMS_Type")
    @ResponseWrapper(localName = "QueryOrderFromEHaierToOMSResponse", targetNamespace = "http://www.example.org/QueryOrderFromEHaierToOMS/", className = "com.haier.svc.purchase.omsquery.QueryOrderFromEHaierToOMSResponse")
    @WebResult(name = "requestDataReturn", targetNamespace = "")
    public java.util.List<com.haier.svc.purchase.omsquery.ResponseData> queryOrderFromEHaierToOMS(
        @WebParam(name = "requestData", targetNamespace = "")
        com.haier.svc.purchase.omsquery.RequestData requestData
    );
}
