
package com.haier.stock.exchangegoodstoles;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-01T17:03:46.258+08:00
 * Generated source version: 3.2.4
 *
 */
public final class ExchangeGoodsToLES_ExchangeGoodsToLESSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/ExchangeGoodsToLES/", "ExchangeGoodsToLES");

    private ExchangeGoodsToLES_ExchangeGoodsToLESSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ExchangeGoodsToLES_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ExchangeGoodsToLES_Service ss = new ExchangeGoodsToLES_Service(wsdlURL, SERVICE_NAME);
        ExchangeGoodsToLES port = ss.getExchangeGoodsToLESSOAP();

        {
        System.out.println("Invoking exchangeGoodsToLES...");
        com.haier.stock.exchangegoodstoles.ExchangeGoodsToLES_Type.INPUT _exchangeGoodsToLES_input = null;
        com.haier.stock.exchangegoodstoles.ExchangeGoodsToLESResponse.OUTPUT _exchangeGoodsToLES__return = port.exchangeGoodsToLES(_exchangeGoodsToLES_input);
        System.out.println("exchangeGoodsToLES.result=" + _exchangeGoodsToLES__return);


        }

        System.exit(0);
    }

}
