package com.haier.stock.exchangegoodstoles;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-01T17:03:46.305+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://www.example.org/ExchangeGoodsToLES/", name = "ExchangeGoodsToLES")
@XmlSeeAlso({ObjectFactory.class})
public interface ExchangeGoodsToLES {

    @WebMethod(operationName = "ExchangeGoodsToLES", action = "http://www.example.org/ExchangeGoodsToLES/ExchangeGoodsToLES")
    @RequestWrapper(localName = "ExchangeGoodsToLES", targetNamespace = "http://www.example.org/ExchangeGoodsToLES/", className = "com.haier.stock.exchangegoodstoles.ExchangeGoodsToLES_Type")
    @ResponseWrapper(localName = "ExchangeGoodsToLESResponse", targetNamespace = "http://www.example.org/ExchangeGoodsToLES/", className = "com.haier.stock.exchangegoodstoles.ExchangeGoodsToLESResponse")
    @WebResult(name = "OUTPUT", targetNamespace = "")
    public com.haier.stock.exchangegoodstoles.ExchangeGoodsToLESResponse.OUTPUT exchangeGoodsToLES(
        @WebParam(name = "INPUT", targetNamespace = "")
        com.haier.stock.exchangegoodstoles.ExchangeGoodsToLES_Type.INPUT input
    );
}
