package com.haier.stock.exchangegoodstoles;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-01T17:03:46.315+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "ExchangeGoodsToLES",
                  wsdlLocation = "file:/D:/ExchangeGoodsToLES.WSDL",
                  targetNamespace = "http://www.example.org/ExchangeGoodsToLES/")
public class ExchangeGoodsToLES_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/ExchangeGoodsToLES/", "ExchangeGoodsToLES");
    public final static QName ExchangeGoodsToLESSOAP = new QName("http://www.example.org/ExchangeGoodsToLES/", "ExchangeGoodsToLESSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/ExchangeGoodsToLES.WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ExchangeGoodsToLES_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/ExchangeGoodsToLES.WSDL");
        }
        WSDL_LOCATION = url;
    }

    public ExchangeGoodsToLES_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ExchangeGoodsToLES_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExchangeGoodsToLES_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ExchangeGoodsToLES_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ExchangeGoodsToLES_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ExchangeGoodsToLES_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ExchangeGoodsToLES
     */
    @WebEndpoint(name = "ExchangeGoodsToLESSOAP")
    public ExchangeGoodsToLES getExchangeGoodsToLESSOAP() {
        return super.getPort(ExchangeGoodsToLESSOAP, ExchangeGoodsToLES.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExchangeGoodsToLES
     */
    @WebEndpoint(name = "ExchangeGoodsToLESSOAP")
    public ExchangeGoodsToLES getExchangeGoodsToLESSOAP(WebServiceFeature... features) {
        return super.getPort(ExchangeGoodsToLESSOAP, ExchangeGoodsToLES.class, features);
    }

}
