package com.haier.stock.eai.getinvrebateinfofromihs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.2.3
 * Mon Jun 17 15:59:56 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebServiceClient(name = "GetInvRebateInfoFromIHS", wsdlLocation = "file:/Users/benio/Documents/projects/wsdl-creator/wsdl-creator/src/main/resources/GetInvRebateInfoFromIHS.wsdl", targetNamespace = "http://www.example.org/GetInvRebateInfoFromIHS/")
public class GetInvRebateInfoFromIHS_Service extends Service {

    public final static URL   WSDL_LOCATION;
    public final static QName SERVICE                     = new QName(
                                                              "http://www.example.org/GetInvRebateInfoFromIHS/",
                                                              "GetInvRebateInfoFromIHS");
    public final static QName GetInvRebateInfoFromIHSSOAP = new QName(
                                                              "http://www.example.org/GetInvRebateInfoFromIHS/",
                                                              "GetInvRebateInfoFromIHSSOAP");
    static {
        URL url = null;
        try {
            url = new URL(
                "file:/Users/benio/Documents/projects/wsdl-creator/wsdl-creator/src/main/resources/GetInvRebateInfoFromIHS.wsdl");
        } catch (MalformedURLException e) {
            System.err
                .println("Can not initialize the default wsdl from file:/Users/benio/Documents/projects/wsdl-creator/wsdl-creator/src/main/resources/GetInvRebateInfoFromIHS.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public GetInvRebateInfoFromIHS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetInvRebateInfoFromIHS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetInvRebateInfoFromIHS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns GetInvRebateInfoFromIHS
     */
    @WebEndpoint(name = "GetInvRebateInfoFromIHSSOAP")
    public GetInvRebateInfoFromIHS getGetInvRebateInfoFromIHSSOAP() {
        return super.getPort(GetInvRebateInfoFromIHSSOAP, GetInvRebateInfoFromIHS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetInvRebateInfoFromIHS
     */
    @WebEndpoint(name = "GetInvRebateInfoFromIHSSOAP")
    public GetInvRebateInfoFromIHS getGetInvRebateInfoFromIHSSOAP(WebServiceFeature... features) {
        return super.getPort(GetInvRebateInfoFromIHSSOAP, GetInvRebateInfoFromIHS.class, features);
    }

}
