package com.haier.stock.eai.getinvrebateinfofromihs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Mon Jun 17 15:59:56 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebService(targetNamespace = "http://www.example.org/GetInvRebateInfoFromIHS/", name = "GetInvRebateInfoFromIHS")
@XmlSeeAlso({ ObjectFactory.class })
public interface GetInvRebateInfoFromIHS {

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "GetInvRebateInfoFromIHS", targetNamespace = "http://www.example.org/GetInvRebateInfoFromIHS/", className = "org.example.getinvrebateinfofromihs.GetInvRebateInfoFromIHS_Type")
    @ResponseWrapper(localName = "GetInvRebateInfoFromIHSResponse", targetNamespace = "http://www.example.org/GetInvRebateInfoFromIHS/", className = "org.example.getinvrebateinfofromihs.GetInvRebateInfoFromIHSResponse")
    @WebMethod(operationName = "GetInvRebateInfoFromIHS", action = "http://www.example.org/GetInvRebateInfoFromIHS/GetInvRebateInfoFromIHS")
    public com.haier.stock.eai.getinvrebateinfofromihs.OutputType getInvRebateInfoFromIHS(
        @WebParam(name = "in", targetNamespace = "") com.haier.stock.eai.getinvrebateinfofromihs.InputType in);
}
