package com.haier.stock.eai.finance.transcancelorderinfofromehaiersap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 22 09:25:54 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebService(targetNamespace = "http://www.example.org/TransCancelOrderInfoFromEhaierSAP/", name = "TransCancelOrderInfoFromEhaierSAP")
@XmlSeeAlso({ ObjectFactory.class })
public interface TransCancelOrderInfoFromEhaierSAP {

    @WebResult(name = "T_ZMMS0110", targetNamespace = "")
    @RequestWrapper(localName = "TransCancelOrderInfoFromEhaierSAP", targetNamespace = "http://www.example.org/TransCancelOrderInfoFromEhaierSAP/", className = "org.example.transcancelorderinfofromehaiersap.TransCancelOrderInfoFromEhaierSAP_Type")
    @ResponseWrapper(localName = "TransCancelOrderInfoFromEhaierSAPResponse", targetNamespace = "http://www.example.org/TransCancelOrderInfoFromEhaierSAP/", className = "org.example.transcancelorderinfofromehaiersap.TransCancelOrderInfoFromEhaierSAPResponse")
    @WebMethod(operationName = "TransCancelOrderInfoFromEhaierSAP", action = "http://www.example.org/TransCancelOrderInfoFromEhaierSAP/TransCancelOrderInfoFromEhaierSAP")
    public java.util.List<com.haier.stock.eai.finance.transcancelorderinfofromehaiersap.ZMMS0110> transCancelOrderInfoFromEhaierSAP(
        @WebParam(name = "T_ZMMS0104", targetNamespace = "") java.util.List<com.haier.stock.eai.finance.transcancelorderinfofromehaiersap.ZMMS0104> tZMMS0104);
}
