/*
 * 
 */

package com.haier.stock.eai.finance.transcancelorderinfofromehaiersap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 22 09:25:54 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebServiceClient(name = "TransCancelOrderInfoFromEhaierSAP", wsdlLocation = "file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/TransCancelOrderInfoFromEhaierSAP.wsdl", targetNamespace = "http://www.example.org/TransCancelOrderInfoFromEhaierSAP/")
public class TransCancelOrderInfoFromEhaierSAP_Service extends Service {

    public final static URL   WSDL_LOCATION;
    public final static QName SERVICE                               = new QName(
                                                                        "http://www.example.org/TransCancelOrderInfoFromEhaierSAP/",
                                                                        "TransCancelOrderInfoFromEhaierSAP");
    public final static QName TransCancelOrderInfoFromEhaierSAPSOAP = new QName(
                                                                        "http://www.example.org/TransCancelOrderInfoFromEhaierSAP/",
                                                                        "TransCancelOrderInfoFromEhaierSAPSOAP");
    static {
        URL url = null;
        try {
            url = new URL(
                "file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/TransCancelOrderInfoFromEhaierSAP.wsdl");
        } catch (MalformedURLException e) {
            System.err
                .println("Can not initialize the default wsdl from file:/F:/My_Job/Hair_Job/workspace/wsdl-creator/wsdl-creator/src/main/resources/TransCancelOrderInfoFromEhaierSAP.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public TransCancelOrderInfoFromEhaierSAP_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TransCancelOrderInfoFromEhaierSAP_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransCancelOrderInfoFromEhaierSAP_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns TransCancelOrderInfoFromEhaierSAP
     */
    @WebEndpoint(name = "TransCancelOrderInfoFromEhaierSAPSOAP")
    public TransCancelOrderInfoFromEhaierSAP getTransCancelOrderInfoFromEhaierSAPSOAP() {
        return super.getPort(TransCancelOrderInfoFromEhaierSAPSOAP,
            TransCancelOrderInfoFromEhaierSAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransCancelOrderInfoFromEhaierSAP
     */
    @WebEndpoint(name = "TransCancelOrderInfoFromEhaierSAPSOAP")
    public TransCancelOrderInfoFromEhaierSAP getTransCancelOrderInfoFromEhaierSAPSOAP(WebServiceFeature... features) {
        return super.getPort(TransCancelOrderInfoFromEhaierSAPSOAP,
            TransCancelOrderInfoFromEhaierSAP.class, features);
    }

}
