
package com.haier.order.wsdl.mdm;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-03-06T10:37:21.835+08:00
 * Generated source version: 3.1.12
 * 
 */
public final class SelectInfoFromMDM_SelectInfoFromMDMSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/SelectInfoFromMDM/", "SelectInfoFromMDM");

    private SelectInfoFromMDM_SelectInfoFromMDMSOAP_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SelectInfoFromMDM_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SelectInfoFromMDM_Service ss = new SelectInfoFromMDM_Service(wsdlURL, SERVICE_NAME);
        SelectInfoFromMDM port = ss.getSelectInfoFromMDMSOAP();  
        
        {
        System.out.println("Invoking selectInfoFromMDMOP...");
        InType _selectInfoFromMDMOP_in = null;
        SelectInfoFromMDMOPResponse.Output _selectInfoFromMDMOP__return = port.selectInfoFromMDMOP(_selectInfoFromMDMOP_in);
        System.out.println("selectInfoFromMDMOP.result=" + _selectInfoFromMDMOP__return);


        }

        System.exit(0);
    }

}
