package com.haier.order.wsdl.mdm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-03-06T10:37:22.263+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.example.org/SelectInfoFromMDM/", name = "SelectInfoFromMDM")
@XmlSeeAlso({ObjectFactory.class})
public interface SelectInfoFromMDM {

    @WebMethod(operationName = "SelectInfoFromMDM_OP", action = "http://www.example.org/SelectInfoFromMDM/SelectInfoFromMDM_OP")
    @RequestWrapper(localName = "SelectInfoFromMDM_OP", targetNamespace = "http://www.example.org/SelectInfoFromMDM/", className = "com.haier.order.wsdl.mdm.SelectInfoFromMDMOP")
    @ResponseWrapper(localName = "SelectInfoFromMDM_OPResponse", targetNamespace = "http://www.example.org/SelectInfoFromMDM/", className = "com.haier.order.wsdl.mdm.SelectInfoFromMDMOPResponse")
    @WebResult(name = "Output", targetNamespace = "")
    public SelectInfoFromMDMOPResponse.Output selectInfoFromMDMOP(
            @WebParam(name = "in", targetNamespace = "")
                    InType in
    );
}
