package com.haier.svc.purchase.queryfrostorderfromehaiertooms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2016-01-28T16:10:42.856+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://www.example.org/QueryFrostOrderFromEHAIERToOMS/", name = "QueryFrostOrderFromEHAIERToOMS")
@XmlSeeAlso({ObjectFactory.class})
public interface QueryFrostOrderFromEHAIERToOMS {

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "QueryFrostOrderFromEHAIERToOMS", targetNamespace = "http://www.example.org/QueryFrostOrderFromEHAIERToOMS/", className = "com.haier.svc.purchase.queryfrostorderfromehaiertooms.QueryFrostOrderFromEHAIERToOMS_Type")
    @WebMethod(operationName = "QueryFrostOrderFromEHAIERToOMS", action = "http://www.example.org/QueryFrostOrderFromEHAIERToOMS/QueryFrostOrderFromEHAIERToOMS")
    @ResponseWrapper(localName = "QueryFrostOrderFromEHAIERToOMSResponse", targetNamespace = "http://www.example.org/QueryFrostOrderFromEHAIERToOMS/", className = "com.haier.svc.purchase.queryfrostorderfromehaiertooms.QueryFrostOrderFromEHAIERToOMSResponse")
    public com.haier.svc.bean.queryfrostorderfromehaiertooms.OutType queryFrostOrderFromEHAIERToOMS(
        @WebParam(name = "in", targetNamespace = "")
        com.haier.svc.bean.queryfrostorderfromehaiertooms.InType in
    );
}
