package com.haier.svc.purchase.queryfrostorderfromehaiertooms;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2016-01-28T16:10:42.990+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "QueryFrostOrderFromEHAIERToOMS", 
                  wsdlLocation = "QueryFrostOrderFromEHAIERToOMS.wsdl",
                  targetNamespace = "http://www.example.org/QueryFrostOrderFromEHAIERToOMS/") 
public class QueryFrostOrderFromEHAIERToOMS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/QueryFrostOrderFromEHAIERToOMS/", "QueryFrostOrderFromEHAIERToOMS");
    public final static QName QueryFrostOrderFromEHAIERToOMSSOAP = new QName("http://www.example.org/QueryFrostOrderFromEHAIERToOMS/", "QueryFrostOrderFromEHAIERToOMSSOAP");
    static {
        URL url = QueryFrostOrderFromEHAIERToOMS_Service.class.getResource("QueryFrostOrderFromEHAIERToOMS.wsdl");
        if (url == null) {
            url = QueryFrostOrderFromEHAIERToOMS_Service.class.getClassLoader().getResource("QueryFrostOrderFromEHAIERToOMS.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(QueryFrostOrderFromEHAIERToOMS_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "QueryFrostOrderFromEHAIERToOMS.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public QueryFrostOrderFromEHAIERToOMS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryFrostOrderFromEHAIERToOMS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryFrostOrderFromEHAIERToOMS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns QueryFrostOrderFromEHAIERToOMS
     */
    @WebEndpoint(name = "QueryFrostOrderFromEHAIERToOMSSOAP")
    public QueryFrostOrderFromEHAIERToOMS getQueryFrostOrderFromEHAIERToOMSSOAP() {
        return super.getPort(QueryFrostOrderFromEHAIERToOMSSOAP, QueryFrostOrderFromEHAIERToOMS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryFrostOrderFromEHAIERToOMS
     */
    @WebEndpoint(name = "QueryFrostOrderFromEHAIERToOMSSOAP")
    public QueryFrostOrderFromEHAIERToOMS getQueryFrostOrderFromEHAIERToOMSSOAP(WebServiceFeature... features) {
        return super.getPort(QueryFrostOrderFromEHAIERToOMSSOAP, QueryFrostOrderFromEHAIERToOMS.class, features);
    }

}
