package com.haier.afterSale.webService.cancelDispatchedWorkers;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-06-04T11:12:59.858+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/MyFirstSOA/TransOrderCancelFromEHAIERToHP/TransOrderCancelFromEHAIERToHP", name = "TransOrderCancelFromEHAIERToHP")
@XmlSeeAlso({ObjectFactory.class})
public interface TransOrderCancelFromEHAIERToHP {

    @WebMethod(action = "process")
    @RequestWrapper(localName = "process", targetNamespace = "http://xmlns.oracle.com/MyFirstSOA/TransOrderCancelFromEHAIERToHP/TransOrderCancelFromEHAIERToHP", className = "com.haier.afterSale.webService.cancelDispatchedWorkers.Process")
    @ResponseWrapper(localName = "processResponse", targetNamespace = "http://xmlns.oracle.com/MyFirstSOA/TransOrderCancelFromEHAIERToHP/TransOrderCancelFromEHAIERToHP", className = "com.haier.afterSale.webService.cancelDispatchedWorkers.ProcessResponse")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/MyFirstSOA/TransOrderCancelFromEHAIERToHP/TransOrderCancelFromEHAIERToHP")
    public Outputs process(
            @WebParam(name = "input", targetNamespace = "http://xmlns.oracle.com/MyFirstSOA/TransOrderCancelFromEHAIERToHP/TransOrderCancelFromEHAIERToHP")
                    java.util.List<Inputs> input
    );
}
