
package com.haier.afterSale.webService.cancelDispatchedWorkers;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-06-04T11:12:59.818+08:00
 * Generated source version: 3.1.11
 * 
 */
public final class TransOrderCancelFromEHAIERToHP_TransOrderCancelFromEHAIERToHPPt_Client {

    private static final QName SERVICE_NAME = new QName("http://xmlns.oracle.com/MyFirstSOA/TransOrderCancelFromEHAIERToHP/TransOrderCancelFromEHAIERToHP", "transordercancelfromehaiertohp_client_ep");

    private TransOrderCancelFromEHAIERToHP_TransOrderCancelFromEHAIERToHPPt_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = TransordercancelfromehaiertohpClientEp.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TransordercancelfromehaiertohpClientEp ss = new TransordercancelfromehaiertohpClientEp(wsdlURL, SERVICE_NAME);
        TransOrderCancelFromEHAIERToHP port = ss.getTransOrderCancelFromEHAIERToHPPt();  
        
        {
        System.out.println("Invoking process...");
        java.util.List<Inputs> _process_input = null;
        Outputs _process__return = port.process(_process_input);
        System.out.println("process.result=" + _process__return);


        }

        System.exit(0);
    }

}
