/*
 * 
 */

package com.haier.svc.purchase.selectmdminfofrommdmbyconditon;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.2.3
 * Mon Aug 12 15:02:15 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebServiceClient(name = "SelectMDMInfoFromMDMByConditon", wsdlLocation = "file:/G:/haier/eclipse/ws/wsdl-creator/src/main/resources/SelectMDMInfoFromMDMByConditon.wsdl", targetNamespace = "http://www.example.org/SelectMDMInfoFromMDMByConditon/")
public class SelectMDMInfoFromMDMByConditon_Service extends Service {

    public final static URL   WSDL_LOCATION;
    public final static QName SERVICE                            = new QName(
                                                                     "http://www.example.org/SelectMDMInfoFromMDMByConditon/",
                                                                     "SelectMDMInfoFromMDMByConditon");
    public final static QName SelectMDMInfoFromMDMByConditonSOAP = new QName(
                                                                     "http://www.example.org/SelectMDMInfoFromMDMByConditon/",
                                                                     "SelectMDMInfoFromMDMByConditonSOAP");
    static {
        URL url = null;
        try {
            url = new URL(
                "file:/G:/haier/eclipse/ws/wsdl-creator/src/main/resources/SelectMDMInfoFromMDMByConditon.wsdl");
        } catch (MalformedURLException e) {
            System.err
                .println("Can not initialize the default wsdl from file:/G:/haier/eclipse/ws/wsdl-creator/src/main/resources/SelectMDMInfoFromMDMByConditon.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SelectMDMInfoFromMDMByConditon_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SelectMDMInfoFromMDMByConditon_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SelectMDMInfoFromMDMByConditon_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SelectMDMInfoFromMDMByConditon
     */
    @WebEndpoint(name = "SelectMDMInfoFromMDMByConditonSOAP")
    public SelectMDMInfoFromMDMByConditon getSelectMDMInfoFromMDMByConditonSOAP() {
        return super.getPort(SelectMDMInfoFromMDMByConditonSOAP,
            SelectMDMInfoFromMDMByConditon.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SelectMDMInfoFromMDMByConditon
     */
    @WebEndpoint(name = "SelectMDMInfoFromMDMByConditonSOAP")
    public SelectMDMInfoFromMDMByConditon getSelectMDMInfoFromMDMByConditonSOAP(WebServiceFeature... features) {
        return super.getPort(SelectMDMInfoFromMDMByConditonSOAP,
            SelectMDMInfoFromMDMByConditon.class, features);
    }

}
