package com.haier.svc.purchase.selectmdminfofrommdmbyconditon;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Mon Aug 12 15:02:15 CST 2013
 * Generated source version: 2.2.3
 * 
 */

@WebService(targetNamespace = "http://www.example.org/SelectMDMInfoFromMDMByConditon/", name = "SelectMDMInfoFromMDMByConditon")
@XmlSeeAlso({ ObjectFactory.class })
public interface SelectMDMInfoFromMDMByConditon {

    @WebResult(name = "Outputs", targetNamespace = "")
    @RequestWrapper(localName = "SelectMDMInfoFromMDMByConditon_OP", targetNamespace = "http://www.example.org/SelectMDMInfoFromMDMByConditon/", className = "org.example.selectmdminfofrommdmbyconditon.SelectMDMInfoFromMDMByConditonOP")
    @ResponseWrapper(localName = "SelectMDMInfoFromMDMByConditon_OPResponse", targetNamespace = "http://www.example.org/SelectMDMInfoFromMDMByConditon/", className = "org.example.selectmdminfofrommdmbyconditon.SelectMDMInfoFromMDMByConditonOPResponse")
    @WebMethod(operationName = "SelectMDMInfoFromMDMByConditon_OP", action = "http://www.example.org/SelectMDMInfoFromMDMByConditon/SelectMDMInfoFromMDMByConditon_OP")
    public com.haier.svc.purchase.selectmdminfofrommdmbyconditon.OutputsType selectMDMInfoFromMDMByConditonOP(@WebParam(name = "Inputs", targetNamespace = "") com.haier.svc.purchase.selectmdminfofrommdmbyconditon.InputsType inputs);
}
